### ISSUE TITLE
Trailers support in the package

### ISSUE THREAD

**Issue by doctorpangloss** [Benedicht/BestHTTP-Issues#100]
Previously you closed a gRPC related issue. The user incorrectly wrote "tailing" header and meant trailers. Are trailers supported in your implementation? What library are you using?

**Comment by Benedicht** [comment]
"tailing" was a pisspelling in the [issue's title](https://github.com/Benedicht/BestHTTP-Issues/issues/15), trailing headers support for HTTP/2 added back then for [v2.1.0](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/changelog.html#210-2020-06-29).

**Comment by Benedicht** [comment]
> What library are you using?

3rd party libraries are used only for TLS, Json and compression/decompression.
