### ISSUE TITLE
Unity WebGL WebSocket wss connection

### ISSUE THREAD

**Issue by wangdng** [Benedicht/BestHTTP-Issues#101]
![image](https://user-images.githubusercontent.com/16604274/172650784-a0f92ceb-eecb-424b-b562-3da60676c53d.png)
When I use WebSocket to connect to the server under Unity WebGL, this error will be reported when I use the wss connection. Does anyone know the answer?

**Comment by wangdng** [comment]
![image](https://user-images.githubusercontent.com/16604274/172651519-67de70d8-b136-4bae-ad5d-ef60c07c9dae.png)
When I test in WebGL, the browser will report this error, and I can't connect to the server.

**Comment by Benedicht** [comment]
The first one is thrown when the server and the client doesn't support the same set of TLS versions, so the TLS negotiation fails.
In [BestHTTP/2 v2.6.0](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/changelog.html#260-2022-03-03) the minimum supported TLS version is increased to v1.2, but here's a quick guide how you can enable TLS 1.1 too: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/HTTPS.html#how-to-enable-tls-11

The second one is closed with a Close Code of 1006. 1006 means that the connection is closed locally by the browser. 1006 can be quite anything, it might not even upgraded to the websocket protocol.

The two issues might relate, but without more information i can't say anything for sure.

**Comment by Benedicht** [comment]
Closing the issue because of inactivity.
