### ISSUE TITLE
Unity WebGL Addressables build throws exception when BestHTTP package is included

### ISSUE THREAD

**Issue by lnadi17** [Benedicht/BestHTTP-Issues#102]
This exact problem is described here: 
[https://forum.unity.com/threads/cannot-set-properties-of-undefined-setting-1-when-running-a-unitywebrequest.1248445/](https://forum.unity.com/threads/cannot-set-properties-of-undefined-setting-1-when-running-a-unitywebrequest.1248445/)

Basically, when I create a blank project and add Addressables package in it, as well as BestHTTP2 package, trying to call _LoadAssetsAsync_ method throws an exception. It can be fixed with replacing a line in _*.framework.js_, but I want to know if there's any global setting that I can change which gets rid of this exception, or any other solution that is cleaner than the current solution.

**Comment by Benedicht** [comment]
What version of the plugin are you using?

**Comment by lnadi17** [comment]
Thank you, I found that it needed an update, after update everything works fine. You can close this issue now.
