### ISSUE TITLE
ping timeout when my app is background

### ISSUE THREAD

**Issue by kailaisi** [Benedicht/BestHTTP-Issues#103]
### Problem
When my app is in the background, when a ping is received, the pong's reply is not executed. Even if the current network is great. This leads to the error of Timeout.

### reason
All message processing depends on the execution of the Update method. Update of Monibehavior cannot be performed when the app is in the background.
<img width="470" alt="image" src="https://user-images.githubusercontent.com/11023905/173596864-5af52874-3e32-4af4-967e-54ffb11ea979.png">

**Comment by Benedicht** [comment]
Yes, this is a known "limitation". Sure, the plugin could spin up a new thread to call `OnUpdate` from, but all users would have to deal with a new problem: Unity have a very limited set of APIs that support calls from the non Unity-main thread...

**Comment by kailaisi** [comment]
Whether the library considers to support  directly reply pong when receive a ping？

**Comment by Benedicht** [comment]
It might be possible with the Websocket protocol, but all other higher level protocols (SignalR Core, Socket.IO, etc.) are using the regular callbacks as everybody else.
