### ISSUE TITLE
BestHTTP outside Unity environment, as a standard Net DLL

### ISSUE THREAD

**Issue by silentdiverchris** [Benedicht/BestHTTP-Issues#107]
Hello there, this is not a bug report or enhancement request, more seeking advice if I may. I am tasked with writing a .Net monitoring system that communicates with an existing Unity application which uses BestHTTP to communicate between client and server. Essentially I am writing a non-Unity client emulator that uses the same protocol as the existing Unity client to talk to the same server.

The application I am writing does not need to be a Unity application and it's highly desirable that it isn't, so what I am trying to do is come up with a version of BestHTTP with the Unity dependencies removed, so I can use the library to handle the client side in a traditional .Net application that has no Unity dependencies.

I tried satisfying the UnityEngine dependencies with a few different NuGet packages and had it building, but on calling BestHTTP.HTTPManager.Setup() it throws an exception with an InnerException of 'SecurityException: ECall methods must be packaged into a system module.' and could find no way around that.

My current approach is removing the Unity dependencies completely, replacing the Unity calls to get the device identifier, the working directory and a Math function with native functionality, and removed some procedure attribute. I can now create a SocketManager object and link the event handlers, and now there are no Unity references I am not getting the 'ECall methods....' exception. However, on sending the first Emit I am not getting a response from the other end, nor do I get any events raised from any of the 'SocketManager.Socket.On' handlers.

Running equivalent code through a scratch Unity application with the standard BestHTTP addon does allow me to connect, the connect and disconnect and reconnect work OK and the events are raised, so I'm pretty confident the only difference is my having removed the Unity calls from the addon (and essentially turned it into a standard .Net DLL).

I've tried it with both Net Framework 472 and Net Core 6 in case that made a difference somehow, both produce identical results.

I'm not asking you to fix it or anything like that, more a case of asking is there any fundamental reason why this could not work in the way I'm approaching it.

Any advice would be much appreciated, thanks.

**Comment by silentdiverchris** [comment]
Further detail, the procedure attributes I removed were [ExecuteInEditMode] and [RuntimeInitializeOnLoadMethod], and I removed the MonoBehaviour base class, all from HTTPUpdateDelegator. Perhaps the removal of MonoBehaviour is the problem,

**Comment by Benedicht** [comment]
The `HTTPUpdateDelegator` calls `HTTPManager.OnUpdate();` and that's where all the callback processing (and other protocols related bookkeeping) is done. 
You have to call `HTTPManager.OnUpdate();` periodically somewhere too.
