### ISSUE TITLE
Can't get disconnected reason of socket.io3

### ISSUE THREAD

**Issue by CindyXL** [Benedicht/BestHTTP-Issues#108]
Socket.io document said the disconnect event would transfer the reason, but when I use BestHttp to detect the disconnection, there is no message passed.
<img width="883" alt="image" src="https://user-images.githubusercontent.com/49672550/176148122-3fa6440c-1f95-4bfe-9133-89350fc16984.png">

**Comment by Benedicht** [comment]
> Socket.io document said the disconnect event would transfer the reason

Could you point out where i could find this in the documentation?

**Comment by CindyXL** [comment]
> You can find it here. 
https://socket.io/docs/v3/client-socket-instance/#disconnect

**Comment by Benedicht** [comment]
I think there's a little misunderstanding, the disconnect event does not transfer the reason of the disconnection! The reason strings in the socket.io docs are not part of the socket.io protocol and they are entirely generated on the client.

BestHTTP/2 uses the `error` event when there's an unexpected and unrecoverable error detected and if possible it tries to reconnect. A `disconnect` event is fired when the client either disconnected gracefully (initiated by the client **or** server) or there's no more reconnect attempt.

You can find a flow chart with the events in the documentation: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/protocols/socketio/socketio.html#emitted-events
