### ISSUE TITLE
HttpManager.AbortAll causes prosessing connections to never finish

### ISSUE THREAD

**Issue by fsuhrau** [Benedicht/BestHTTP-Issues#109]
Hi,

in our mobile app we allow our users to use the same account on multible devices.
A login will invalidate the session on the other devices(s) since we have also background tasks running which do additional requests we do an HttpManager.AbortAll() to cancel all running requests to provide a clean state while logging in again.

if this happens more often BestHTTP logs:

GetNextAvailable - activeConnections(8) >= HTTPManager.MaxConnectionPerServer(8)

what i noticed so far is that connections which are in state processing never get closed & removed when AbortAll was called until we can't spawn new connections anymore.

the only way to free up this connections again is by restarting the app.

**Comment by Benedicht** [comment]
`HttpManager.AbortAll()` is used by the plugin when the application is shutting down and there's no turning back. I think your best option for now is keeping track of the requests and call `.Abort()` on them when needed.

You should be track active requests like this:
```cs
using BestHTTP;
using BestHTTP.Core;

List<HTTPRequest> activeRequests = new List<HTTPRequest>();

RequestEventHelper.OnEvent = (RequestEventInfo eventInfo) =>
{
    if (eventInfo.Event == RequestEvents.StateChange)
    {
        switch (eventInfo.State)
        {
            case HTTPRequestStates.Initial:
                activeRequests.Add(eventInfo.SourceRequest);
                break;

            case HTTPRequestStates.Finished:
            case HTTPRequestStates.Error:
            case HTTPRequestStates.Aborted:
            case HTTPRequestStates.ConnectionTimedOut:
            case HTTPRequestStates.TimedOut:
                activeRequests.Remove(eventInfo.SourceRequest);
                break;
        }
    }
};
```

**Comment by fsuhrau** [comment]
Thx for the response.
Maybe i missed this part in the documentation about the AbortAll. 
i will keep track of the requests on our end now and abort them manually.
