### ISSUE TITLE
[SignalrCore] Send/Invoke tasks don't complete if disconnected

### ISSUE THREAD

**Issue by discodonut** [Benedicht/BestHTTP-Issues#11]
If the connection is not currently connected, then InvokeImp will return early and the returned task will never complete.  If the connection is lost during a pending invocation, then the task will never complete.

It also looks like there's a bug where Send will always register as an invocation and send an invocation id?  The signalrcore spec says that non-blocking sends should send a nil invocation id.

**Comment by Benedicht** [comment]
@discodonut 

Thanks for the report! Fixed both issues. 

While the non-blocking invocation support is there, the plugin never sends out non-blocking invocations as every call of `InvokeImpl` has a callback where the plugin sets either the `Future` or `TaskCompletionSource` to completed(Assign/TrySetResult) or failed(Fail/TrySetException).
