### ISSUE TITLE
Is it possible to maintain socketio connection on android while the app is not in the foreground

### ISSUE THREAD

**Issue by mluketin** [Benedicht/BestHTTP-Issues#113]
Hi,

Is there a way to use Socketio on Android in a way that when user clicks Home button, the connection doesn't timeout? Right now, if I click home button, after timeout period, I see on server side that client disconnected.

Thanks,
Marin

**Comment by Benedicht** [comment]
On mobile platforms when the application is in the background, Unity stops calling Update functions and the plugin can't maintain the connection's state (sending and handling ping-pong requests) so it eventually times out.
