### ISSUE TITLE
Header names should be case insensitive (issues on systems with Turkish culture)

### ISSUE THREAD

**Issue by chris-yarbrough** [Benedicht/BestHTTP-Issues#114]
**Context**
In BestHTTP 2.6.2 header names are stored within a Dictionary in the HTTPResponse class. In the AddHeader method these names are made lowercase via the .NET string.ToLower() method.

**Issue**
On systems with a Turkish culture (e.g. "tr-TR"), this can cause unexpected issues if the server sends uppercase header names. For example, the uppercase letter "I" will be converted to a Turkish "ı" (without a dot) and not the expected "i" with a dot. Hence, if a client now queries for header names via the TryGetValue method on the dictionary, the name cannot be correctly retrieved unless the client knows all of the implementation details.

According to multiple HTTP specifications (e.g. RFC 2616), header names should be treated as case insensitive.
Here are some mentions: https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive

**Proposed Fix**
Do not use .ToLower() on header names. Instead allow clients to query both variants by using StringComparer.OrdinalIgnoreCase when creating the dictionary. There may be other locations within the library where this case must be covered.

**Additional Notes**
Using .ToLowerInvariant() on strings also fixes part of the problem (e.g. uppercase letter "I" will become the expected "i" even on Turkish systems), but is still formally incorrect. As per spec, the header name should be kept the way it was sent by the server and only dealt with in a case insensitive manner.

A dictionary can be initialized with a comparer like this:
`Headers = new Dictionary<string, List<string>>(response.Headers, StringComparer.OrdinalIgnoreCase)`

One might also be inclined to use StringComparer.InvariantCultureIgnoreCase just to be on the safe side. However, this will cost performance without benefit, as far as I know. The invariant culture setting can deal with special cases such as the German "ß" and "ss" meaning the same character, but as per spec, header names only contain ASCII characters. Ergo, the ordinal comparison is enough, as long as there is no cultural conversion done via the incorrect ToLower().

Here is some code to demonstrate my findings (C# using NUnit):

```
[Test]
public void ExampleTest_CaseInsensitiveDictionary_ThisWillFail()
{
	Thread.CurrentThread.CurrentCulture = new CultureInfo("tr-TR");
	
	var headers = new Dictionary<string, string>();
	headers.Add("I-ROBOT", "irrelevant value");

	// No matter what the server sends, both should be allowed as per spec.
	Assert.That(headers.ContainsKey("I-ROBOT"));
	Assert.That(headers.ContainsKey("i-robot"));
}

[Test]
public void ExampleTest_CaseInsensitiveDictionary_Fix()
{
	Thread.CurrentThread.CurrentCulture = new CultureInfo("tr-TR");
	
	var headers = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
	headers.Add("I-ROBOT", "irrelevant value");

	Assert.That(headers.ContainsKey("I-ROBOT"));
	Assert.That(headers.ContainsKey("i-robot"));
}

[Test]
public void ExampleTest_ToLower_ThisWillFail()
{
	Thread.CurrentThread.CurrentCulture = new CultureInfo("tr-TR");
	
	var headers = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
	
	// This is representative for what can happen in HTTPResponse.AddHeader(name, value)
	headers.Add("I-ROBOT".ToLower(), "irrelevant value");

	// Although the comparison ignores case, the symbols will have changed from
	// "I" to "ı" instead of "i".
	Assert.That(headers.ContainsKey("i-robot"));
}

[Test]
public void ExampleTest_ToLower_Fix()
{
	Thread.CurrentThread.CurrentCulture = new CultureInfo("tr-TR");
	
	var headers = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
	
	headers.Add("I-ROBOT", "irrelevant value");

	// Now Turkish I conversion is not performed, everything works.
	Assert.That(headers.ContainsKey("I-ROBOT"));
	Assert.That(headers.ContainsKey("i-robot"));
}
```

Thank you for your work! Best greetings from InnoGames and let me know if I can provide any more information. :)

**Comment by Benedicht** [comment]
Thanks for your detailed report!
