### ISSUE TITLE
HTTPUpdateDelegator improvements.

### ISSUE THREAD

**Issue by israellot** [Benedicht/BestHTTP-Issues#115]
If user accidently calls `public void SwapThreadingMode()`  twice, two threads would end up running. 
I believe a better approach would be to have a `SetThreadingMode(ThreadingMode mode)` method where the intention becomes explicit and it may be called multiple times during app's lifecycle without harm. It should kill the thread if moving back to unity's update, and restart it if moving to background.
Also, when running on background, there should be a pulse sent from the receiving thread to so that the thread can process data immediately without having to wait the delay expire. In my custom code I created a Pulse method 
``` 
        private  SemaphoreSlim _semaphore = new SemaphoreSlim(0, 1);
        public void Pulse()
        {
            if(IsThreaded)
            {
                HTTPManager.Logger.Information("HTTPUpdateDelegator", "Pulse");

                try
                {
                    _semaphore.Release(1);
                }
                catch { }
            }
        }
``` 
Then on your `ThreadFunc` you do ` _semaphore.Wait(ThreadFrequencyInMS);` instead of a Thread.Sleep or Task.Delay
It basically creates an cancellable delay. 
You could also use a cancellationToken for Task.Delay, but Thread.Sleep has no such option.
As i'm only using websockets, I call `HTTPUpdateDelegator.Instance?.Pulse();` from ReceiveThreadFunc to awake it.

**Comment by Benedicht** [comment]
Thanks for the feedback and suggestions!

In the next release there will be a couple new functions(`SetThreadingMode` and `PingUpdateThread`) and improvements
