### ISSUE TITLE
Reduce allocations for websocket using binary frames

### ISSUE THREAD

**Issue by israellot** [Benedicht/BestHTTP-Issues#116]
``` 
if (Type == WebSocketFrameTypes.Text || Type == WebSocketFrameTypes.Continuation)
                Data = BufferPool.Get((long)Length, true);
            else
                if (Length == 0)
                    Data = BufferPool.NoData;
                else
                    Data = new byte[Length];
````

I believe you could use pooled arrays for binary frames as well, and delay the array allocation to until the OnBinary is invoked. If there's no subscribed listener, no allocation would need to be made. 
Besides that, a second event could be added `OnBinaryUnsafe`, where the argument is the pooled array, maybe an ArraySegment or ReadOnlyMemory<byte>, where the user decides if they need to copy the data to retain or not. 
In my use case I could quickly look and interpreted the data in the pooled array and discard the processing so a lot of allocations would be avoided.

**Comment by israellot** [comment]
I would gladly send some PRs if you want.

**Comment by Benedicht** [comment]
In v2.7.0 WebSocket will contain a new `OnBinaryNoAlloc` event that receives the downloaded data wrapped as a BufferSegment.

Tried to follow Unity's naming with the NoAlloc posfix and i think it's more describing. The `Unsafe` postfix would indicate that unsafe code is in use, or it's unsafe to use the event.
