### ISSUE TITLE
Define for BESTHTTP_DISABLE_PROXY Not Working

### ISSUE THREAD

**Issue by RMichaelPickering** [Benedicht/BestHTTP-Issues#117]
As shown in the Websocket example, there's a define BESTHTTP_DISABLE_PROXY that could be used to disable any proxy, which applies to my use case. However, when it is so defined in the project, I get an error message as follows:
"**Assets\Best HTTP\Source\Connections\ConnectionHelper.cs(95,41): error CS1061: 'HTTPRequest' does not contain a definition for 'Proxy' and no accessible extension method 'Proxy' accepting a first argument of type 'HTTPRequest' could be found (are you missing a using directive or an assembly reference?)**"

I will implement a workaround by not including the proxy code in my Websocket implementation, and removing the define.

**Comment by RMichaelPickering** [comment]
Now after the workaround, I get two errors on the TLS Security addon examples... let me see if I need to pull in a newer release!

**Comment by RMichaelPickering** [comment]
I'm on the latest release, just commenting out the offending lines... the first was setting request.DisableCache to true at line 109 of BatchedTestEntry.cs.

**Comment by RMichaelPickering** [comment]
And the second error was caused by the same code on line 166 of CertificateManagerWindow.cs.

Perhaps this is because I set BESTHTTP_DISABLE_CACHING as a global define in my project?

**Comment by RMichaelPickering** [comment]
And commenting out both lines worked, my app is now building!

**Comment by RMichaelPickering** [comment]
@Benedicht In what release will this be fixed please?

**Comment by Benedicht** [comment]
It's included in [v2.7.0](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/changelog.html#270-2022-08-25).
