### ISSUE TITLE
Deserialize SignalR object with custom converter

### ISSUE THREAD

**Issue by fc-ts** [Benedicht/BestHTTP-Issues#118]
Hello,
I would need to deserialize a Json object arriving as a SignalR method parameter with a custom Newtonsoft converter.
Is it possibile to do?

Thanks in advance and have a nice day

**Comment by Benedicht** [comment]
You can use the one that [comes with the plugin](https://github.com/Benedicht/BestHTTP_Examples/blob/master/SignalRCore/Encoders/JsonDotNetEncoder.cs), here's the guide how you can enable it: [How to Enable and Use Newtonsoft’s JSON .NET For Unity Encoder](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/protocols/signalr_core/Encoders.html#how-to-enable-and-use-newtonsofts-json-net-for-unity-encoder).
Or you can create a copy and modify it for your needs.
