### ISSUE TITLE
UploadStream problem

### ISSUE THREAD

**Issue by ibarban** [Benedicht/BestHTTP-Issues#12]
Hi,

I am having some problem when using UploadStream.
When I try to upload around 100MB of data, the request.Exception property gives "Unable to write data to the transport connection: The socket has been shut down.". On the other hand, on the server side I get "An existing connection was forcibly closed by the remote host".
I think that the error is not related to the amount of data but rather the time needed to upload something.
What would be the best way to find the cause of the problem?
Thanks.

**Comment by Benedicht** [comment]
@ibarban 

Could you set the plugin's log level to All and send the log file to my email address (besthttp@gmail.com)?
