### ISSUE TITLE
waiting long time when first request

### ISSUE THREAD

**Issue by LongMarch7** [Benedicht/BestHTTP-Issues#120]
i use HTTPRequest for get request。always，first request need wait long time

**Comment by Benedicht** [comment]
You can set the plugin's logging level to verbose by adding the following line somewehere in your startup code:
```cs
BestHTTP.HTTPManager.Logger.Level = BestHTTP.Logger.Loglevels.All;
```

Replicate your issue and send over all the produced log entries to me. You can reach me at besthttp@gmail.com too.
You can read more about logging here: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/Logging.html

**Comment by Benedicht** [comment]
@LongMarch7 Is there any update about your issue?
