### ISSUE TITLE
In Android Build, getting an issue: reasonCode: UnspecifiedError reasonMessage: mono-io-layer-error (110) 

### ISSUE THREAD

**Issue by kiranjavvajisc** [Benedicht/BestHTTP-Issues#121]
Hi, In the game I am getting this connection failed with the reasonCode: UnspecifiedError and reasonMessage: mono-io-layer-error (110).

Any issues in the usage OR bug ?

**Comment by Benedicht** [comment]
It's an error from the Android system. There's a mapping in mono between known error codes, but when the system returns with one that isn't recognised tis generic error message is thrown.

https://github.com/mono/mono/blob/main/mcs/class/System/ReferenceSources/Win32Exception.cs#L1739

It can be insufficient rights to open a network condition, or any other android specific issue.
