### ISSUE TITLE
Provide compiler define for UniTask library to replace use of Task

### ISSUE THREAD

**Issue by Soren025** [Benedicht/BestHTTP-Issues#126]
Library in question: https://github.com/Cysharp/UniTask

The main reason I suggest this is due to how native C# tasks continue to execute in the editor even after you exit play mode. The `UniTask` library implements tasks to run against the Unity update loop meaning tasks will be ignored once you exit play mode.

You can experience what I am referring to by executing a `HTTPRequest` using `WaitForResponseAsync` on an endpoint you know will take a few seconds and then exit play mode.

Or just run this in the editor...
```csharp
public class Test : MonoBehaviour
{
    private void Start()
    {
        Run();
        Application.Quit();
    }
    
    private async void Run()
    {
        await Task.Delay(5000);
        Debug.Log("Stuff happened outside play mode");
    }
}
```

**Comment by isaac-mcfadyen** [comment]
+1, this would be great especially since UniTasks are actually lighter than regular Tasks

**Comment by Benedicht** [comment]
Added to v3.
