### ISSUE TITLE
Issues with unexpected timeouts and connection closed unexpectedly

### ISSUE THREAD

**Issue by chris-yarbrough** [Benedicht/BestHTTP-Issues#127]
We're using HTTPRequest to send simple Post and Get requests to different backend systems. Recently, we noticed two errors surface as flaky tests on our build server but also on production servers.

1. Requests finish with ConnectionTimeOut or TimedOut although there's no apparent reason why the timeout would not be long enough (e.g. 60 seconds).
2. Requests finish with a generic error and the message "Connection closed unexpectedly" without any further information (no exceptions, no response body).

Both errors appear more frequently than an occasional network hiccup, but seemingly randomly. We have different systems with different requests to different endpoints, but the issue seems to affect all of them. As a test case I managed to reproduce the errors by running a test suite on multiple machines at the same firing many requests one after the other or by manually running individual test cases. Here are my observations:

- Running multiple machines with many requests sent increases the chance of seeing the errors.
- If one of the tests failed with "Connection closed unexpectedly", the same/equivalent request will continue to fail if I retry to send it again manually until I recompile the code.
- During certain times or after specific events, the issue happens very often (maybe 95% reliably in automated tests), but in other instances, the issue is hard to reproduce.
- Recompiling the code seems to "reset" a previous state in which many requests failed.
- Entering play mode (assembly reload) does not fix a previously failing request (if I try again, it still fails until recompile).
- Disabling caching or proxies does not prevent the errors.
- I can reproduce the errors with requests to third-party endpoints such as google.com
- **Disabling HTTP2 via the scripting define BESTHTTP_DISABLE_HTTP2 makes the errors unreproducible**

BestHTTP 2.7.0 (also tested in 2.6.2)
Unity 2020.3.36 (also tested in 2021.3.7)

I provided a testing project which tries to reproduce the errors in a simple and NDA-compatible way. The errors do happen for me locally in that project, but I'm afraid they are much harder to reproduce there than in the production setup, which I cannot share.

Please open the test project and see the contents of the "Assets/Docs" folder. Here I've documented several test runs with screenshots and also provided some error logs collected when tests were failing.

To reproduce the issue:

- See FlakyNetworkTests.cs
- Open the Unity test runner in the PlayMode tab and run all tests
- Run individually selected tests one by one
- Run a group of tests or all tests until the error is reproduced
- It might help to open a copy of the project in two different Unity versions and let all tests run at the same time

Sorry if the issue is difficult to reproduce on your end, we've spent multiple days on investigating the issues so far and are somewhat stuck and baffled.

Regarding the timeouts:
- In the tests it might seem as if only very low timeout values are failing and that we should simply increase them. However, the same request can also fail with very high timeout values (60 seconds). And, since the requests are very simple, they should practically never timeout.
- Setting the timeout values to -1 or 0 should disable timeout handling (as per documentation). Is it a bug that a request with a timeout of -1 can fail with a TimeOut exception? To my understanding, the request should wait indefinitely, but it seems like the default values are used instead.

Regarding the unexpected connection closing:
- This issue is the most important one, since it happens more often in the production environment.
- When this error showed, I also saw HTTP2HandlerException and ThreadAbortException (see the Docs folder).

Please advise, if you have any information or ideas how we can further investigate these issues. Since the errors do not reproduce with HTTP1, it may be an issue in the HTTP2 implementation, but so far we can't pinpoint anything. After running hundreds of test scenarios I have a feeling that the issue may also be connected to some sort of persistent state (e.g. connection pooling), because the issue never happens on the first test run after a clean start like after recompile or boot). How can I further narrow down the scenario or collect more information?

Thank you very much for your time and please let me know if I can in any way help beyond what I've provided here!

[FlakyNetworkTests.zip](https://github.com/Benedicht/BestHTTP-Issues/files/9718896/FlakyNetworkTests.zip)

**Comment by chris-yarbrough** [comment]
Thanks for looking into this! Here are two logs. The first contains detailed/verbose logging, the second is sadly only regular log level, because when I tried to reproduce the "closed unexpectedly" issue today with verbose logs, it didn't happen for a long time. Reducing the log level then produces the error on the first test run for me. Super strange!

[FlakyTests_01.log](https://github.com/Benedicht/BestHTTP-Issues/files/9733778/FlakyTests_01.log)
 In FlakyTets_01, search for
> Request failed with state

[FlakyTests_02.log](https://github.com/Benedicht/BestHTTP-Issues/files/9733779/FlakyTests_02.log)
In FlakyTests_02 search for
> Connection closed unexpectedly

**Comment by Benedicht** [comment]
@chris-yarbrough Could you drop me a mail at besthttp@gmail.com so i can send back a patched file. That should fix the timeouts when they are set to zero or lower.

**Comment by chris-yarbrough** [comment]
I’m afraid I haven’t managed to reproduce the error again until now. Also, I’m still trying to produce “connection closed unexpectedly” while the verbose logs are enabled, but the issue never happened with the logs enabled, only if I disable them. Very difficult to investigate, but I’ll try to keep an eye on the error while working on other things and hopefully I can catch something along the way. Will let you know if I have anything else.

From: Tivadar György Nagy ***@***.***>
Date: Tuesday, 11. October 2022 at 16:57
To: Benedicht/BestHTTP-Issues ***@***.***>
Cc: Christopher Yarbrough ***@***.***>, Mention ***@***.***>
Subject: Re: [Benedicht/BestHTTP-Issues] Issues with unexpected timeouts and connection closed unexpectedly (Issue #127)

Thanks, sent it. Could you replicate the exception in the HTTP2Handler and send a new Editor.log? I would like to see the context of that exception too.

**Comment by Benedicht** [comment]
The fix will be included in the next release.
