### ISSUE TITLE
Possible performance improvement of TLSSecurity.Setup() in editor

### ISSUE THREAD

**Issue by chris-yarbrough** [Benedicht/BestHTTP-Issues#129]
We're noticing some unusual slow performance of TLSSecurity.Setup() in the Unity Editor. Of course, the call is only in editor and is expected to be slow because of Database/File access, but we're sometimes seeing execution times from 2.5 to 8 seconds, which is extremely long and can hinder iteration time.

I did a quick profile and saw two chances for optimization.

1)
<img width="1934" alt="image" src="https://user-images.githubusercontent.com/111497457/197862143-3edc5b90-9f34-43b0-9d74-f14b572e48ba.png">

Within the method TLSSecurity.GetPluginFolder a call to Directory.GetDirectories is comparatively slow. Most likely because it's using the recursive option. Maybe searching via a different method or via Unity's AssetDatabase or with info from the CompilationPipeline could be faster. Alternatively, we would also be fine with setting the path in a configuration object if that avoids this searching routine. I also noticed that our 8s project is much larger (more directories and files) than the one with 2.5. It seems reasonable to assume that the recursive search is scaling poorly for larger projects in this case.

2)
<img width="783" alt="Screenshot 2022-10-24 at 14 32 38" src="https://user-images.githubusercontent.com/111497457/197862721-9dd98b0b-ad25-4123-828e-3434efe34372.png">

The method AVLTree.TestBalance takes a long time, but it seems to only be relevant for debugging, so it can removed or hidden behind a special compilation flag potentially. Also, this method is called multiple times (I saw at least three calls), although the result is always the same. The first result can most likely be cached for the session.

In my test, removing TestBalance and hardcoding the GetPluginFolder result was reducing the setup time from 2.5 seconds to 0.2 seconds. Maybe there are other bottlenecks in the Setup routine but the two mentioned methods seem like an easy gain.

Please consider optimizing, thank you! :)

**Comment by Benedicht** [comment]
Both will be fixed in the next update.
