### ISSUE TITLE
[WebSocket] OnError handling can double-log errors

### ISSUE THREAD

**Issue by discodonut** [Benedicht/BestHTTP-Issues#13]
This is maybe more of a suggestion, but when a WebSocket encounters an error, it will run this code:
```
if (OnError != null)
    OnError(this, reason);
if (OnError == null && OnError == null)  // this is odd
    HTTPManager.Logger.Error("WebSocket", reason);
```
My OnError callback logs the error, then unregisters all the callbacks and nulls out the socket.  However, because this code checks the callback again, it ends up logging the error twice, and it would be nice if it didn't do that.  Maybe the double null check should just be an `else`?

**Comment by Benedicht** [comment]
Good catch! There was an `OnErrorDesc` that got renamed to `OnError` too, this is why there's that strange `if` statement. Now it's going to be an `else` only.
