### ISSUE TITLE
Strip REST and leave only Sockets

### ISSUE THREAD

**Issue by VadymTykhoniuk** [Benedicht/BestHTTP-Issues#131]
Hi, we are building unity app, and size of it is quite important.
We decide to use UnityWebRequest for REST and only Sockets from BestHTTP2

Somehow stripping doesn't work very well and the whole implementation gets compiled.
Is there anyway to safely delete rest implementation? or like release "lite" version with only sockets in it?

**Comment by Benedicht** [comment]
The HTTP layer is required for all higher lever protocols (including socket.io too!). So, even with high stripping, code relating to HTTP will not be stripped. You can disable other protocols by using one or more [available defines](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/HowToDisableFeatures.html), but i wouldn't recommend to disable WebSocket as if possible Socket.IO will upgrade to the websocket transport from longpolling.
