### ISSUE TITLE
How to use websocket in non-main thread?

### ISSUE THREAD

**Issue by sknightq** [Benedicht/BestHTTP-Issues#132]
I'm using a websocket (V2.70) for recieving audio and transform data to drive model.
My framerate is 30 (33ms in on frame). But in **Profiler** I found the **HTTPUpdateDelegator.Update** cost about 50ms, which is result   in low framerate.
My model is updated in main thread (**Index.Update**). The framerate is OK.
So I want move the websocket to non-main thread. But I found the OnMessage Callback always be invoked in the main thread. I reviewed the source code. There is a thread mode reply on **Setup** function, but still not work. I tried to use
```BestHTTP.HTTPUpdateDelegator.Instance.SwapThreadingMode()``` and ```BestHTTP.HTTPUpdateDelegator.Instance.SetThreadingMode(ThreadingMode.Threaded)```.   
Still not work....

```
// In child thread function
  public void InitializeWS()
  {
    BestHTTP.HTTPManager.Logger.Level = BestHTTP.Logger.Loglevels.All;
    BestHTTP.HTTPManager.Setup(); // I set breakpoint in the source code but the thread mode isn't change
   // WSClient is wrapper of BestHttp websocket
    this.ws = new WSClient("ws://" + Index.wsURL + "/v2/ws/vh", (WebSocket ws, string message) =>
    {
      if (message.IndexOf("\"type\":\"audio\"") > 0)
      {
        ttsCB(ws, message); // still call in main function
      }
      else if (message.IndexOf("\"type\":\"ttf\"") > 0)
      {
        ttfaCB(ws, message); // still call in main function
      }
    });
   // log out in Not in Main Thread
    Debug.Log(mainThread.Equals(Thread.CurrentThread) ? "In Main Thread in WS" : "Not In Main Thread in WS");
  }
```
![image](https://user-images.githubusercontent.com/8033144/201600760-e85c3828-fea3-4bc4-b0ba-2ca78f441bb0.png)
![image](https://user-images.githubusercontent.com/8033144/201600785-ee186950-6e1d-477a-905f-e2e03dbff745.png)
Above  confuses me many days! Thanks for anyone can help me!

**Comment by Benedicht** [comment]
You should call only one of the `SwapThreadingMode`/`SetThreadingMode` methodes.
Also, you check whether it's on the main thread or not after creating `WSClient` and not from the callback.

**Comment by sknightq** [comment]
@Benedicht Thanks for your reply ! 
I just call the one of the ```SwapThreadingMode```/```SetThreadingMode``` methos when I tried. And my logs told me the `WSClient` created in non-main thread. 
My confuse is how to move the ```HTTPUpdateDelegator.Update``` to the other thread or how to decrease the cost time in ```HTTPUpdateDelegator.Update```.
My code structure is following :
```
void Start()
{
  BestHTTP.HTTPManager.Setup();
  wsThread = new Thread(this.InitializeWS);
  wsThread.Start();
}
void InitializeWS() 
{
  BestHTTP.HTTPUpdateDelegator.Instance.SwapThreadingMode();
  this.ws = new WSClient(url, onMessageCallback);
  // Print: Not In Main Thread in InitializeWS
  Debug.Log(mainThread.Equals(Thread.CurrentThread) ? "In Main Thread in WS" : "Not In Main Thread in InitializeWS");
}
```
```BestHTTP.HTTPUpdateDelegator.Instance.SwapThreadingMode()``` Should this line in main thread or not?

**Comment by Benedicht** [comment]
You don't have to create a new thread because it doesn't matter where you create the WebSocket instance/call `SwapThreadingMode`. 

It should be something like this:
```cs
void Start()
{
  BestHTTP.HTTPManager.Setup();
  BestHTTP.HTTPUpdateDelegator.Instance.SwapThreadingMode();
  this.ws = new WSClient(url, onMessageCallback);
}

// this should be called on a thread now
void onMessageCallback(WebSocket ws, string message)
{
  // ...
}
```

**Comment by sknightq** [comment]
I used the above code. But why the thread is changed back ? And the ```HTTPUpdateDelegator.Update``` still in the main thread.
![image](https://user-images.githubusercontent.com/8033144/201629373-0f01e921-6fc6-47bf-bdea-f2be623cb0cb.png)

**Comment by sknightq** [comment]
@Benedicht  I found a solution temporarily!
_First_, I **Add** ```BestHTTP.HTTPUpdateDelegator.Instance.SetThreadingMode(ThreadingMode.Threaded)``` in my main thread **Update** method and **Delete** the ```BestHTTP.HTTPUpdateDelegator.Instance.SwapThreadingMode()``` in **Start** method
_Second_, I found the problem line (line 232 in HTTPUpdateDelegator), but I don't know **why  the left value is always greater than 1**? Do I miss some configurations or not ?
I change the ```1``` to ```2 or 3``` temporarily，then the code works, the framerate is greater than 30 (less than 33ms/ per frame).
![image](https://user-images.githubusercontent.com/8033144/201637800-969aa7a7-21ba-4836-b8ab-ac6a7358b6af.png)
![image](https://user-images.githubusercontent.com/8033144/201641600-c1756131-011b-4ffd-b98e-6432b1138fb9.png)

My changes are litte funny. Waitting for your offical explaniation or support.

**Comment by Benedicht** [comment]
`updateThreadCount` is the number threads created. Increasing the number increases the allowed update threads running and calling `HTTPManager.OnUpdate();`.

**Comment by sknightq** [comment]
So I can change the code from ```1``` to ```2 or 3``` ?
 I think my way is not seriously. Maybe you can add a ```ThreadCount``` configuration in next realease.

**Comment by Benedicht** [comment]
I wouldn't think it would be necessary, as one thread is usually enough. 
What would be helpful is to know why you had to increase it. I tried but i couldn't replicate your issue.

**Comment by sknightq** [comment]
I‘m confused too，maybe I was using unity analysize or vscode unity debug tool. I will check it tomorrow.

**Comment by sknightq** [comment]
I change back the ```ThreadCount``` to ```1```. Everything still can work. I think my some debug operations make me wrong ```ThreadCount```. I will close this issues. 
@Benedicht Thank you for your code !!
