### ISSUE TITLE
TLS Security native crash on Android when Script Debugging is enabled

### ISSUE THREAD

**Issue by chris-yarbrough** [Benedicht/BestHTTP-Issues#133]
We’re observing crashes on Android devices when trying to attach a debugger while also using TLS Security. The resolved stack trace points to FastGcmBlockCipher_ProcessBytes and related methods in BestHTTP 2.7.0

To investigate and reproduce, please see the attached project:
[BestHTTPCrash_NoLibrary.zip](https://github.com/Benedicht/BestHTTP-Issues/files/10032375/BestHTTPCrash_NoLibrary.zip)

Important:
- IL2CPP with C++ compiler configuration ‘release’ (debug will not result in the crash)
- Development Build enabled
- Script Debugging enabled

For full stack trace see:
Doc/Crash_Symbolicated.txt

Full log with all log levels:
Doc/FullDeviceLog_LogLevelsAll.txt

Build log:
Doc/EditorBuildLog.txt

The sample code in MyScript.cs simply initializes TLSSecurity and sends a simple request. The request does not need to succeed for the problem to occur.

Also see the provided video to see the crash and logs happening in real time (optional):
Doc/ScreenRecording.mp4

To reproduce:
- Ensure correct build settings (also see Doc/BuildSettings.png for reference)
- Open the IDE, e.g. JetBrains Rider and ensure csproj files are generated
- Set two breakpoints in the MyScript file (no need to attach the debugger, maybe even unrelated)
- Build the provided project to an Android device (e.g. Galaxy S7 Edge)

After a few seconds, the app crashes. Observe the console output to find the stacktrace.
Potentially, use the Android Logcat Stacktrace Utility to symbolicate the stracktrace.
To produce the symbols, create a new build with the “generate symbols” build settings enabled.
Setup the symbol paths in the project settings for logcat to point to the IL2CPP development editor installation
and a second one to the generated (and unzipped) Symbols.zip file after the build was created.

If the app does not crash after more than 10 seconds, please try the following:
- Attach the debugger while the app is running, hit breakpoints and resume
- Enable WaitForManagedDebugger in build settings, on device click ok and wait

<img width="1672" alt="TLSSecurityCrash" src="https://user-images.githubusercontent.com/111497457/202471996-59de3387-989d-4c59-803e-da9058c5859f.png">

Thank you for your time! :)

**Comment by Benedicht** [comment]
As always, thanks for the detailed report!

What i could find is that that checking Script Debugging is adding a compile flag that creates a combination where a certain instruction fails under an arm processor.
Tested with the [latest version of the plugin](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/changelog.html#281-2022-11-16) and it worked without any issues with your setup.

**Comment by chris-yarbrough** [comment]
Thank you for looking into this! I can also confirm, my test project does not fail when I update to BestHttp 2.8.1! We can update, so we're in luck. :) 

Let's hope the issue does not return in different form, it looks pretty cryptic to fix. These failing instructions, are they something you can ensure will not fail in the future or is that issue possibly unrelated to the BestHttp implementation? Let me know if it's something that Unity should tackle, I have a support track where I could mention this. 

If there's nothing else to do, feel free to close the issue, as the update resolves our immediate issue!

**Comment by Benedicht** [comment]
It's because of the combination of Release build + Script Debugging.
That code is the default since years now and your report is the first one for this type of issue. I wouldn't think it will cause any problem outside of this combination, but even if will, the cipher implementation can be switched easily to a slower but more fail-safe one.
