### ISSUE TITLE
Feature request: JSON.NET on SocketIO3

### ISSUE THREAD

**Issue by isaac-mcfadyen** [Benedicht/BestHTTP-Issues#134]
Currently, Socket.IO 3/4 uses LitJSON as it's parser.

Because it doesn't accept `JsonConverter` or `JsonProperty` decorators like JSON.NET, you can't customize enum parsing/serialization and property naming conventions (for example, a lowercase JSON property deserialized into an uppercase struct field with `JsonProperty`).

I tried taking a look at writing a custom parser myself based on the JSON.NET parser from the SignalR example, however Socket.IO uses it's own message format and I couldn't easily swap them out.

A JSON.NET parser for SocketIO 3/4 would be very welcome 🙂

**Comment by Benedicht** [comment]
Try out this one: https://gist.github.com/Benedicht/d0d5e0c75e73d5e889ae8d68dde8f491

**Comment by isaac-mcfadyen** [comment]
Wonderful: thank you!

Is it possible to add this to the Parsers directory in the examples? Guessing this isn't an uncommon scenario.

**Comment by Benedicht** [comment]
Next release will include the parser.
