### ISSUE TITLE
[Socket.IO] Take long time to connect multi server

### ISSUE THREAD

**Issue by ducphamhong** [Benedicht/BestHTTP-Issues#135]
Hello 

I use BestHTTP (lasted v2.8.1)
It takes a long time to connect WebSocket Server and sometimes it time out (can't connect)

Can you help me fix it?
![Log](https://user-images.githubusercontent.com/57616039/202965783-b3bb4e44-34f9-4613-b26f-2f3214257c8c.png)

The bugs happen when I used more than 2 servers, It is still ok if I run on 1 server.
![MinInstance](https://user-images.githubusercontent.com/57616039/202965807-73261909-e60c-4236-95b9-0fcd959036ae.png)

The host server 
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/main/run/websockets

**Comment by ducphamhong** [comment]
Hello 
I open a connection with

```
SocketOptions options = new SocketOptions();
options.ConnectWith = BestHTTP.SocketIO3.Transports.TransportTypes.WebSocket;
```

It fixed.

**Comment by Benedicht** [comment]
Might be that with the initial long-polling transport, one request went to the first server and another request to the second one. See it in more detail here: https://socket.io/docs/v4/using-multiple-nodes/
