### ISSUE TITLE
Is BestHTTP compatible with the latest signalr client code?

### ISSUE THREAD

**Issue by bbehrens** [Benedicht/BestHTTP-Issues#136]
I'm asking specifically about the new dotnet 7 release of it.  https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client

**Comment by Benedicht** [comment]
I'm not sure about your question. Best HTTP/2 implements only the client side protocols, so i think the question should be more about compatibility with the server.
I'm sure the plugin is compatible with the recent release of Asp.net Core 7, and supports the recent addition of the SignalR Core protocol: [server callable client functions](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/protocols/signalr_core/HubConnection.html#server-callable-client-functions).
