### ISSUE TITLE
Threaded mode doesn't work when it is set before Setup is called

### ISSUE THREAD

**Issue by sergey-shapesxr** [Benedicht/BestHTTP-Issues#137]
Version of BestHTTP is 2.8.1.
STR:
Call `HTTPUpdateDelegator.Instance.CurrentThreadingMode = ThreadingMode.Threaded;` before the first `Update`, where `Setup` in `HTTPUpdateDelegator` is called.

Expected: Thread starts correctly and everything works as intended.
Actual: Thread doesn't start.

I'm sure it happens because of `SetThreadingMode` logic, that firstly checks for `isSetupCalled` and sets `_currentThreadingMode` to Threaded. And on the following call from `Setup` is ignored because threading mode didn't change.

**Comment by Benedicht** [comment]
Fixed in next release.
