### ISSUE TITLE
TLSSecurity.Setup() slow due to X509Name.ToString() and AVLTree.Add()

### ISSUE THREAD

**Issue by pak762** [Benedicht/BestHTTP-Issues#138]
Hello,

during profiling our game with Android Studio we noticed that the TLSSecurity.Setup() method takes relatively long to execute. Usually it is about 2 seconds for fast Android devices but this can also take up to 6 seconds for slower Android tablets for example and can even cause an ANR.

![TLSSecuritySetup](https://user-images.githubusercontent.com/6782881/206697164-2dd74ac5-81ab-462f-a46c-3522c625e3cc.PNG)

There are two main issues:

X509Name.ToString() now takes half of the overall time due to the comparison to sort it in the AVLTree. Previously the string was cached in cachedStrRepresentation but this does not seem to be the case anymore. I guess the reason for the removal was some issue that after X509Name got changed after cachedStrRepresentation was calculated once this was not updated? Is there a way to get this cache back and just dirty it when there is a change?

The other half is taken by AVLTree.Add() which each time sorts the whole tree. Is there any way to optimize this? Just out of interest, what exactly is the reason to use an AVLTree in this case?

For testing we removed the sorting in the the Add() function and put back the cachedStrRepresentation and the Setup() time went from 2 seconds to 0.3 seconds on my test device.

Would be awesome if this could be optimized, thank you :-)

**Comment by Benedicht** [comment]
AFAIK `X509Name`s are immutable so caching should be safe. Unfortunately, one of the BouncyCastle updates removed it that i wasn't aware, but will add it back in the next release.

An AVL tree is good for finding stored keys really fast, but with a price when doing insert/remove. If you remove the balancing call, it's just a plain binary search tree with slow queries. The slower queries might not be seen because they aren't done on Unity's main thread.
I have something in my mind to reduce rebalance calls.

**Comment by Benedicht** [comment]
> I have something in my mind to reduce rebalance calls.

What i thought is that it could save the DB optimized, loading the it the tree would be always balanced, so there wouldn't be any rebalance. It still have to call `RebalanceFrom`, but it got faster nonetheless.
In my tests it went from an avg. of *1.7* seconds to an avg. of *0.43* sec:

| before | caching in X509Names | caching + AVLTree opt. |
| --- | --- | --- |
| 1.7 sec | 0.568 | 0.432 | 

Additionally, moved the loading code to a thread so it will not block the main thread.

I still have a few smaller changes in mind that could help further speeding up loading, but these were the low hanging fruits.

**Comment by pak762** [comment]
Thank you very much for your response and detailed explanations.

These optimizations look awesome!

**Comment by Benedicht** [comment]
Two other improvements are:
1. Added a `StringBuilderPool` implementation to reuse StringBuilder instances. This change lowers memory pressure of the app and lowers the number of GC runs.
2. Switch from a recursive depth calculation to a pre-calculated one in the `AVLTree`. It has a really good early exit strategy to not trying to update nodes and theirs parents where it isn't necessary. `RebalanceFrom` calls are super fast now.

After these changes the average load time went down to 0.33 seconds. The remaining 99% of the time is sent in BouncyCastle's x509Name loading and in GC.

**Comment by Benedicht** [comment]
One more changed that i added but forgot about.
As one node can store more than one item, stored items are added to a list previously. However, this is a somehow rare case, majority of the nodes are storing only one item. Nodes now will use a struct implementation to allocate a List<> only when needed, further reducing GC allocations.
