### ISSUE TITLE
Unity 2021 compilation issue

### ISSUE THREAD

**Issue by sergey-shapesxr** [Benedicht/BestHTTP-Issues#140]
There are some compilation errors in Unity 2021. Interface IBlockCipher isn't fully implemented for classes AesFastEngine and NullEngine. Also, interface IRandomGenerator isn't implemented for class ReversedWindowGenerator. Methods with Span support are missing.

**Comment by Benedicht** [comment]
Because of removed files from the BouncyCastle implementation, upgrading to v2.8.x or newer might result in compile errors. To avoid or fix it remove the `\Best HTTP\` folder then import the plugin again.

**Comment by sergey-shapesxr** [comment]
Oh, I see now. Thank you very much!
