### ISSUE TITLE
Possible performance problem in HTTP2Handler.RunHandler() function

### ISSUE THREAD

**Issue by pak762** [Benedicht/BestHTTP-Issues#142]
Hello,

during performance profiling in Android Studio I found that sometimes the inner while loop **_(this.isRunning)_** in the **_RunHandler()_** function of the **_HTTP2Handler_** class does nothing except getting the **_DateTime now = DateTime.UtcNow;_** time without having any thread sleep in it using more or less one core each during a period of 10-20+ seconds. At some point this seems to go away and it is then using WaitOne().

![ThreadsNoSleepIssue](https://user-images.githubusercontent.com/6782881/207403502-7e610782-d11f-4cd7-ab08-88e6362c1980.PNG)

Is there any way this could be optimized or is there any specific reason that is causing this on our side?

**Comment by Benedicht** [comment]
As always, thanks for the report!
The fix will be included in the next release. If you think you can drop me a mail (besthttp@gmail.com) and I can send an updated package.
