### ISSUE TITLE
SecureRandom.cs NextBytes null pointer derefence

### ISSUE THREAD

**Issue by Syjgin** [Benedicht/BestHTTP-Issues#147]
Hi. We have a lot of events in Crashlytics, but, unfortunately, only with meaningless native stacktrace:

> Fatal Exception: Tombstone: Version '2021.3.12f1 (8af3c3e441b1)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'armeabi-v7a'
Build fingerprint: 'lge/dh0lm_e/dh0lm:10/QKQ1.200311.002/1658:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2023-01-11 09:23:20+0100
pid: 5013, tid: 14316, name: UnityMain  >>> com.our.app <<<
uid: 10261
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xba
Cause: null pointer dereference
    r0  00000000  r1  fffffff1  r2  ffffffff  r3  00000000
    r4  00000000  r5  00000000  r6  2000be11  r7  52808880
    r8  2000be21  r9  00000000  r10 00000000  r11 6f8f7c20
    ip  00000000  sp  354cbe18  lr  6cc05314  pc  6cb95090
    #00 pc 0x592090 libil2cpp.so 
    #01 pc 0x602310 libil2cpp.so 
    #02 pc 0x602b74 libil2cpp.so 
    #03 pc 0x6246d0 libil2cpp.so 
    #04 pc 0x62466c libil2cpp.so 
    #05 pc 0x86814c libil2cpp.so 
    #06 pc 0x867504 libil2cpp.so 
    #07 pc 0x867a84 libil2cpp.so 
    #08 pc 0x11bcc70 libil2cpp.so 
    #09 pc 0x11ba57c libil2cpp.so 
    #10 pc 0x1fe1f9c libil2cpp.so 
    #11 pc 0x1fcf6c4 libil2cpp.so 
    #12 pc 0x1fcf484 libil2cpp.so 
    #13 pc 0x1fe24b4 libil2cpp.so 
    #14 pc 0x1fe2300 libil2cpp.so 
    #15 pc 0x1fcf6c4 libil2cpp.so 
    #16 pc 0x1fcad9c libil2cpp.so 
    #17 pc 0x60ce30 libil2cpp.so 
    #18 pc 0x60cc8c libil2cpp.so 
    #19 pc 0x5835a8 libil2cpp.so 
    #20 pc 0x5d8c48 libil2cpp.so 
    #21 pc 0x5ad55c libil2cpp.so 
    #22 pc 0xaa8bb libc.so (__pthread_start(void*) + 20)
    #23 pc 0x61993 libc.so (__start_thread + 30)

Everything, that we know is Crashlytics for some reason classified, that error take place in the SecureRandom.cs, NextBytes method and this file is inside BestHttp module. Maybe, there are some related issue exists, but I was not able to find it.

**Comment by Syjgin** [comment]
looks like this was fixed in 2.8.3, will try it

**Comment by Benedicht** [comment]
@Syjgin I'm not sure about this. The error that v2.8.3(signal SIGBUS) fixes is different from the one you receive:
> signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xba
> Cause: **null pointer dereference**

The SecureRandom class in question is [this one](https://github.com/bcgit/bc-csharp/blob/master/crypto/src/security/SecureRandom.cs).

I can't see what could cause a *null pointer dereference* and why it would be different from 'regular' null-pointer exceptions.

Nonetheless, it might worth to try it out with v2.8.3.
