### ISSUE TITLE
Blocking BufferedReadNetworkStream.Read causes ANRs

### ISSUE THREAD

**Issue by Eike-Decker** [Benedicht/BestHTTP-Issues#148]
We see rare but significant ANRs that can be traced to this callstack:

```
HTTPUpdateDelegator.Update()
HTTPUpdateDelegator.CallOnUpdate()
HTTPManager.OnUpdate()
RequestEventHelper.ProcessQueue()
HostDefinition.Send(HTTPRequest request)
HostConnection.Send(HTTPRequest request)
HostConnection.GetNextAvailable(HTTPRequest request)
HTTPConnection.TestConnection()
TlsProtocol.TestApplicationData()
TlsProtocol.SafeReadRecord()
RecordStream.ReadRecord()
BufferedReadNetworkStream.Read(byte[] buffer, int offset, int count)
ReadOnlyBufferedStream.Read(byte[] buffer, int offset, int size)
```

Devices lock up for 10+s on that call since we execute the http connection on the main thread. I am unsure if this is an implementation fault on our end or if this is something that BestHTTP needs to handle gracefully.

**Comment by Benedicht** [comment]
What version of the plugin do you use? (You can check `HTTPManager.UserAgent`.)

**Comment by Eike-Decker** [comment]
Sorry I forgot about this: `BestHTTP/2 v2.8.2`

**Comment by Benedicht** [comment]
How widespread is this issue? I think a block in that code could occur only when the client receives only part of a TLS frame.

**Comment by Eike-Decker** [comment]
Difficult to say. Here's our situation: Our Application ANR rate on Android is ~0.4% for most devices but for the Redmi Note 10 it's 15% (yes, FIFTEEN %). I am reviewing data from a propietary stacktrace sampling tool and to my surprise, 20% of the samples (6 of 26) that came from the Redmi 10 pointed to this particular problem. I was aware of this issue in December, but it seemed to make up only 1-2% of the collected ANR samples. I don't know why this should only affect the Redmi devices this severly - I only have the slight suspicion that when the app goes into the background, the OS running on the Redmi phones may severe the running connections or something. That's currently my only explanation why this error seems to be so prevalent on these devices.

Another point why this ANR issue we see may be connected to this particular problem is that we suffer from these increased ANRs since last year when we updated our network handling to add TLSSecurity to verify certificates on mobile devices.

**Comment by Benedicht** [comment]
Thanks for the additional information! 
I can offer a quick workaround by commenting out the `TestConnection` call in HostConnection.cs. It doesn't have any drawback other than detecting broken connections with a slight delay.
A proper fix will require more work by transition from blocking reads/writes to asynchronous ones.

**Comment by Eike-Decker** [comment]
We can test this to see if it has an effect. Could very well be that it doesn't make much of a difference. Getting a result from this may however take 1-2 weeks - if we'd roll it out early this week.

**Comment by Eike-Decker** [comment]
Small update: We employed the suggested code change but we don't see a significant reduction in ANRs, so while this is the cause of some ANRs, it doesn't seem to be too much in the big picture. So it should be fixed but it is not that pressing it seems.

**Comment by Benedicht** [comment]
Fixed it in the next big release (v3).
