### ISSUE TITLE
Missing internal assembly with Mono on Android

### ISSUE THREAD

**Issue by GabrielePicco** [Benedicht/BestHTTP-Issues#152]
When using Mono build on Android, with Unity version 2021.3.19f1, I get the following issue with all the requests I try:

```
{"tid":5,"div":"HTTP2Stream","msg":"FinishRequest","ex": [{"msg": "__Internal assembly:<unknown assembly> type:<unknown type> member:(null)", "stack": "  at (wrapper managed-to-native) Interop+Brotli.BrotliDecoderCreateInstance(intptr,intptr,intptr)\n  at System.IO.Compression.BrotliDecoder.InitializeDecoder () [0x00000] in <b649bc9e881c4625925be87d6ef9b61d>:0 \n  at System.IO.Compression.BrotliDecoder.EnsureInitialized () [0x0000e] in <b649bc9e881c4625925be87d6ef9b61d>:0 \n  at System.IO.Compression.BrotliDecoder.Decompress (System.ReadOnlySpan`1[T] source, System.Span`1[T] destination, System.Int32& bytesConsumed, System.Int32& bytesWritten) [0x00000] in <b649bc9e881c4625925be87d6ef9b61d>:0 \n  at System.IO.Compression.BrotliStream.Read (System.Span`1[T] buffer) [0x00102] in <b649bc9e881c4625925be87d6ef9b61d>:0 \n  at System.IO.Compression.BrotliStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00011] in <b649bc9e881c4625925be87d6ef9b61d>:0 \n  at BestHTTP.Connections.HTTP2.HTTP   I  
```

The package works fine on editor and IOS tough, also works on Android if I use IL2CPP. Because of some other requirements, we need mono compilation working as well.

An example of request:

```
         HTTPRequest request = new HTTPRequest(
                 new Uri("https://serverless.garbles.fun/api/v1/game/generate-mint-item-tx/"), 
             HTTPMethods.Post, async (HTTPRequest request, HTTPResponse response) =>
             {
                 Debug.Log(response.DataAsText);
             });
        
         var body = JsonConvert.SerializeObject(new
         {
             public_key = "GcfUM5hCMYVe6Mpj6En2crkY1NxKLAYCK8Pc4Cv9Yp3c",
             latitude = 0,
             longitude = 0,
             id = "steak",
             cluster = "devnet"
         });
         Debug.Log("Body: " + body);
         request.RawData = System.Text.Encoding.UTF8.GetBytes(body);
         request.AddHeader("Content-Type", "application/json");
         request.Send();
```

**Comment by Benedicht** [comment]
What version of the plugin are you using (you can print out `HTTPManager.UserAgent`, or just check its value in the source)?

**Comment by GabrielePicco** [comment]
Thanks for the fast reply @Benedicht . I'm using the latest: BestHTTP/2 v2.8.3

**Comment by Benedicht** [comment]
Hmm, that's intersting. v2.8.3 shouldn't request brtoli compressed content under Android when using mono.

As a quick workaround you can add the following line to set up your requests:
`request.AddHeader("Accept-Encoding", "gzip, identity");`

**Comment by GabrielePicco** [comment]
Thanks, adding the header circumvent the brtoli issue

**Comment by Benedicht** [comment]
Due to a lot of issues by Unity not including the native libaries needed by [BrotliStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.brotlistream), starting with v2.8.4 it will be enabled only when the BESTHTTP_ENABLE_BROTLI define is used.

**Comment by vadim-marchuk** [comment]
> Hmm, that's intersting. v2.8.3 shouldn't request brtoli compressed content under Android when using mono.
> 
> As a quick workaround you can add the following line to set up your requests: `request.AddHeader("Accept-Encoding", "gzip, identity");`

Hi there. I have encountered the same issue. While the workaround works, I also noticed the preprocessor directives responsible for not using Brotli on Android Mono, and they look incorrect. Can you please look at the arguments below and give your thoughts?

#if (NET_STANDARD_2_1 || UNITY_2021_2_OR_NEWER) && (!(ENABLE_MONO && UNITY_ANDROID) || (!UNITY_WEBGL || UNITY_EDITOR))

The second part of this can be rewritten in the next format.
!(ENABLE_MONO && UNITY_ANDROID) || !UNITY_WEBGL || UNITY_EDITOR

And on the Android Mono build, this expression will give
false || true || false = true
while the expected result is false.

If Brotli is allowed in UnityEditor and on any platform except WebGL and MonoAndroid, then the expression should be
UNITY_EDITOR || (!UNITY_WEBGL && !(ENABLE_MONO && UNITY_ANDROID))
