### ISSUE TITLE
Socket.IO socket.OnAny(HandleSocketEvent);

### ISSUE THREAD

**Issue by MindScriptAct** [Benedicht/BestHTTP-Issues#153]
Hello, 

 I need ability to handle all incoming messages with one function. (To be able to debug messages that are not yet handled by client.)
 
 I noticed you have SocketIOEventTypes.Event but I fail to find documentation how to use it. In fact, none of these are properly documented : SocketIOEventTypes.Event, SocketIOEventTypes.Ack,SocketIOEventTypes.BinaryAck, SocketIOEventTypes.BinaryEvent, SocketIOEventTypes.Disconnect, SocketIOEventTypes.Unknown.
 
 Is it posible to get OnAny functionality?
 or if its covered by SocketIOEventTypes.Event, please give example. (or even better - add it to your documentation.)
 
 Thank you for your time!
  And thanks for building great tool.

**Comment by Benedicht** [comment]
Most of the `SocketIOEventTypes` are used only internally and doesn't forwarded (the only exception are Connect and Disconnect). While i don't plan to add support for the remaining ones, i can add an `OnPacket` event to the `SocketManager` that's called for every packet received from the server.

If you drop me a mail to besthttp@gmail.com, i can send back a mail to a new pacakage with the new OnPacket event.
