### ISSUE TITLE
Websocket reserved header bits not set for fragmented messages

### ISSUE THREAD

**Issue by jeremyouellette** [Benedicht/BestHTTP-Issues#154]
In BestHTTP 2.8.3, the reserved header bits are not being correctly set when websocket messages are fragmented.  The following patch to WebSocketFrame.cs addresses the issue:

        private void FragmentAndSend(Action<BufferSegment, BufferSegment> callback, uint maxFragmentSize, bool mask, LoggingContext context)
        {
            int pos = this.Data.Offset;
            int endPos = this.Data.Offset + this.Data.Count;

            while (pos < endPos)
            {
                int chunkLength = Math.Min((int)maxFragmentSize, endPos - pos);
                bool isInitial = pos == this.Data.Offset;
                bool isFinal = pos + chunkLength >= this.Data.Count;

                WriteFragment(callback: callback,
                    Type: isInitial ? this.Type : WebSocketFrameTypes.Continuation,
                    IsInitial: isInitial,
                    IsFinal: isFinal,
                    Data: this.Data.Slice((int)pos, (int)chunkLength),
                    mask: mask,
                    context: context);

                pos += chunkLength;
            }
        }

        private void WriteFragment(Action<BufferSegment, BufferSegment> callback, WebSocketFrameTypes Type, bool IsInitial, bool IsFinal, BufferSegment Data, bool mask, LoggingContext context)
        {
            // First byte: Final Bit + Rsv flags + OpCode
            byte finalBit = (byte)(IsFinal ? 0x80 : 0x0);
            byte reservedBits = (byte)(IsInitial ? this.Header & 0x70 : 0x0);
            byte Header = (byte)(finalBit | reservedBits | (byte)Type);

            WriteFragment(callback, Type, Header, Data, mask, context);
        }

**Comment by Benedicht** [comment]
Thanks for the report and the code. I still have to investigate this, but your header byte computation doesn't look good.

**Comment by jeremyouellette** [comment]
For context, the specific issue we hit was sending a large message over a websocket which had negotiated gzip compression, the server received the initial frame without RSV1 set and failed (obviously) parsing the compressed data.  The header byte computation here is just preserving the values of RSV1-RSV3 that were initially set in the pre-fragmentation frame header and ensuring that they're correctly set in the initial fragmented frame per the protocol spec.

**Comment by Benedicht** [comment]
Reworked header and fragmentation handling a little. In the next version header bits should be set correctly.
