### ISSUE TITLE
EventSource  interrupt！

### ISSUE THREAD

**Issue by cpj123456** [Benedicht/BestHTTP-Issues#155]
Hi,Take a look at the picture.
Log:"Request Finished Successfully, but the server sent an error. Status Code: 200-OK Message: ".

I'm not sure if it's due to the server or if EventSource needs to set certain parameters. 
What's the problem?
Thank you!

![20230413005459](https://user-images.githubusercontent.com/16045764/231528474-7dc7d641-714e-4c4a-a3a8-b8cf056cea7a.png)

**Comment by Benedicht** [comment]
Could you add the following line somewhere in your startup code, replicate the error and send over all the produced log lines to me (here, on [discord](https://discord.gg/yD9tXwQ) or over [email](mailto:besthttp@gmail.com)):
```cs
BestHTTP.HTTPManager.Logger.Level = BestHTTP.Logger.Loglevels.All;
```

You can read more about logging in the plugin here: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/Logging.html

I think the server is sending a chunk that means it's the *end of content*, but the logs might help know more.

**Comment by Benedicht** [comment]
Could you create a minimal repro project and send it over?
