### ISSUE TITLE
litJson fails to serialize enums. 

### ISSUE THREAD

**Issue by MindScriptAct** [Benedicht/BestHTTP-Issues#157]
Hi, 

 Then I emit data that contains enums (using BestHTTP.SocketIO3;) -> code crashes. 
 
 both 
Newtonsoft.Json.JsonConvert.SerializeObject(data); 
 and 
MongoDB.Bson;       data.ToJson();  
works fine.
 
 Thank you for your time.
 
I hacked Newtonsoft.Json.JsonConvert.SerializeObject(args);  into Socket.cs line 58 to make it work.

**Comment by MindScriptAct** [comment]
hm.. nothing fancy.. just enum : 
`
namespace prjName.Shared.Constants
{
    public enum MapInteractionType
    {
        None = 0,
        Teleport = 1,
        TimedTeleport = 2,
    }
}
`

**Comment by Benedicht** [comment]
Just tried out but it worked on my end. Could you share any error message or additional information that might help?
