### ISSUE TITLE
 If  do not operate the app for a period of time， the first requeset will fail

### ISSUE THREAD

**Issue by Dejavu0709** [Benedicht/BestHTTP-Issues#159]
If  do not operate the app for a period of time， the first requeset will fail，the request did not send to the server successfully，is there some params to solve this？

**Comment by Benedicht** [comment]
It can happen with connections kept alive. It's a mayor performance boost came with HTTP/1.1, however, clients can test a tcp connection only by sending something, and with HTTP/1.1 that's a new request. So, currently, there are only a few ways to proceed:
1.) You can try set a lower [MaxConnectionIdleTime](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/GlobalSettings.html#maxconnectionidletime). If you aren't sending the new request in the same frame the application is coming back from the background state, the connection can reach its idle time and closes.
2.) You can disable keep-alive by setting [KeepAliveDefaultValue](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/GlobalSettings.html#keepalivedefaultvalue) to false: `HTTPManager.KeepAliveDefaultValue = false;`
3.) Use HTTP/2. It has control frames to do ping-pong mechanism. Detecting a broken connection still takes time, requests sent during this time window still will fail however.
