### ISSUE TITLE
No callbacks are sent in editor mode after play mode

### ISSUE THREAD

**Issue by Benedicht** [Benedicht/BestHTTP-Issues#16]
The plugin shuts down on `OnApplicationQuit` or `OnDisable`, after these events no callbacks are called for requests sent in editor mode.

**Comment by janbc** [comment]
i have the same issue,

**Comment by legoritma** [comment]
@Benedicht Is there any release date for this?

**Comment by Benedicht** [comment]
@legoritma I hope it's going to be out in one or two weeks. But you can drop me a mail any time and i can send an updated package.
