### ISSUE TITLE
[SignalR Core] Exception on removing subscription during reconnection

### ISSUE THREAD

**Issue by Scormave** [Benedicht/BestHTTP-Issues#161]
There is an exception, that is fired from method **Remove** in **HubConnection** if it is in states **Closed** or **CloseInitiated**.
It sounds logical on the first glance, because you can't operate with **HubConnection** in these states. But, I catch this exception on reconnection during small time interval between **Connected** and **Reconnecting** states, when there is a **Closed** state (I use Threaded mode, so it's pretty easy).
So, my question is - why do exceptions needed in methods **On** and **Remove** since subscriptions use ConcurrentQueue and this queue isn't even cleared by **HubConnection** on closing?

**Comment by Benedicht** [comment]
You are right, it's pointless to throw exceptions there. In the next release they will be removed.
