### ISSUE TITLE
iOS il2cpp link error

### ISSUE THREAD

**Issue by duanrui71** [Benedicht/BestHTTP-Issues#163]
when i upgrade besthttp to 2.5.4 to 2.8.3. I got an il2cpp link error;
![image](https://github.com/Benedicht/BestHTTP-Issues/assets/20023122/ff8b22d2-86ce-424b-81f7-a8e2092ab24b)

Can someone help?

**Comment by Benedicht** [comment]
What version of Unity are you using?

**Comment by duanrui71** [comment]
2021.3.20f1

**Comment by Benedicht** [comment]
Could you drop me a mail to besthttp@gmail.com, i will send back a link to a new package.

**Comment by Benedicht** [comment]
Due to a lot of issues by Unity not including the native libaries needed by [BrotliStream](https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.brotlistream), starting with v2.8.4 it will be enabled only when the BESTHTTP_ENABLE_BROTLI define is used.
