### ISSUE TITLE
GO_AWAY and Server closing the connection due MaxConcurrentStreams

### ISSUE THREAD

**Issue by MunteanuAndreiStefan** [Benedicht/BestHTTP-Issues#165]
ValueOrError`1:Error occured on loading ImageMeta entities from the collection 'XXX', url: https://XXX/api/meta/collections/XXX-YYY-ZZZ-
Error: Server closing the connection! Error code: NO_ERR...;

When I have more than 10 MaxConcurrentStreams and try to download 1000+ files, I get GO_AWAY.

Is there a mechanism to retry it from where it failed? Should I manually setup something before start making the requests?
I've tested with HTTP/1.1 it works all right with 20 max connections. Any idea/direction?

**Comment by Benedicht** [comment]
In case of HTTP/2, the requests are put into the HTTP/2 handler's queue and the timer starts ticking. However, the HTTP/2 has its own max concurrent stream and number of requests to handle through the connection's lifetime. 
With HTTP/2 you can orgenize a custom queue on top of the plugin. I'm also going to fix it in the next big release.
