### ISSUE TITLE
Error in JsonDotNetParser when serializing ack

### ISSUE THREAD

**Issue by davide-aldegheri** [Benedicht/BestHTTP-Issues#166]
Hi there, it's me again!

I've found an issue using the JsonDotNetParser.
Specifically the issue is when using the EmitAck event in a WebSocket environment. I've looked through your code and found that it should lie here:

```csharp
case SocketIOEventTypes.Ack:
                case SocketIOEventTypes.BinaryAck:
                    if (nspAdded) builder.Append(',');

                    if (args != null && args.Length > 0)
                    {
                        builder.Append(JsonConvert.SerializeObject(args[0], this._settings));
                    }
                    else
                        builder.Append("[]");
```
At line 507 you are serializing only the first item of the args array, this produces a json object in the emitted package that gets refused by the server. I've tried removing indexing the array and it correctly produces a json array which works fine.

```chsarp
builder.Append(JsonConvert.SerializeObject(args, this._settings));
```

**Comment by Benedicht** [comment]
Thanks for the report and investigation!
