### ISSUE TITLE
Problems encountered when using WebSocket and EventSource

### ISSUE THREAD

**Issue by turboboostcat** [Benedicht/BestHTTP-Issues#168]
Problems encountered when using WebSocket and EventSource

**WebSocket**：
When I open the websocket and send the first message immediately, an error is reported immediately, and then it is normal. Attach sample code and error message:
```
socket = new WebSocket(new Uri(address));
socket.OnOpen += OnOpen;
socket.OnBinary += OnBinary;
socket.OnMessage += OnMessage;
socket.OnClosed += OnClose;
socket.OnError += OnError;
AddLog("Connecting...");
socket.Open();
```
`Error: Request Finished with Error! Exception: TCP Stream closed unexpectedly by the remote server  at BestHTTP.WebSocket.Frames.WebSocketFrameReader.ReadByte (System.IO.Stream stream) [0x00010] in E:\Unity\Project\Assets\Best HTTP\Source\WebSocket\Frames\WebSocketFrameReader.cs:131 `

**EventSource**：
When I have not finished receiving a message, an error will be reported, and then I will not receive the rest of the message:
```
EventSource eventSource = new EventSource(new Uri(address));
eventSource.InternalRequest.MethodType = HTTPMethods.Post;
eventSource.InternalRequest.SetHeader("client-id", m_client_id);
eventSource.InternalRequest.SetHeader("Content-Type", "application/json");
eventSource.InternalRequest.RawData = Encoding.UTF8.GetBytes(JsonUtility.ToJson(data));
eventSource.OnOpen += (source) => { LogHelper.Log("OnOpen"); };
eventSource.OnClosed += (source) => { LogHelper.Log("OnClosed"); };
eventSource.OnError += (source, error) => { LogHelper.Log("OnError:"+error); };
eventSource.OnStateChanged += (source, oldState, newState) => { LogHelper.LogFormat("OnStateChanged:{0},{1}", oldState, newState); };
eventSource.OnMessage += (source, message) => { LogHelper.Log("OnMessage:" + message); };
eventSource.Open();
```
```
OnMessage:"": "{"code":0,"msg":null,"response":"。","status":"running"}"
OnError:No Content-Type header with value 'text/event-stream' present.
OnStateChanged:Open,Closed
OnClosed
```

**I have enabled the log level and saved besthttp.log, the file has been sent to your email, please check it.**
**File List:**
1. besthttp eventsource.log
2. besthttp websocket.log

`HTTPManager.Logger.Level = BestHTTP.Logger.Loglevels.All;`

**Comment by turboboostcat** [comment]
I hope you can spare your precious time to help analyze how to solve these problems.
Thank you very much, best wishes.

**Comment by Benedicht** [comment]
Sent a new EventSource.cs in mail.

**Comment by turboboostcat** [comment]
> 

thanks，boss！I love u very very much!
