### ISSUE TITLE
How to use BestHTTP/2 with android?

### ISSUE THREAD

**Issue by Linkersem** [Benedicht/BestHTTP-Issues#170]
I have download the BestHTTP/2 (version 2.8.1)and import the package to my project , I do not konw how to use it and make it work on my Android phone? 
I also read document in "https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/platforms.html",but i am confused with this. can you give some steps to explain how to use BestHTTP/2 with Android?

**Comment by Benedicht** [comment]
Hmm, where did you downloaded v2.8.1? The latest version in the store is v2.8.3.

>  do not konw how to use it and make it work on my Android phone?

The plugin doesn't require any setup. Also, usage depends on what protocol do you want to use: http, socket.io, signalr core?

For http, you can find a few quick examples here: [Small Code Samples](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/protocols/http/SmallCode-Samples.html)
