### ISSUE TITLE
Complains about `ProxyFinder` class not found on Android

### ISSUE THREAD

**Issue by DomDerrien** [Benedicht/BestHTTP-Issues#172]
Probably a safe message b/c the application is working, but an annoying one as it triggered after each request launch...

> 10-05 15:41:20.965 10216 10734 E Unity   : {"tid":1,"div":"AndroidProxyDetector","msg":"GetProxy","ex": [{"msg": "java.lang.ClassNotFoundException: com.besthttp.proxy.ProxyFinder", "stack": "java.lang.ClassNotFoundException: com.besthttp.proxy.ProxyFinder\n\tat java.lang.Class.classForName(Native Method)\n\tat java.lang.Class.forName(Class.java:454)\n\tat com.unity3d.player.UnityPlayer.nativeRender(Native Method)\n\tat com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)\n\tat com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)\n\tat android.os.Handler.dispatchMessage(Handler.java:102)\n\tat android.os.Looper.loopOnce(Looper.java:201)\n\tat android.os.Looper.loop(Looper.java:288)\n\tat com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)\nCaused by: java.lang.ClassNotFoundException: com.besthttp.proxy.ProxyFinder\n\t... 9 more\n  at UnityEngine.AndroidJNISafe.CheckException () [0x00000] in <00000000000000000000000000000000>:0 \n  at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x00000] in <000000000000000000000

**Comment by Benedicht** [comment]
For a very quick fix, you can disable proxy detection by adding the following line somewhere in your startup code:
`HTTPManager.ProxyDetector = null;`

However, it would be good to know *why* can't be found. Could you confirm that you have `ProxyFinder.java` in the `Best HTTP\Plugins\Android\` folder?

**Comment by Benedicht** [comment]
Found out both the cause of the issue and its fix: https://bestdocshub.pages.dev/Shared/proxy/proxy-autodetect/#issues-with-minify
