### ISSUE TITLE
How to trigger a cache flush?

### ISSUE THREAD

**Issue by DomDerrien** [Benedicht/BestHTTP-Issues#173]
I use Best HTTP/2 caching capabilities a lot because data received from our remote service are good for 24 hours or more.

Is there a way to trigger the cache flush? I want to offer in the app settings to help users debug issues more efficiently.

Thanks

**Comment by Benedicht** [comment]
You can use `BestHTTP.Caching.HTTPCacheService` static class' `BeginClear` to clear and `BeginMaintainence` to run a general maintainence on the cache.

With `BeginClear` you can delete all cached entities.
By calling `BeginMaintainence` you have to pass an `HTTPCacheMaintananceParams` object that you can use to delete old entries[1] and set a limit on the cache's size.
You can call `BeginMaintainence` on application startup.

---
For v3 there will be a new local cache implementation where a limit can be set to the cache, and it will use it to automatically evict old entries[1] and keep the cache's size under the limit.

---

[1] In both cases, *old* means when it was last accessed, not when it was placed in the cache.

**Comment by DomDerrien** [comment]
Thanks for the tip.
I'm going to give it a try soon.
Have a nice weekend ;)
