### ISSUE TITLE
can i get cache content by one url ?

### ISSUE THREAD

**Issue by phzzy** [Benedicht/BestHTTP-Issues#178]
How can I directly trigger a response callback when I request a server image and the cache exists, instead of requesting the server again and waiting for the server to return 304 before triggering the callback?

i use **HTTPCacheService.GetEntity(uri)** , and then how to trigger reponse callback?

**Comment by Benedicht** [comment]
The plugin's http cache respects the server's caching policy it communicates through headers. In your case, the server tells the client that it has to re-validate the content's freshness every time.
If you have access to the server to change caching headers, i would recommend to use a `Cache-Control` header with a `max-age` directive.
If you don't have access to the server, you can use `GetBodyStream` of the `HTTPCacheFileInfo` returned by `HTTPCacheService.GetEntity` to access the stored resource.
