### ISSUE TITLE
HTTPRequest question

### ISSUE THREAD

**Issue by Scormave** [Benedicht/BestHTTP-Issues#179]
Hello!
I wanted to use HTTP requests functionality from BestHTTP, but noticed that for some reason every sent web-request spawns a new thread for it, using ThreadedRunner.RunLongLiving method. Is there a reason for this? It becomes really hard to profile an application for example, there are too much short living threads. In my understanding, there should be ThreadedRunner.RunShortLiving call.
Even in case of long-running requests, ThreadPool can determine if there is a thread starvation and spawn new threads.

**Comment by Benedicht** [comment]
I thought about it too, however, the plugin doesn't know wheter the request will be short or long living. It might upgrade to a HTTP/2 connection that can be alive for minutes, or a websocket one for hours... 
It could use some kind of heuristic however to better utilize background (short living) threads.

**Comment by Scormave** [comment]
Can I suggest a possible solution? At least for HTTP1 - you can override `Process` method of `HTTP1Handler` and see if this request doesn't contain something to upload or download, and in this case I think it is possible to use `RunShortLiving`.

**Comment by Benedicht** [comment]
Added it to the v3 branch. It already has a better threading modell, downloads doesn't occupy a thread until receives the whole response. My current addition to this is that when the request is a simple HTTP/1 GET request without an upgrade header, it's going to use the thread pool, instead of creating a new thread.
