### ISSUE TITLE
HTTPRequest failing every other request with Python's http.server

### ISSUE THREAD

**Issue by AlejandroHuerta** [Benedicht/BestHTTP-Issues#180]
I'm running into a strange issue I haven't been able to explain. I'm running a small python web server using http.server. Here's a stripped-down version of it.

```
from http.server import HTTPServer, BaseHTTPRequestHandler
import json

HOST = "localhost"
PORT = 4001

class RequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        print('Received request ' + self.path)
                  
        data = {"data": [{ "Name": "camera1", "Index": 1, "Provider": "provider1", "IsDirectDriver": True, "IsSelected": False }]}
        response = json.dumps(data)
        
        self.respond(200, "application/json", response.encode())
        
    def respond(self, code, content_type, data):
        self.send_response(code)
        self.send_header("Content-Type", content_type)
        self.end_headers()
        self.wfile.write(data)
        self.close_connection = True

try:
    httpd = HTTPServer((HOST, PORT), RequestHandler)
    httpd.serve_forever()
except BaseException as error:
    print('An exception occurred: {}'.format(error))

```

When I do a GET from BestHTTP2 such as
```
UniTask<ServerReply> Get(string url) {
          Debug.Log($"Making GET request to {url}");

          UniTaskCompletionSource<ServerReply> taskCompletionSource = new();

          var request = new HTTPRequest(new Uri(url), HandleResponses(taskCompletionSource));
          request.MethodType = HTTPMethods.Get;
          request.Send();

          return taskCompletionSource.Task;
 }
```
I get an error every other request of it that looks like this

> {"tid":323,"div":"HTTPResponse","msg":"Failed to read Status Line! Retry is disabled, re-throwing exception.","stack":"  at HTTPResponse.Receive (System.Int64 forceReadRawContentLength, System.Boolean readPayloadData, System.Boolean sendUpgradedEvent) [0x000d2] in C:\\Users\\sangh\\OneDrive\\Documents\\Source\\SharpCapConsole\\Client\\Assets\\Best HTTP\\Source\\HTTPResponse.cs:257 \r  at Connections.HTTP1Handler.Receive (HTTPRequest request) [0x0007d] in C:\\Users\\sangh\\OneDrive\\Documents\\Source\\SharpCapConsole\\Client\\Assets\\Best HTTP\\Source\\Connections\\HTTP1Handler.cs:230 \r  at Connections.HTTP1Handler.RunHandler () [0x0014a] in C:\\Users\\sangh\\OneDrive\\Documents\\Source\\SharpCapConsole\\Client\\Assets\\Best HTTP\\Source\\Connections\\HTTP1Handler.cs:70 \r  at Connections.HTTPConnection.ThreadFunc () [0x002ac] in C:\\Users\\sangh\\OneDrive\\Documents\\Source\\SharpCapConsole\\Client\\Assets\\Best HTTP\\Source\\Connections\\HTTPConnection.cs:196 \r  at PlatformSupport.Threading.ThreadedRunner+<>c__DisplayClass6_0.<RunLongLiving>b__0 (System.Object param) [0x00000] in C:\\Users\\sangh\\OneDrive\\Documents\\Source\\SharpCapConsole\\Client\\Assets\\Best HTTP\\Source\\PlatformSupport\\Threading\\ThreadedRunner.cs:111 \r  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00000] in <b89873cb176e44a995a4781c7487d410>:0 \r  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <b89873cb176e44a995a4781c7487d410>:0 \r  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <b89873cb176e44a995a4781c7487d410>:0 \r  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <b89873cb176e44a995a4781c7487d410>:0 \r  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x00000] in <b89873cb176e44a995a4781c7487d410>:0 ","ctxs":[{"TypeName": "HTTPResponse", "Hash": 6054851162689945599, "BaseRequest": 736410768, "IsStreamed": false, "IsFromCache": false},{"TypeName": "HTTPRequest", "Hash": -104859479703553}],"t":638352459828452940,"ll":"Warning","bh":1}
UnityEngine.Debug:LogWarning (object)
BestHTTP.Logger.UnityOutput:Write (BestHTTP.Logger.Loglevels,string) (at Assets/Best HTTP/Source/Logger/UnityOutput.cs:17)
BestHTTP.Logger.ThreadedLogger:ThreadFunc () (at Assets/Best HTTP/Source/Logger/ThreadedLogger.cs:148)
BestHTTP.PlatformSupport.Threading.ThreadedRunner/<>c__DisplayClass6_0:<RunLongLiving>b__0 (object) (at Assets/Best HTTP/Source/PlatformSupport/Threading/ThreadedRunner.cs:111)
System.Threading.ThreadHelper:ThreadStart (object)

The even stranger thing is if I swap out BestHTTP2 for BestHTTP1 (Basic) I don't receive that error, which leads me to the conclusion that there must be something strange going on with BestHTTP2. I can provide a working stripped-down version of the c# portion if necessary.

**Comment by Benedicht** [comment]
This error happens when the client tries to reuse the connection, but the server already closed it. If i remember right, between v1 and v2 the default idle times are got changed, so it's possible that with v1 the client closes the connection before the second request, while with v2 the client still have the connection around but the server closed it in the meantime.

You can change the default idle time:
```cs
HTTPManager.MaxConnectionIdleTime = TimeSpan.FromSeconds(4);
```

or disable it completely:
```cs
HTTPManager.KeepAliveDefaultValue = false;
```

You can read more about connection pooling here: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/ConnectionPool.html

**Comment by Benedicht** [comment]
Yeah, you're closing the connection after writing the request, giving no chance reusing the connection: `self.close_connection = True`

So you have to disable connection pooling completely: `HTTPManager.KeepAliveDefaultValue = false;`

**Comment by AlejandroHuerta** [comment]
Hey, thanks for the response. I think `close_connection` is defaulted to True anyways because removing the line doesn't change the behavior and setting it to False seems to just hang the connection. Changing `KeepAliveDefaultValue` to false does fix the issue, so thanks for that info!
