### ISSUE TITLE
How to Upgrade the BestHTTP.WebSocket for new version?

### ISSUE THREAD

**Issue by Alobal** [Benedicht/BestHTTP-Issues#181]
In the old version, we use the `WebSocket` class in the `BestHTTP.WebSocket` namespace. And for the new version, what namespace is used to replace it?

Sorry for not found the solution in the Upgrade guide.

**Comment by Alobal** [comment]
Actually, we encountered a Crash Problem in the old version, the crash log as follow:
```
1
libc.prop_area::map_prop_area_rw(char const*, char const*, bool*)(map_prop_area_rw:262)
2
System.Net.Sockets.Socket.Socket_internal (System.Net.Sockets.Socket,System.Net.Sockets.AddressFamily,System.Net.Sockets.SocketType,System.Net.Sockets.ProtocolType,int&)(Native Method)
3
System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily,System.Net.Sockets.SocketType,System.Net.Sockets.ProtocolType)(0xdf:223)
4
BestHTTP.PlatformSupport.TcpClient.General.TcpClient.Init (System.Net.Sockets.AddressFamily)(0x5b:91)
5
BestHTTP.PlatformSupport.TcpClient.General.TcpClient.Connect (System.Net.IPAddress[],int)(0xfb:251)
6
BestHTTP.PlatformSupport.TcpClient.General.TcpClient.Connect (string,int)(0x1db:475)
7
BestHTTP.Connections.TCPConnector.Connect (BestHTTP.HTTPRequest)(0x49f:1183)
8
BestHTTP.Connections.HTTPConnection.ThreadFunc ()(0x1c7:455)
9
BestHTTP.PlatformSupport.Threading.ThreadedRunner.<>c__DisplayClass5_0.<RunLongLiving>b__0 (object)(0x27:39)
10
System.Threading.ThreadHelper.ThreadStart_Context (object)(0xef:239)
11
System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)(0x1b7:439)
12
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)(0x2b:43)
13
System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)(0x4f:79)
14
System.Threading.ThreadHelper.ThreadStart (object)(0x3f:63)
15
<Module>.runtime_invoke_void__this___object (object,intptr,intptr,intptr)(Native Method)
```

So, we are trying to upgrade version to solve this. Or, could you help us solve it at the old version?

**Comment by Benedicht** [comment]
> In the old version, we use the WebSocket class in the BestHTTP.WebSocket namespace. And for the new version, what namespace is used to replace it?

The new version is now modularized, the Best HTTP package contains only the HTTP protocol and [a common, shared infrastructure](https://bestdocshub.pages.dev/#q-how-are-the-best-packages-interconnected-and-what-are-their-dependencies) for all the other packages. 
The WebSocket protocol is now in the [Best WebSockets](https://bestdocshub.pages.dev/WebSockets/) asset and got its own [Upgrade Guide](https://bestdocshub.pages.dev/WebSockets/upgrade-guide/).

> Actually, we encountered a Crash Problem in the old version, the crash log as follow:
> System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily,System.Net.Sockets.SocketType,System.Net.Sockets.ProtocolType)(0xdf:223)

The Socket constructor receives 3 enums, i have no idea why it would crash in a lower level. I would suggest to fill up a bugreport to Unity.
