### ISSUE TITLE
Nintendo Switch's module don't provide support of access to UnityEngine.Application.persistentDataPath

### ISSUE THREAD

**Issue by am1goo** [Benedicht/BestHTTP-Issues#182]
This fix resolve this problem completely, but it is modification of third-party code.
class `Best HTTP/Source/Core/HostManager.cs`, method `SetupFolder`

![image](https://github.com/Benedicht/BestHTTP-Issues/assets/5287406/7575b0c8-600d-4035-93d4-af6d197817c9)

PS: also `ProjectSettings` should contains scripting defines: `BESTHTTP_DISABLE_CACHING`, `BESTHTTP_DISABLE_COOKIES` and `BESTHTTP_DISABLE_COOKIE_SAVE`

**Comment by Benedicht** [comment]
Thanks! Is `UnityEngine.Application.persistentDataPath` throws an exception under Nintendo Switch?

**Comment by am1goo** [comment]
Yeah, correct. It should be ignored completely.

**Comment by am1goo** [comment]
There is not a problem about defensive mechanism
There is a problem about restricted access in native code while using `UnityEngine.Application.persistentDataPath`
![image](https://github.com/Benedicht/BestHTTP-Issues/assets/5287406/41d33a47-3299-4f1a-91e9-41c35b0c4936)

**Comment by am1goo** [comment]
Also, as you can see, there is `RootCacheFolderProvider` exists.  But it's about custom business logic and not about platform exclusions.

**Comment by am1goo** [comment]
Sorry for long delay
>Could you elaborate on this?
Yeap, here is log from debug info about access to filesystem via `UnityEngine.Application.persistentDataPath`
It means, we as developers, can't use any plugins/packages/etc with usage of the property, like BestHTTP or Unity Purchasing, 
```
FS_ACCESS: { start: 1603370923, end: 1603370923, result: 0x00000202, handle: 0x0000000000000000, priority: Normal, function: "GetEntryType", path: "rom:/Data/%HOMEPATH%", entry_type: Directory }
FS_ACCESS: { start: 1603370924, end: 1603370924, result: 0x00000202, handle: 0x0000000000000000, priority: Normal, function: "GetEntryType", path: "rom:/Data/%HOMEPATH%", entry_type: Directory }
FS_ACCESS: { start: 1603370924, end: 1603370924, result: 0x00000202, handle: 0x0000000000000000, priority: Normal, function: "GetEntryType", path: "rom:/Data/%HOMEPATH%", entry_type: Directory }
FS_ACCESS: { start: 1603370924, end: 1603370924, result: 0x00000000, handle: 0x0000000000000000, priority: Normal, function: "GetEntryType", path: "rom:/Data", entry_type: Directory }
FS_ACCESS: { start: 1603370925, end: 1603370925, result: 0x00000000, handle: 0x0000000000000000, priority: Normal, function: "GetEntryType", path: "rom:/Data", entry_type: Directory }
FS_ACCESS: { start: 1603370925, end: 1603370925, result: 0x00000202, handle: 0x0000000000000000, priority: Normal, function: "GetEntryType", path: "rom:/Data/%HOMEPATH%", entry_type: Directory }
[LocalFileSystemSwitch::CreateAsDir] Trying to write to 'rom:' mount path 'rom:/Data/%HOMEPATH%'! 
FS_ACCESS: { start: 1603370925, end: 1603370925, result: 0x0031B802, handle: 0x0000000000000000, priority: Normal, function: "CreateDirectory", path: "rom:/Data/%HOMEPATH%" }
****** FS ERROR INFORMATION ******
Error: Error occurred at CreateDirectory().
nn::fs::ResultUnsupportedOperation: Error: Unsupported operation.
```

**Comment by Benedicht** [comment]
Added an exception to the call, this way sub-systems that want to use the file system will disable themself.
This solution still allows to implement a callback for a custom path.
