### ISSUE TITLE
A crash stack collected from Firebase Crashlytics

### ISSUE THREAD

**Issue by miaoyuxin** [Benedicht/BestHTTP-Issues#185]
[issue_bb2a425820058458a84eb70acc8a82f8_crash_session_659b572003a10001381839651c780dfe_DNE_0_v2_stacktrace.txt](https://github.com/Benedicht/BestHTTP-Issues/files/13856130/issue_bb2a425820058458a84eb70acc8a82f8_crash_session_659b572003a10001381839651c780dfe_DNE_0_v2_stacktrace.txt)

Hi,This is just collected. It seems that it crashed after receiving the message

![image](https://github.com/Benedicht/BestHTTP-Issues/assets/8309010/d3deb9ef-bee8-47ce-aa03-903eca527769)

**Comment by Benedicht** [comment]
I would suggest to use a recent version of Unity, i seen a lot of crashes like this fixed reccently.
