### ISSUE TITLE
Incorrect Brotli handling for AndroidMono

### ISSUE THREAD

**Issue by vadim-marchuk** [Benedicht/BestHTTP-Issues#187]
Hi there. I have encountered the same issue as described [here](https://github.com/Benedicht/BestHTTP-Issues/issues/152). While the workaround mentioned there works, I also noticed the preprocessor directives responsible for not using Brotli on Android Mono look incorrect. Can you please look at the arguments below and give your thoughts? Thank you!

#if (NET_STANDARD_2_1 || UNITY_2021_2_OR_NEWER) && (!(ENABLE_MONO && UNITY_ANDROID) || (!UNITY_WEBGL || UNITY_EDITOR))

The second part of this can be rewritten in the next format.
!(ENABLE_MONO && UNITY_ANDROID) || !UNITY_WEBGL || UNITY_EDITOR

And on the Android Mono build, this expression will give
false || true || false = true
while the expected result is false.

If Brotli is allowed in UnityEditor and on any platform except WebGL and MonoAndroid, then the expression should be
UNITY_EDITOR || (!UNITY_WEBGL && !(ENABLE_MONO && UNITY_ANDROID))

**Comment by Benedicht** [comment]
Thanks for creating a new issue. Something definately off in that define, recently received an email too about it, but had no time yet to investigate.

Your version looks correct, it will be included in the next version.
