### ISSUE TITLE
it works, but with a lot of error logs, why? (State.Set(Processing => Finished) isn't called on the main thread(0))

### ISSUE THREAD

**Issue by warriorWorld** [Benedicht/BestHTTP-Issues#188]
{"tid":1,"div":"HTTPRequest","msg":"State.Set(Processing => Finished) isn't called on the main thread(0)!","stack":"  at HTTPRequest.set_State (HTTPRequestStates value) [0x0000c] in .\/Packages\/com.tivadar.best.http\/Runtime\/HTTP\/HTTPRequest.cs:257   at Hosts.Connections.RequestEventHelper.ProcessQueue () [0x00318] in .\/Packages\/com.tivadar.best.http\/Runtime\/HTTP\/Hosts\/Connections\/RequestEvents.cs:407   at Shared.HTTPManager.OnUpdate () [0x00045] in .\/Packages\/com.tivadar.best.http\/Runtime\/Shared\/HTTPManager.cs:283   at Shared.HTTPUpdateDelegator.CallOnUpdate () [0x0000f] in .\/Packages\/com.tivadar.best.http\/Runtime\/Shared\/HTTPUpdateDelegator.cs:273   at Shared.HTTPUpdateDelegator.Update () [0x00015] in .\/Packages\/com.tivadar.best.http\/Runtime\/Shared\/HTTPUpdateDelegator.cs:263 ","ctx": [{"TypeName": "HTTPRequest", "Hash": "e5a5fc83a4e860a126dee90e219c18f7"}, {"TypeName": "HostVariant", "Hash": "82732088df68adaf4f8f24b5ba1eca28", "Host": "file"}],"t":638471475742669090,"ll":"Error","bh":1}
UnityEngine.Debug:LogError (object)
Best.HTTP.Shared.Logger.UnityOutput:Write (Best.HTTP.Shared.Logger.Loglevels,string) (at ./Packages/com.tivadar.best.http/Runtime/Shared/Logger/UnityOutput.cs:38)
Best.HTTP.Shared.Logger.ThreadedLogger:WriteJob (Best.HTTP.Shared.Logger.LogJob&) (at ./Packages/com.tivadar.best.http/Runtime/Shared/Logger/ThreadedLogger.cs:231)
Best.HTTP.Shared.Logger.ThreadedLogger:ThreadFunc () (at ./Packages/com.tivadar.best.http/Runtime/Shared/Logger/ThreadedLogger.cs:192)
Best.HTTP.Shared.PlatformSupport.Threading.ThreadedRunner/<>c__DisplayClass12_0:<RunLongLiving>b__0 (object) (at ./Packages/com.tivadar.best.http/Runtime/Shared/PlatformSupport/Threading/ThreadedRunner.cs:78)
System.Threading.ThreadHelper:ThreadStart (object)

**Comment by Benedicht** [comment]
Fixed in v3.0.7. Should be released today.

**Comment by warriorWorld** [comment]
> Fixed in v3.0.7. Should be released today.

OK, thanks for reply so quick

**Comment by Benedicht** [comment]
You should be able to update now to v3.0.7 through Unity's package manager window.

**Comment by warriorWorld** [comment]
> You should be able to update now to v3.0.7 through Unity's package manager window.

👌
