### ISSUE TITLE
Dead Lock Issues BlockingDownloadContentStream

### ISSUE THREAD

**Issue by tsroman** [Benedicht/BestHTTP-Issues#189]
Method Read(byte[] buffer, int offset, int count) will dead block your thread when Content Stream is fully consumed (IsCompleted)
Since there is nothing to read [readCount] will always be 0

The simple fix is just to check for completion.
Replace line 150 with
```while (readCount == 0 && IsCompleted == false)```

Also, in line 114 I get a pragma warning CS0197 which appears as an error in my JetBrains Rider code editor. (It's just distraction)
Would be good if this gets wrapped in #pragma warning disable/restore CS0197 block.

**Comment by Benedicht** [comment]
Thank you for your report, the fixes will be included in the next version!
