### ISSUE TITLE
Azure SignalR service does not support receving SignalR messages in serverless mode

### ISSUE THREAD

**Issue by dmlo** [Benedicht/BestHTTP-Issues#19]
As per [this documentation](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-serverless-development-config#sending-messages-from-a-client-to-the-service) the Azure SignalR service does not support receiving messages from clients at this time when using it in Serverless mode.

Clients should invoke Azure Functions by normal http triggers.

It may be worthwhile to update your [Azure SignalR documentation page](https://besthttp-documentation.readthedocs.io/en/latest/#6.%20SignalR%20Core/Azure%20SignalR%20Service/) to give users a heads up.

**Comment by Benedicht** [comment]
Thanks, added!
