### ISSUE TITLE
Can HTTPRequest implement IDisposable?

### ISSUE THREAD

**Issue by tsroman** [Benedicht/BestHTTP-Issues#190]
HTTPRequest does have a Dispose method but doesn't implement an IDisposable interface,

So it's impossible to use it with using operator.

**Comment by Benedicht** [comment]
Yep, that's true. On the other hand, you shouldn't dispose the request manually. Dispose is called by the plugin when it's safe to do. You just have to create the request, setup the callbacks and call Send on it, the plugin will take care freeing up any resources allocated.

**Comment by tsroman** [comment]
I see ok, I understand. Based on that I suggest making it internal so the user will not have the option to call it freely.

**Comment by Benedicht** [comment]
Yeah, that's what i just did. :)
Originally, HTTPRequest does implemented the IDisposable interface and the public Dispose function is the remnant of this.
