### ISSUE TITLE
If Dispose HTTPRequest before its completion or Abort, we get an Exception error.

### ISSUE THREAD

**Issue by tsroman** [Benedicht/BestHTTP-Issues#191]
I think the Dispose method should Abort() HTTPRequest automatically

**Comment by Benedicht** [comment]
As noted in https://github.com/Benedicht/BestHTTP-Issues/issues/189 you shouldn't even call Dispose() manually. Abort is a different function because the processing cancellation takes time and some resources can be freed safely only when it's finished.
