### ISSUE TITLE
use websocket  OnWebSocketBinaryNoAllocDelegate  todeal protobuf

### ISSUE THREAD

**Issue by luyangliu616** [Benedicht/BestHTTP-Issues#192]
i use websocket  OnWebSocketBinaryNoAllocDelegate  to deal  with protobuf 
and sometimes get this problem
`{"tid":54,"div":"TCPStreamer","msg":"ContentConsumer.OnContent","ex": [{"msg": "Payload from the server is masked!", "stack": "  at Best.WebSockets.Implementations.Frames.WebSocketFrameReader.Read (System.IO.Stream stream) [0x0011a] in \/Users\/junhong\/Documents\/VizUnityNew\/viz_unity\/Assets\/Libs\/BestWebsockets\/Runtime\/Implementations\/Frames\/WebSocketFrameReader.cs:157 \n  at Best.WebSockets.Implementations.OverHTTP1.OnContent () [0x0002b] in \/Users\/junhong\/Documents\/VizUnityNew\/viz_unity\/Assets\/Libs\/BestWebsockets\/Runtime\/Implementations\/OverHTTP1.cs:483 \n  at Best.HTTP.Shared.PlatformSupport.Network.Tcp.Streams.NonblockingTCPStream.OnContent (Best.HTTP.Shared.PlatformSupport.Network.Tcp.TCPStreamer streamer) [0x00017] in \/Users\/junhong\/Documents\/VizUnityNew\/viz_unity\/Assets\/Libs\/BestHttp\/Runtime\/Shared\/PlatformSupport\/Network\/Tcp\/Streams\/NonblockingTCPStream.cs:100 \n  at Best.HTTP.Shared.PlatformSupport.Network.Tcp.TCPStreamer.OnReceived (System.IAsyncResult asyncResult) [0x000aa] in \/Users\/junhong\/Documents\/VizUnityNew\/viz_unity\/Assets\/Libs\/BestHttp\/Runtime\/Shared\/PlatformSupport\/Network\/Tcp\/TCPStreamer.cs:304 "}],"stack":"  at Shared.PlatformSupport.Network.Tcp.TCPStreamer.OnReceived (System.IAsyncResult asyncResult) [0x000c0] in \/Users\/junhong\/Documents\/VizUnityNew\/viz_unity\/Assets\/Libs\/BestHttp\/Runtime\/Shared\/PlatformSupport\/Network\/Tcp\/TCPStreamer.cs:308   at System.Net.Sockets.SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state) [0x00000] in <7a81e51e915a4e3a83ecbb5584005dd3>:0   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <2ccb053bed3740ab940e67afec38ab31>:0   at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <2ccb053bed3740ab940e67afec38ab31>:0   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <2ccb053bed3740ab940e67afec38ab31>:0 ","ctx": [{"TypeName": "TCPStreamer", "Hash": "648eb7a9dda0bd9318e59428eab92268"}, {"TypeName": "HTTPOverTCPConnection", "Hash": "6389579364ed397aff26f2317859f87b", "HostKey": "{\"Uri\":\"ws:\/\/[192.168.150.1:8888](http://192.168.150.1:8888/)\", \"Proxy\": , \"Key\": 85b3e2af0837ab6bf5925b37a6f82f64}", "RequestHandler": "1acc32701d3cacc54f24f73558a0dbee"}],"t":638481924722402540,"ll":"Exception","bh":1}
UnityEngine.Debug:LogError (object)
Best.HTTP.Shared.Logger.UnityOutput:Write (Best.HTTP.Shared.Logger.Loglevels,string) (at Assets/Libs/BestHttp/Runtime/Shared/Logger/UnityOutput.cs:38)
Best.HTTP.Shared.Logger.ThreadedLogger:WriteJob (Best.HTTP.Shared.Logger.LogJob&) (at Assets/Libs/BestHttp/Runtime/Shared/Logger/ThreadedLogger.cs:231)
Best.HTTP.Shared.Logger.ThreadedLogger:ThreadFunc () (at Assets/Libs/BestHttp/Runtime/Shared/Logger/ThreadedLogger.cs:192)
Best.HTTP.Shared.PlatformSupport.Threading.ThreadedRunner/<>c__DisplayClass12_0:<RunLongLiving>b__0 (object) (at Assets/Libs/BestHttp/Runtime/Shared/PlatformSupport/Threading/ThreadedRunner.cs:78)
System.Threading.ThreadHelper:ThreadStart (object)`

**Comment by Benedicht** [comment]
Fixed in next version.
