### ISSUE TITLE
[SignalR] Add support for stateful reconnect

### ISSUE THREAD

**Issue by ruben-ivre** [Benedicht/BestHTTP-Issues#193]
ASP.Net Core 8.0 added support for [stateful reconnect](https://learn.microsoft.com/en-us/aspnet/core/signalr/configuration?view=aspnetcore-8.0&tabs=dotnet#configure-stateful-reconnect), queueing messages in either side until the reconnect is completed and resuming from there.
From what I can see in BestHTTP SignalR client code there's no support for that yet, and it is really useful to have it, specially for apps that are stateful (like our case), because resyncing the state after a disconnect can be really complicated, so queueing messages is a much preferred solution.
I would be happy even if we didn't have the client-side queueing, just the support for the server-side one.

From what I see in the ASP.Net repository [documentation](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/HubProtocol.md), this requires adding two new messages to the protocol (Ack and Sequence) and probably some changes to the negotiation step.

**Comment by Benedicht** [comment]
I would love to! Unfortuantely, the current documentation covers only a fraction of the needed knowledge to implement it. Both the Hub protocol and transport protocol changes drastically when stateful reconnect is negotiated. 
There's an [open issue](https://github.com/dotnet/aspnetcore/issues/53103) for them to update the docs, but i don't know when they will take their time to do it.
While i could reverse engineer the protocol as i did for a few protocols (like with socket.io 1.0 that hasn't had any documentation about the protocol at that time), but i don't have the time for it.

**Comment by ruben-ivre** [comment]
I needed the feature, so I ended up implementing it myself. I still need to run some more tests on it, but so far is working ok, although it might not be perfect. I've only implemented the websockets and message pack parts, cause that's what I needed it for.

What I have so far is:
- Added the new message types, ack and sequence.
- Sending acks when receiving messages from the server.
- Queueing messages sent and removing them from queue when ack's from server.
- Reconnect without renegotiate.
- Send and receive new sequence numbers on reconnect.
- Resend queued messages on reconnect.

All this is guarded by an `Options.UseStatefulReconnect` flag, so it's pretty safe to add it.

I have permission from my employer to share this patch with you, so you can integrate in your asset if you are willing to. Let me know if you want it and we can arrange it. It's about couple hundred lines added or changed.

**Comment by Benedicht** [comment]
Of course i'm happy to take a look on it.

**Comment by ruben-ivre** [comment]
> Of course i'm happy to take a look on it.

I've sent you the code by email. Let me know how it goes.

**Comment by Benedicht** [comment]
Thanks @ruben-ivre, it seems at best I'll have time next week to check it out.

**Comment by Benedicht** [comment]
Hi Ruben, 

thanks again for the code and sorry for the late reply. I could review your implementation the previous week, but had no time to come back since.

Made a few cosmetic changes for my likings here and there. The only bigger change was to add `UseStatefulReconnect` to the server's `NegotiationResult` and check this value instead of the value stored in `HubOptions`.
Also added support for the new messages to the other encoders too.

**Comment by ruben-ivre** [comment]
@Benedicht I've sent you another small patch that fixes a couple bugs.

**Comment by vandelpal** [comment]
@Benedicht  We have NullReference Exception in HubConnection.SendMessage (and in other places) when setting HubOptions.SkipNegotiation = true and try to send a request in the new version of BestHttp. Please check and fix it in the next release.

**Comment by Benedicht** [comment]
> @Benedicht We have NullReference Exception in HubConnection.SendMessage (and in other places) when setting HubOptions.SkipNegotiation = true and try to send a request in the new version of BestHttp. Please check and fix it in the next release.

I plan to relase the next update in a couple of days.
