### ISSUE TITLE
Ide gives errors but compiles and runs anyway

### ISSUE THREAD

**Issue by boraty14** [Benedicht/BestHTTP-Issues#194]
First picture is giving  an error for documentation for mismatched parameters, which is okay but second one seems like it is warning for some kind of runtime issue. Don't know if it is actually an issue or not. Bought the socket io bundle by the way and it really works nice and no problem so far but this constant errors in IDE are kind of annoying. Using Unity 2020.3.20.
![Screenshot 2024-04-11 162607](https://github.com/Benedicht/BestHTTP-Issues/assets/85781952/ddeaf40c-a185-437d-aa11-0c0bb9a0f2be)
![Screenshot 2024-04-11 162622](https://github.com/Benedicht/BestHTTP-Issues/assets/85781952/231d0d7a-1a38-45f8-b25d-8b1d579e77bf)

**Comment by Benedicht** [comment]
Thanks for the report, fix will be included in the next version!
