### ISSUE TITLE
TypeError: Module.dynCall_viiiii is not a function Unity 6 PWA

### ISSUE THREAD

**Issue by varietec** [Benedicht/BestHTTP-Issues#196]
<img width="712" alt="Screenshot 2024-05-21 at 6 39 49 PM" src="https://github.com/Benedicht/BestHTTP-Issues/assets/122415619/c95b45c6-6097-44db-8803-0754fc741c9a">

**Comment by varietec** [comment]
Its happening when we target web assembly 2023.

**Comment by Benedicht** [comment]
What version of the plugin do you use? 
WebAssembly 2023 support added in [v3.0.8](https://bestdocshub.pages.dev/HTTP/changelog/#308-2020-05-20).
