### ISSUE TITLE
BlockingDownloadContentStream InvalidOperationException

### ISSUE THREAD

**Issue by tsroman** [Benedicht/BestHTTP-Issues#199]
Hi, im getting on rare occasions InvalidOperationException when using BlockingDownloadContentStream in cycle read.

Issue should be in this line Packages\com.tivadar.best.http\Runtime\HTTP\Response\BlockingDownloadContentStream.cs:121

It checks only by flag base._isCompleted but if at that moment there are still some not consumed segments error should not throw.

So I suggest changing 
``` if (base._isCompleted) ``` 
To
```  if (base.IsCompleted) ```

**Comment by Benedicht** [comment]
Thanks for your report!
The fix will be included in the next release.
