### ISSUE TITLE
Support for negotiation handshake for Azure Functions using Azure SignalR Service 

### ISSUE THREAD

**Issue by danielekbom** [Benedicht/BestHTTP-Issues#20]
To connect to Azure SignalR Service with a Azure Functions backend, a client must complete a successful connection negotiation.
SignalR client SDKs already contain the logic required to perform the negotiation handshake. The following is in JavaScript.

const connection = new signalR.HubConnectionBuilder()
  .withUrl('https://my-signalr-function-app.azurewebsites.net/api')
  .build()

Read more about the concept here:
https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-concept-serverless-development-config

How can I do this in BestHTTP?
If it is not possible it would be awesome it it could be added in a future release.
Thanks!

**Comment by Benedicht** [comment]
Last time i checked a few weeks ago, it worked flawlessly. You have to use the Azure authenticator and pass the uri with the /api/ path.
This was my code that connected to the sample that can be found in [this quickstart](https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-csharp):
```
class TestMessage
{
    public string sender;
    public string text;
}

public override void Do_Test()
{
    var conn = new HubConnection(new Uri("http://localhost:7071/api/"), new JsonProtocol(new BestHTTP.SignalRCore.Encoders.LitJsonEncoder()));
    conn.AuthenticationProvider = new AzureSignalRServiceAuthenticator(conn);
    conn.OnConnected += OnConnected;
        
    conn.On<TestMessage>("newMessage", msg =>
    {
        Debug.Log(msg.text);
    });
        
    conn.Send("SendNewMessageToAll", new TestMessage { sender = "Bob", text = "something" });
        
    conn.StartConnect();
}

private void OnConnected(HubConnection hub)
{
    Debug.Log("Connected!");

    var request = new HTTPRequest(new Uri("http://localhost:7071/api/messages"), HTTPMethods.Post);

    request.AddHeader("Content-Type", "application/json");

    string json = LitJson.JsonMapper.ToJson(new TestMessage { sender = "Bob", text = "something" });
    request.RawData = System.Text.Encoding.UTF8.GetBytes(json);

    request.Send();

}```

**Comment by danielekbom** [comment]
> ```cs
> AzureSignalRServiceAuthenticator
> ```

Thanks, I will try. What is AzureSignalRServiceAuthenticator? I cannot find any information about it.

**Comment by danielekbom** [comment]
@Benedicht Sorry I have found the BestHTTP documentation about this now. Previously I accidentally read under SignalR and not SignalR Core. Will see if I can figure out how to get it to work now.
[https://besthttp-documentation.readthedocs.io/en/latest/#6.%20SignalR%20Core/Azure%20SignalR%20Service/](url)

**Comment by Benedicht** [comment]
@danielekbom Yesterdey received and closed Azure SignalR Core and Azure Functions related issues, mistakenly thought you are the same author otherwise i would include the authenticator too, sorry.

**Comment by danielekbom** [comment]
@Benedicht Got it working by following the documentation, great documentations! Thanks :)
