### ISSUE TITLE
IndexOutOfRangeException on standalone client

### ISSUE THREAD

**Issue by lastdan** [Benedicht/BestHTTP-Issues#201]
Hi. We're getting the next exception from some clients on Windows:

IndexOutOfRangeException: Index was outside the bounds of the array.
Best.HTTP.Shared.PlatformSupport.Network.Tcp.TCPRingmaster.OnLaneFinished (System.IAsyncResult ar) (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
UnityEngine.Debug:LogException(Exception)

Unity version 2022.3.40, OS Windows 10 64bit.

**Comment by Benedicht** [comment]
How frequent are these errors?

**Comment by dimamatik** [comment]
v 2.8.5 - without exceptions
3.0.8 & 3.0.10 versions - we start to receive exceptions in cloud.unity.com crash reporting
How often: ~1000 users online in 24h, received 215 exceptions from 21 users
OS versions - Windows 7, 8.1, 10, 11 (64bit)
How to reproduce - we do not know

**Comment by dimamatik** [comment]
we received few more exceptions:

IndexOutOfRangeException: Index was outside the bounds of the array.
UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs)

with stack trace:

System.Net.Sockets.SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () (at <00000000000000000000000000000000>:0)
UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs)
Best.HTTP.OnRequestFinishedDelegate:Invoke(HTTPRequest, HTTPResponse)

maybe... it crashes during exception logging?

**Comment by Benedicht** [comment]
> System.Net.Sockets.SocketAsyncResult+<>c.b__27_0 (System.Object state) (at <00000000000000000000000000000000>:0)
System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () (at <00000000000000000000000000000000>:0)
System.Threading.ThreadPoolWorkQueue.Dispatch () (at <00000000000000000000000000000000>:0)
System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () (at <00000000000000000000000000000000>:0)
UnityEngine.<>c:b__0_0(Object, UnhandledExceptionEventArgs)
Best.HTTP.**OnRequestFinishedDelegate**:Invoke(HTTPRequest, HTTPResponse)

`OnRequestFinished` is the user code that gets called when a request is finished, i don't know how the ThreadPool gets in the mix. 
The whole issue is quite strange, i wouldn't exclude the possibility that it's a Unity/IL2CPP issue (unfortunately seen a few). The first stack trace if from `OnLaneFinished`, however, it's operating on an array that's never changes.
