### ISSUE TITLE
Unable to read data from the transport connection : Interupted

### ISSUE THREAD

**Issue by HaSyHieu** [Benedicht/BestHTTP-Issues#203]
Hello, I'm using your websocket implementation and i am using those configuration 
- webSocket.StartPingThread = true
- webSocket.PingFrequency = 2 
- webSocket.closeAfterNoMessage = TimeSpan.FromSeconds(1.5f);

Sometimes, the server works well, but the websocket close with error : Unable to read data from the transport connection : interupted and the connection is closed. Can you guess the problem ?

**Comment by Benedicht** [comment]
What version of the plugin do you use?

**Comment by HaSyHieu** [comment]
I use version 3.0.0

**Comment by HaSyHieu** [comment]
hey @Benedicht, i also check that in some weak android device, when i push the data through websocket, there was a delay from the sent to the server. Why ?

**Comment by Benedicht** [comment]
There were changes how the plugin sends out ping messages, could you try out the [latest](https://bestdocshub.pages.dev/WebSockets/changelog/) (v3.0.5) version of the WebSocket asset?

**Comment by vaghelamohit** [comment]
Hello @HaSyHieu.  Did you find a solution to the interrupted connection?

**Comment by Benedicht** [comment]
Unfortunately, no. Could you follow the steps here to collect and send over diagnostic logs from the plugin: https://bestdocshub.pages.dev/Shared/logging/how-to-report-a-bug/#reporting-bugs

**Comment by HaSyHieu** [comment]
@mohitghostt @Benedicht Ok, I wil check the log. Too much works. I also remove the ping part
