### ISSUE TITLE
header customizing

### ISSUE THREAD

**Issue by philosucker** [Benedicht/BestHTTP-Issues#205]
Hello
I am currently developing a part that attempts to connect a websocket from a Unity client to a server developed with FastAPI.

Here is what I would like to ask you:
When I try to connect a websocket from a Unity client to a FastAPI server, I want to put a JWT token in the websocket header when I first try to connect.
I wonder if this is possible using the Best WebSocket you created.
Is it true that customizing the websocket header is possible with Best WebSocket?
I couldn't find the relevant information in the documentation you provided, so I'm asking here.
If it is possible, can I purchase the Best WebSockets Bundle that you are selling on the Unity Asset Store?

**Comment by Benedicht** [comment]
You can add headers by subscribing to the WebSocket's [OnInternalRequestCreated](https://bestdocshub.pages.dev/WebSockets/api-reference/WebSockets/WebSocket/#actionwebsocket-httprequest-oninternalrequestcreated) callback. 
But **you can't use it in WebGL builds**!

**Comment by philosucker** [comment]
THANKS!!
