### ISSUE TITLE
SignalR asmdef missing reference to MessagePack

### ISSUE THREAD

**Issue by BenIVRE** [Benedicht/BestHTTP-Issues#207]
With the latest version of the Best.SignalRCore package (installed via Package Manager) there's the new `MessagePackCSharpProtocol` class that is behind the define `BEST_SIGNALR_ENABLE_MESSAGEPACK_CSHARP`. However, enabling this define reveals that the `MessagePack` assembly is not referenced in `Packages\com.tivadar.best.signalrcore\Runtime\com.Tivadar.Best.SignalR.asmdef`

**Comment by Benedicht** [comment]
If you follow the [instructions](https://bestdocshub.pages.dev/SignalR/intermediate-topics/encoders/#messagepack-csharp) you should have a `MessagePack.asmdef` file somewhere in your project. Unity should automatically reference it and when you add the `BEST_SIGNALR_ENABLE_MESSAGEPACK_CSHARP` define `MessagePackCSharpProtocol` class shouldn't display any error.

Alternately, you can locate the `MessagePack.asmdef` file manually and reference it in the `com.Tivadar.Best.SignalR.asmdef` file.
