### ISSUE TITLE
Potential managed memory leak with HTTP2Handler disposal

### ISSUE THREAD

**Issue by ogata-daichi-boi** [Benedicht/BestHTTP-Issues#210]
It seems that HTTP2Handler is subscribed to HTTP2SettingsRegistry, but is not unsubscribed, thus leaving streams, requests, responses etc hanging without garbage collection
Plugin version: 2.8.6

Event subscription line: HTTP2Handler.cs:146
this.settings.RemoteSettings.OnSettingChangedEvent += OnRemoteSettingChanged;

**Comment by Benedicht** [comment]
While it doesn't unsubscribe explicitly, when the HTTP2 connection is closed the handler instance becomes unreferenced, so both the handler and its settings can be collected by the GC.
