### ISSUE TITLE
URL and TextEncoder are not supported on WeChatMini (WebGL) platform.

### ISSUE THREAD

**Issue by feraligatr** [Benedicht/BestHTTP-Issues#213]
BestHTTP version: 3.0.11
BestWebSockets version: 3.0.6
Unity 2022.3.27f1
Platform: WebGL

WeChatMini is a restricted WebGL platform. It has it's own WebSocket implementation.
In BestHTTP_WebRequest.jslib and BestHTTP_WebSocket.jslib, URL, console.log, TextEncoder and TextDecoder are used, which are not supported on this platform.
I don't have a good way to solve it. I just:
- commented console.log
- use strings directly instead of URLs
- use a polyform library "https://github.com/anonyco/FastestSmallestTextEncoderDecoder/blob/master/EncoderDecoderTogether.min.js" for TextEncoder/TextDecoder

**Comment by Benedicht** [comment]
Thanks for the tips, i do not plan to support WeChatMini or the addition of more 3rd party code at the moment.
