### ISSUE TITLE
HeartbeatManager causes CPU spikes

### ISSUE THREAD

**Issue by MarcMenghin** [Benedicht/BestHTTP-Issues#215]
Unity 6000.0.26f1
BestHTTP 3.0.11
BestWebSockets 3.0.6
BestSignalR 3.0.3

I am creating a simulation which uses BestSignalR to get realtime position data. Everything runs smoothly except about every now an then there is a noticeable lag. From what I can see in the Unity Profiler the suspect is the HeartbeatManager which uses over 50% (most of the time around 80%) of CPU time in theses spikes. At the same time the GC is triggered as well (which amplifies the problem)

![grafik](https://github.com/user-attachments/assets/3487f44d-7d48-41a3-b20e-4a32d2bea21e)

![grafik](https://github.com/user-attachments/assets/b916ea61-4988-4f2f-9e20-f1182903d4b0)

I could not see anything else that looks suspicious in the logs or otherwise.

Is there a way to improve the situation, maybe some configuration for the Heartbeat? Is it expected like this, or did I configure something wrong? Do I even need the Heartbeat if I constantly get position updates (at least one every 1-2 Sec)?

**EDIT:** Did a deep Profile: About 50% of the time is spent in ` JsonProtocol.ParseMessage()` and allocates 1.7MB of memory. Also, around 37% of the time is spent in `HubConnection.OnMessage()`. In there it uses 31% in `JsonProtocol.GetRealArguments()`. 

So, how do I speed up Json handling?

**Edit2:** 

JitJsonEncoder is worse in over all CPU time but slightly better in Memory (so smaller GC) compared to JsonDotNetEncoder.

**Comment by Benedicht** [comment]
You're receiving quite a large message from the server. First of all, i would try to reduce it.
It also possible to use a binary-based encoder like [MessagePack-CSharp](https://bestdocshub.pages.dev/SignalR/intermediate-topics/encoders/#messagepack-csharp) or [GameDevWare MessagePack](https://bestdocshub.pages.dev/SignalR/intermediate-topics/encoders/#gamedevware-messagepack). They both implement the MessagePack protocol.

It's also possible to run OnUpdate calls on a thread, but that also means that you can't interact with most of the Unity systems directly from events/callbacks.

**Comment by MarcMenghin** [comment]
Thank you for the fast response! 

The only messages I get are the position updates and an occasional ping. I thought that the HeartbeatManager is related to the ping messages I get, so have nothing to do with my position updates (but I did not verify this). 

The position update event might be on the bigger side compared to other messages. I will check that next. A single update is small but they will definitely arrive in bursts from the server.

Production environment is WebGL, so I think threads will not be helpful in my case as WebGL is singlethreaded. Please correct me if I am wrong there. The Messages I get are directly put into a Queue where a Worker takes care of a few each frame (to not cause a lag when many position updates arrive within a single frame).

**Comment by Benedicht** [comment]
Both OnUpdate calls and the HeartbeatManager are part of the larger ecosistem of the plugin, they are there to help maintain the state of the protocols. Most of the logic is run from these, like handling callbacks.
With SignalR, the plugin subscribes to the same public OnMessage events of the WebSocket protocol and have to parse the json messages there too.

As far as i know, multithreaded isn't enabled on the c# side in WebGL, so yeah, running OnUpdate from a thread isn't an option for you at the moment.

But, you can still try to switch to MessagePack instead of using Json. Also, if you have burst of messages, i would try to send them in one larger message, it would have less overhead.
