### ISSUE TITLE
socket.io custom headers

### ISSUE THREAD

**Issue by Upd4ting** [Benedicht/BestHTTP-Issues#25]
It would be great to have some sort of `customHeaders` dictionnary in the `SocketOptions` of SocketIO to be able to inject some custom headers in the websocket http request or polling one.

I could make you the needed changes if you tell me that you could add them to your library

**Comment by Benedicht** [comment]
What i thought is to add a callback that receives the SocketManager and the HTTPRequest objects. This way, not only headers can be added, but should be future proof for new customizations.

**Comment by Benedicht** [comment]
So, it would be something like this:

```csharp
Manager = new SocketManager(new Uri(address));

Manager.Options.HTTPRequestCustomizationCallback += HTTPRequestCustomizationCallback;

private void HTTPRequestCustomizationCallback(SocketManager manager, HTTPRequest request)
{
    request.AddHeader("Custom", "Header Value");
}
```
```

**Comment by Upd4ting** [comment]
Nice work, thank you!
