### ISSUE TITLE
Socket.io: Internal error! Message: Non-negative number required.

### ISSUE THREAD

**Issue by col000r** [Benedicht/BestHTTP-Issues#26]
I'm trying to connect to a very simple node.js chat server, running locally. But just doing this 

`var manager = new SocketManager( new Uri( "http://localhost:3000/" ) );
manager.Socket.On( SocketIOEventTypes.Connect, ( socket, packet, args ) => Debug.Log( "connected" ) ); // Debug.LogFormat("Connected {0}, {1}, {2}", socket, packet, args  ) );`

gives me this error: 

`{"tid":1,"div":"PollingTransport","msg":"ParseResponse","ex": [{"msg": "Non-negative number required.\r\nParameter name: count", "stack": "  at System.Text.UTF8Encoding.GetString (System.Byte[] bytes, System.Int32 index, System.Int32 count) [0x0003a] in <fb001e01371b4adca20013e0ac763896>:0 \r\n  at BestHTTP.SocketIO.Transports.PollingTransport.ParseResponse (BestHTTP.HTTPResponse resp) [0x00190] in F:\\PROJECTS 2020\\Mine\\Assets\\Best HTTP\\Source\\SocketIO\\Transports\\PollingTransport.cs:408 "}],"stack":"  at SocketIO.Transports.PollingTransport.ParseResponse (HTTPResponse resp) [0x002b4] in F:\\PROJECTS 2020\\Mine\\Assets\\Best HTTP\\Source\\SocketIO\\Transports\\PollingTransport.cs:454 \r  at SocketIO.Transports.PollingTransport.OnRequestFinished (HTTPRequest req, HTTPResponse resp) [0x0009a] in F:\\PROJECTS 2020\\Mine\\Assets\\Best HTTP\\Source\\SocketIO\\Transports\\PollingTransport.cs:187 \r  at Core.RequestEventHelper.HandleRequestStateChange (Core.RequestEventInfo event) [0x001d4] in F:\\PROJECTS 2020\\Mine\\Assets\\Best HTTP\\Source\\Core\\RequestEvents.cs:313 \r  at Core.RequestEventHelper.ProcessQueue () [0x002ef] in F:\\PROJECTS 2020\\Mine\\Assets\\Best HTTP\\Source\\Core\\RequestEvents.cs:221 \r  at HTTPManager.OnUpdate () [0x00001] in F:\\PROJECTS 2020\\Mine\\Assets\\Best HTTP\\Source\\HTTPManager.cs:374 \r  at HTTPUpdateDelegator.Update () [0x00020] in F:\\PROJECTS 2020\\Mine\\Assets\\Best HTTP\\Source\\HTTPUpdateDelegator.cs:171 ","ctxs":[],"t":637297288197788770,"ll":"Exception","bh":1}
UnityEngine.Debug:LogError(Object)
BestHTTP.Logger.UnityOutput:Write(Loglevels, String) (at Assets/Best HTTP/Source/Logger/UnityOutput.cs:22)
BestHTTP.Logger.ThreadedLogger:WriteToOutput(LogJob) (at Assets/Best HTTP/Source/Logger/ThreadedLogger.cs:107)
BestHTTP.Logger.ThreadedLogger:ThreadFunc() (at Assets/Best HTTP/Source/Logger/ThreadedLogger.cs:121)
BestHTTP.PlatformSupport.Threading.<>c__DisplayClass5_0:<RunLongLiving>b__0(Object) (at Assets/Best HTTP/Source/PlatformSupport/Threading/ThreadedRunner.cs:98)
System.Threading.ThreadHelper:ThreadStart(Object)`

This is the chat server code:

`var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

app.get('/', function(req, res){
  res.sendFile(__dirname + '/index.html');
});

var userId = 0;
io.on('connection', function(socket){
  socket.userId = userId ++;
  console.log('a user connected, user id: ' + socket.userId);

  socket.on('chat', function(msg){
    console.log('message from user#' + socket.userId + ": " + msg);
    io.emit('chat', {
      id: socket.userId,
      msg: msg
    });
  });
});

http.listen(3000, function(){
  console.log('listening on *:3000');
});`

What's up with that?

**Comment by col000r** [comment]
ok, getting the same result even when trying to connect to this [hello world example](https://www.tutorialspoint.com/socket.io/socket.io_hello_world.htm)

**Comment by Benedicht** [comment]
You have to connect to the http://localhost:3000/**socket.io/** url. Socket.io is bound to this path by default.
