### ISSUE TITLE
Compile Error when disabling caching [2.1.0]

### ISSUE THREAD

**Issue by legoritma** [Benedicht/BestHTTP-Issues#27]
When BESTHTTP_DISABLE_CACHING preprocessor is set, ConnectionHelper class is not compiled and give following error.

`The type or namespace name 'LoggingContext' could not be found (are you missing a using directive or an assembly reference?)`

**Comment by Benedicht** [comment]
Fixed. (Visual Studio placed using directives between #if #endif pairs...)
I can send an updated package just drop a mail to my email address (besthttp@gmail.com).
