### ISSUE TITLE
Upload speed under iOS way slower than under macOS

### ISSUE THREAD

**Issue by derwaldgeist** [Benedicht/BestHTTP-Issues#28]
First of all, I love this asset. It works very well.

However, I noticed a significant difference in upload speed on iOS compared to macOS. I am using HTTP POST to send image files to an S3 bucket. On my macOS machine (i.e. in the editor) the upload is almost instant (I restrict the image dimensions to 768 on the shorter dimension, so the files aren't that big).

On iOS, however, the same upload takes multiple seconds, even if the device is in the same WI-FI network. I am using an iPhone X, so the device speed shouldn't be a big issue.

What might cause this huge difference?

I am now working on video uploads with significant more data, so I am getting pretty worried about the speed I will be able to achieve and the resulting usability.

**Comment by Benedicht** [comment]
Unfortunately the default TLS handler (https://github.com/bcgit/bc-csharp) the plugin uses can be quite slow. On the other hand, it's feature rich and i could add features to make the HTTP/2 implementation possible.
If you use [newer versions of Unity](https://blogs.unity3d.com/kr/2018/07/11/scripting-runtime-improvements-in-unity-2018-2/), where they added a new TLS implementation you can add the following line somewhere in your startup code to switch back to SslStream: `BestHTTP.HTTPManager.UseAlternateSSLDefaultValue = false;`.
However, in this case, HTTP/2 not going to work and the plugin will use the HTTP/1 protocol only.

You can read more about the topic here: [https://besthttp-documentation.readthedocs.io/en/latest/#7. Global Topics/HTTPS/](https://besthttp-documentation.readthedocs.io/en/latest/#7. Global Topics/HTTPS/)

**Comment by derwaldgeist** [comment]
Thanks for the info. I saw the statement about BouncyCastle in the docs, but it wasn't clear to me that using it also has a performance impact. I came from BestHTTP Pro, so I basically skimmed through the changes section. I think it would be good if this was mentioned there.

One additional question: I also saw the comment in the docs that for better Thread Safety, one should call `BestHTTP.HTTPManager.Setup();`. But I couldn't find any place in the docs explaining what this statement actually does? Is it required at all times, i.e. also without respect to Thread Safety?

**Comment by derwaldgeist** [comment]
I tried setting `BestHTTP.HTTPManager.UseAlternateSSLDefaultValue = false;` now, but it didn't change much. Uploads are still painstakingly slow on my iPhone.

**Comment by Benedicht** [comment]
`BestHTTP.HTTPManager.Setup()` would be required only if you would want to use a non main thread to dispatch callbacks. So, in the 99% of cases it's not required.

About your main issue. Could send over (besthttp@gmail.com) how you set up your upload request? Also, collecting and sending over detailed logs can be handy, you can read how to set log levels and where you can find the log files here: [https://besthttp-documentation.readthedocs.io/en/latest/#7.GlobalTopics/Logging/](https://besthttp-documentation.readthedocs.io/en/latest/#7.GlobalTopics/Logging/)

**Comment by GavanWilhite** [comment]
Was there any conclusion on this? Just trying to figure out best practices for iOS upload speed.

**Comment by Benedicht** [comment]
@GavanWilhite A lot of improvements are added in [v2.2.0](https://benedicht.github.io/BestHTTP-Documentation/#changelog/#220-2020-09-02), speeding up the TLS layer quite well.
