### ISSUE TITLE
SignalR Core: InvalidDataException: Missing required property 'type'.

### ISSUE THREAD

**Issue by mctheaw** [Benedicht/BestHTTP-Issues#31]
I found an error which I have tried to investigate and fix it for days but still stuck with it.

After the client has connected with the server for 2-5 seconds, I have got a bellowing message on the **Hub_OnError** event.

**Connection closed with an error. InvalidDataException: Missing required property 'type'.**

More info:
- The server is .Net Core 3.1 running on IIS
- The client is WebGL. My mainly platform is WebGL but the error also occurs on Android and Windows but I have not tried on other target platforms.
- Error does not happen on Unity Editor.
- Hub connected with WebSocket transport using the JSON encoder.

Please let me know if you have any clue, thank you.

![SNAG-0000-20200718-174028](https://user-images.githubusercontent.com/34645912/87850967-7b1e3300-c91e-11ea-8c45-01c72d088b97.png)

**Comment by Benedicht** [comment]
Could you set the [plugin's loglevel to All](https://besthttp-documentation.readthedocs.io/en/latest/#7.GlobalTopics/Logging/), replicate your issue and send the full log to me (besthttp@gmail.com)?

**Comment by mctheaw** [comment]
I just sent the e-mail with the full log. Thank you for the very fast response,

**Comment by Benedicht** [comment]
Thank you for the logs! I think your are using an old version of the plugin with older support version for SignalR Core. In your version ping messages has no type field, while recent versions require it and the plugin sends them as it should.

**Comment by mctheaw** [comment]
I updated the latest version (2.1.0, released Jul 2, 2020) unfortunately the same issue occurs. I sent another full-log file to your e-mail.

**Comment by mctheaw** [comment]
Hi,

I have updated to the latest version 2.1.0, the full log is attached with this e-mail.

Thank you for your support.

________________________________

**Comment by Benedicht** [comment]
Received no new log files.

**Comment by mctheaw** [comment]
Sorry, my bad. I sent by reply to your GitHub email. So I forward it directly to your given email now.

**Comment by Benedicht** [comment]
Thanks, received it. Something strange happening here. Tried out both LitJsonEncoder and JsonDotNetEncoder and all of them encoded the ping message correctly.
Could you send over a repro-project?

**Comment by mctheaw** [comment]
I can not do that but no worry I will continue by myself. This may be a specific case that happens only in my project. Thank you for your help :).

**Comment by Muchaszewski** [comment]
@Benedicht Because the `type` field is not used (doesn't have any strongly typed reference), in build with a high level of code stripping, this field is removed from the execution and thus this error message. (I am using the latest version).

To fix this check if `[Preserve]` attribute is on ALL structs and their fields. eg:
```
    [Preserve]
    public struct PingMessage
    {
        [Preserve]
        public MessageTypes type { get { return MessageTypes.Ping; } }
    }
```

**Comment by Benedicht** [comment]
@Muchaszewski What version do you use? These changes should be already in [v2.7.0](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/changelog.html#270-2022-08-25).

> The best to add the whole assembly there!
If possible i would avoid adding the whole assembly to the link.xml as it would completely prevent code stripping on the plugin .

**Comment by Muchaszewski** [comment]
I was on 2.6.3, will test that new version soon!
