### ISSUE TITLE
Upload to S3 stalls for large files

### ISSUE THREAD

**Issue by derwaldgeist** [Benedicht/BestHTTP-Issues#32]
I've implemented an upload to an S3 bucket, which works fine in general. But when I tried to upload larger files, the upload stalls after a while. For a 50 MB file, the stall starts at approx 38% and then eventually times out. What might be the reason for this?

**Comment by derwaldgeist** [comment]
I just saw in the docs that this might be related to the request timeout. I would have expected that this timeout only applies if no data can be transferred anymore. Will try again with a higher timeout setting.

**Comment by derwaldgeist** [comment]
Is there a way to accomplish the behavior I was expecting, e.g. a timeout that only applies if no data can be sent anymore?

**Comment by Benedicht** [comment]
If you upload data through `UploadStream` than request timeout is disabled for the same reasons you wrote (unknown amount of data uploading on an unknown quality of network).

Adding a timer while streaming would raise a few questions. What would be a good value? What can be a reason why there's no data from the stream?
For example the stream might wait for its dependency to produce data.

**Comment by derwaldgeist** [comment]
Ok, I get where you come from. Makes sense!
