### ISSUE TITLE
Issue when send repeatedly with MessagePack

### ISSUE THREAD

**Issue by berry4u** [Benedicht/BestHTTP-Issues#33]
Hi.
I made a simple project using MessagePack encoder. I send a message (at moment a json string just for instantiating a new game object) to server receiving as response the same string.
Everything works fine but when I send (and receive) repeatedly messages randomly the following error message is thrown which I never received using Json encoder. Could it be related with client StreamBufferCapacity ?

{"tid":1,"div":"HubConnection","msg":"OnMessages - Invocation - Invoke","ex": [{"msg": "JSON parse error: Missing a comma or ']' after an array element.", "stack": "  at (wrapper managed-to-native) UnityEngine.JsonUtility.FromJsonInternal(string,object,System.Type)\r\n  at UnityEngine.JsonUtility.FromJson (System.String json, System.Type type) [0x0005c] in <1386288601af43018501cce2912f52f4>:0 \r\n  at UnityEngine.JsonUtility.FromJson[T] (System.String json) [0x00001] in <1386288601af43018501cce2912f52f4>:0 \r\n  at WebImClient.MakeStreamedGameObject (System.String json) [0x00023] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Scripts\\SignalR\\WebImClient.cs:192 \r\n  at WebImClient.<StartConnection>b__9_1 (System.String user, System.String json) [0x00000] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Scripts\\SignalR\\WebImClient.cs:84 \r\n  at BestHTTP.SignalRCore.HubConnection+<>c__DisplayClass104_0`2[T1,T2].<On>b__0 (System.Object[] args) [0x00000] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Plugins\\Best HTTP\\Source\\SignalRCore\\HubConnection.cs:822 \r\n  at BestHTTP.SignalRCore.HubConnection.OnMessages (System.Collections.Generic.List`1[T] messages) [0x00121] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Plugins\\Best HTTP\\Source\\SignalRCore\\HubConnection.cs:913 "}],"stack":"  at SignalRCore.HubConnection.OnMessages (System.Collections.Generic.List`1[T] messages) [0x00136] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Plugins\\Best HTTP\\Source\\SignalRCore\\HubConnection.cs:917 \r  at SignalRCore.Transports.WebSocketTransport.OnBinary (WebSocket.WebSocket webSocket, System.Byte[] data) [0x00067] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Plugins\\Best HTTP\\Source\\SignalRCore\\Transports\\WebsocketTransport.cs:148 \r  at WebSocket.WebSocket.<OnInternalRequestUpgraded>b__47_1 (WebSocket.WebSocketResponse ws, System.Byte[] bin) [0x0000e] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Plugins\\Best HTTP\\Source\\WebSocket\\WebSocket.cs:436 \r  at WebSocket.WebSocketResponse.Core.IProtocol.HandleEvents () [0x000f7] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Plugins\\Best HTTP\\Source\\WebSocket\\WebSocketResponse.cs:543 \r  at Core.ProtocolEventHelper.ProcessQueue () [0x00087] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Plugins\\Best HTTP\\Source\\Core\\ProtocolEvents.cs:69 \r  at HTTPManager.OnUpdate () [0x0000d] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Plugins\\Best HTTP\\Source\\HTTPManager.cs:376 \r  at HTTPUpdateDelegator.Update () [0x00020] in C:\\Users\\bnati\\source\\WebIM_Dev\\Unity\\Tests\\Test2019\\Assets\\Plugins\\Best HTTP\\Source\\HTTPUpdateDelegator.cs:171 ","ctxs":[{"TypeName": "HubConnection", "Hash": -366247680}],"t":637312195290775109,"ll":"Exception","bh":1}
UnityEngine.Debug:LogError(Object)
BestHTTP.Logger.UnityOutput:Write(Loglevels, String) (at Assets/Plugins/Best HTTP/Source/Logger/UnityOutput.cs:22)
BestHTTP.Logger.ThreadedLogger:WriteToOutput(LogJob) (at Assets/Plugins/Best HTTP/Source/Logger/ThreadedLogger.cs:107)
BestHTTP.Logger.ThreadedLogger:ThreadFunc() (at Assets/Plugins/Best HTTP/Source/Logger/ThreadedLogger.cs:121)
BestHTTP.PlatformSupport.Threading.<>c__DisplayClass5_0:<RunLongLiving>b__0(Object) (at Assets/Plugins/Best HTTP/Source/PlatformSupport/Threading/ThreadedRunner.cs:98)
System.Threading.ThreadHelper:ThreadStart(Object)

**Comment by Benedicht** [comment]
Unfortunately this is too little information. I can't see what's sent by the server and what produced by the messagepack encoder, and the exception is thrown in user code.
