### ISSUE TITLE
Can your plugin be used for checking Internet Connection?

### ISSUE THREAD

**Issue by andrewio** [Benedicht/BestHTTP-Issues#34]
So Unity Application.internetReachability is not reliable as said in docs.

Can your plugin just check Internet connection status (like [Internet Reachability Verifier](https://makaka.org/o/irv)) & how can do that?

**Comment by Benedicht** [comment]
I think the linked Internet Reachability Verifier would be a better option, you can periodically check whether you can access and the internet is accessible until the request succeeds:

```csharp
IEnumerator CheckInterNet()
{
    var waitTime = new WaitForSeconds(5);

    bool canReach;
    do
    {
        yield return waitTime;

        var request = new HTTPRequest(new Uri("http://testwebsite"));
        request.DisableCache = true;
        request.IsKeepAlive = false;

        yield return request.Send();

        canReach = request.State == HTTPRequestStates.Finished;
        Debug.Log("Internet connection available: " + canReach);
    }
    while (canReach);
}
```
