### ISSUE TITLE
.Net Core support on other platforms?

### ISSUE THREAD

**Issue by vrecluse** [Benedicht/BestHTTP-Issues#35]
There are `#if NETFX_CORE` macros in the source, but it seems only work on windows.
Any plan to support .Net Core so that BestHttp can run on linux/osx?

**Comment by Benedicht** [comment]
NETFX_CORE is there for the Universal Windows Platform when used with the .NET scripting backend instead of IL2CPP. As far as i know the plugin has no problem running on linox and osx.

Do you have concrete issues with those platforms?
