### ISSUE TITLE
SocketIO Packet.Payload returns an array with the eventname and payload

### ISSUE THREAD

**Issue by moshmage** [Benedicht/BestHTTP-Issues#39]
```c#
// connector
    private void OnConnect() {
      Debug.Log($"Player name {PlayerName.text}");

      _helloEvent = new HelloEvent(PlayerName.text);

      var events = new List<BaseEvent> {
        _helloEvent, new InjectedInWorld(),
      };

      foreach (var ev in events.Where(ev => ev.IsCallable)) {
        _connector.Socket.On(ev.Name as string, ev.Callback);
      }

      _helloEvent.EmitSelf();
    }
    
    public void Connect() {
      _connector.Connect();
      _connector.Socket.On(SocketIOEventTypes.Connect, (s, p, a) => {
        OnConnect();
      });
    }

  public class InjectedInWorld : BaseEvent {
    
    public InjectedInWorld() : base(EventsNames.InjectedInWorld, true) { }

    public override void Callback(Socket socket, Packet packet, object[] args) {
      //var s = JsonUtility.FromJson<Player>(packet.Payload); // This breaks, [{"msg": "JSON must represent an object type." 
      Debug.Log("Payload from InjectedIntoWorld -> " + packet.Payload); // ['eventname', {event: "payload"}]
    }
  }
```

I read in the documentation that using `autodecode = true` would return the event as `[string, {}]` so i didn't provided that value -- but I still get it like so.

There's really no problem, it's just that I'm having trouble parsing the `packet.Payload`; Any help would be appreciated

**Comment by Benedicht** [comment]
A packet's payload contains all the json data the server sends. The payload itself an array containing the event's name and the event's argument(s). Socket.IO designed for javascript where there's no strong typing, and it's hard to make it right on other languages.
This is why you can't convert the whole payload to a Player object. Player is just one of the element in the payload array.

**Comment by moshmage** [comment]
Mate, I know _why_ I can't convert it, just wondering if you had any idea on how to do it _on your library that we paid 50$ to use_

**Comment by Benedicht** [comment]
You should use the autodecode option only if you know what you are doing. Otherwise, you should consume the parsed arguments. The player object's properties are there, although sitting in a Dictionary<string, object>, and if you want you can construct a strongly typed Player object from it.
You can also use your prefered json converter to convert it back to json and use this json string to parse a strongly typed (player) object.

**Comment by moshmage** [comment]
@Benedicht I ended up doing something "ugly" but.. it gets the job done,

```c#
namespace helpers {
  internal static class JsonHelper {
    private static string GetPayload(string s) {
      var start = s.IndexOf("{", StringComparison.Ordinal);
      var end = s.LastIndexOf("}", StringComparison.Ordinal);
      var len = (end - start) + 1;
      return s.Substring(start, len);
    }

    public static T FromJson<T>(string s) {
      return JsonUtility.FromJson<T>(GetPayload(s));
    }
  }
}
``` 

I then consume the events with 
```c#
[Serializable] public class EventPayload {
  public string message;
  public string otherProp;
}

var parsedAndClassed = JsonHelper.FromJson<EventPayload>(packet.Payload);
```

It's not pretty, but it does the job.
