### ISSUE TITLE
WebSockets: Question on error behaviour

### ISSUE THREAD

**Issue by derwaldgeist** [Benedicht/BestHTTP-Issues#41]
Hi Benedicht,

I have a question on how BestHTTP/2 handles WebSockets connections. We are using it on mobile devices which have to react on network changes quickly, e.g. if the user walks into an area where the connection to a WIFI is lost and connection switches to LTE or vice versa.

We have noticed that BestHTTP/2 not always fires `OnClosed` or `OnError` in this case, but we were able to work-around this by activating pings. However, we've noticed two interesting things here:

1. According to the docs, the pings should be sent every 100ms per default. However, `OnError` is fired only after 10s or so, which is way longer. Why is this the case?

2. If OnError is fired in these cases, `IsOpen` is `false`, which we interpret as the WebSocket as being closed. We see that once the connection picks up again, no further messages can be sent through the socket, so we guess that this assumption is true. However, `OnClose` is not fired, which makes our own business logic believe that the socket is still open. We worked around this by checking if `IsOpen` is false, and calling our `OnClose` handler in this case, but this is pretty ugly, and we're unsure if this might lead to unwanted side-effects. Is there a reason why `OnClose` is not fired in this case?

3. The errors reported by OnError only contain a (pretty long) human-friendly text string, but not an error code. To handle them, it would be great to a) be able to use a code instead and b) know which of these error codes might happen. We tried to find this out by trial-and-error.

**Comment by derwaldgeist** [comment]
Hi @Benedicht Thanks a lot for the detailed explanations. This really helps. Wasn't aware that there's a `CloseAfterNoMessage` property as well, will check it out!

**Comment by Benedicht** [comment]
Yeah, I should rework the websocket documentation and add the missing bits too.
