### ISSUE TITLE
HttpProxy to support url bypass

### ISSUE THREAD

**Issue by davide-aldegheri** [Benedicht/BestHTTP-Issues#43]
Greetings, using your asset I stumbled upon an issue that I couldn't get around easily, I've looked through the documentation provided on how to setup a proxy, I've seen that I am able to set it globally or per request, which works perfectly well. 

Problem is that sometimes it would be useful to specify a list of urls that the proxy should ignore so that I can set it up more easily. Is there a way to do this? Would you consider it as an enhancement for this already great asset?

Thanks in advance

**Comment by Benedicht** [comment]
I have a working version, you can drop me a mail (besthttp@gmail.com) and i can send a package.

**Comment by davide-aldegheri** [comment]
Hi, I've tested your version and it's working as expected, real thanks for your efficiency and support, it does exactly what I needed.

**Comment by Benedicht** [comment]
@davide-aldegheri Great! 
It's going to be in the next release, you will be able to update as usually from the asset store.

_Also, if you found my support and plugin helpful, pelase rate/write a little review for my asset in the Unity Asset Store._
