### ISSUE TITLE
Reconnect failing when receiving a probe packet

### ISSUE THREAD

**Issue by davide-aldegheri** [Benedicht/BestHTTP-Issues#44]
Greetings,

I have an issue using socketIO through your asset, I'll try and describe you as best as I can the context.

The server I'm connecting to is using a longpolling transporter with websocket upgradable handshake. The server itself is in a cluster mode balanced with aws ALB, with sticky sessions enabled.

Sometimes when connecting to it I'm receiving a "Status Code: 400- Message: {"code":1,"message":"Session ID unknown"}" which then fails to reconnect. I've tried and debug the reason why this happens, what I saw was that when I receive that error I'm receiving a probe message from the server, which puts the State of the SocketManager in Pause. When this happens I've seen that on the OnHeartbeatUpdate method I'm correctly going in the Pause switch case but the Transport is actually null, so the check below fails when checking if the request or polling are in progress.

```
void IHeartbeat.OnHeartbeatUpdate(TimeSpan dif)
{
    switch (State)
    {
        case States.Paused:
        // To ensure no messages are lost, the upgrade packet will only be sent once all the buffers of the existing transport are flushed and the transport is considered paused.
        if (!Transport.IsRequestInProgress &&
               !Transport.IsPollingInProgress)
        {
            State = States.Open;

            // Close the current transport
            Transport.Close();

            // and switch to the newly upgraded one
            Transport = UpgradingTransport;
            UpgradingTransport = null;

            // We will send an Upgrade("5") packet.
            Transport.Send(new Packet(TransportEventTypes.Upgrade, SocketIOEventTypes.Unknown, "/", string.Empty));

            goto case States.Open;
         }
```

At first I've tried to get around this issue by resetting my connection when I was only receiving a Disconnect event without having first connected, but then I've noticed that even if I received a connection event I could still receive a subsequent disconnect and then failing to retry.

Hope this was as clear as possible, thanks in advance!

**Comment by Benedicht** [comment]
@davide-aldegheri Could you set the plugin's log level to All replicate this issue and send the produced logs to me? 
You can read more about logging in the plugin here: https://besthttp-documentation.readthedocs.io/en/latest/#7.GlobalTopics/Logging/

If it's possible to upgrade to the websocket transport, I would recommend to connect straight with it using the `SocketOptions`' `ConnectWith` property. It's not just can be workaround for this issue until i can fix it, but it can speed up the connection process too.

**Comment by davide-aldegheri** [comment]
[error.log](https://github.com/Benedicht/BestHTTP-Issues/files/5509096/error.log)

@Benedicht Thanks for your quick reply, I've prepared the produced log of the issue, hope this helps you!

I've noticed that by using ConnectWith to force the WebSocket connection I could get around the issue for now, I'll see if this is an acceptable middle ground though I'd like it to be flexible to leave the upgrade option to BestHTTP.

**Comment by Benedicht** [comment]
@davide-aldegheri Thanks for the log, it helps a lot!

**Comment by davide-aldegheri** [comment]
Greetings! I've tested your updated asset version 2.3.1 but this is not working, with the old version I'm able to connect even though I have the issue described here, but with this new version I'm not able to successfully connect in any way, LongPolling or WebSocket. Here is the [issue.log](https://github.com/Benedicht/BestHTTP-Issues/files/5716089/issue.log)
Hope this helps!

**Comment by Benedicht** [comment]
Thanks. I think it's going to be a different issue. The client sent one polling request to get the handshake data and when received sent two request to send a packet and receive any message. This last one returned with the now familiar `Session ID unknown` message. The websocket connection was in the middle of negotiating TLS.

What version do you use? I couldn't squeeze out any issue using the socket.io nodejs package, and i know one case where they use it with a python implementation of socket.io without issues.

Is it possible to prepare a repro-project and send it to me(besthttp@gmail.com)?

**Comment by davide-aldegheri** [comment]
Sure thing, I'll prepare for you a simple project and will email it to you! 

Thanks for your help!
