### ISSUE TITLE
MessagePack Vector3 native support

### ISSUE THREAD

**Issue by DominicBoettger** [Benedicht/BestHTTP-Issues#45]
The Messagepack CSharp (https://github.com/neuecc/MessagePack-CSharp) implementation provides a additional Resolver for Vector3 Unity but the types never matches as Vector3 does not seem to be a default type which is send with the additional header informations needed to support this feature on the server side.

It would be very helpful to have the possibility to send Unity data types directly over SignalR Core.

**Comment by Benedicht** [comment]
The [MessagePackProtocol](https://github.com/Benedicht/BestHTTP_Examples/blob/master/SignalRCore/Encoders/MessagePackProtocol.cs) now supports Unity's Vector2, Vector3 and Vector4.
