### ISSUE TITLE
no support for Socket.io 3.0.1

### ISSUE THREAD

**Issue by 0circle0** [Benedicht/BestHTTP-Issues#46]
socket.io 1.0 & 2.0 are outdated

**Comment by Benedicht** [comment]
The next version going to include Socket.IO 3 support.

Socket.IO 3 (and the underlying Engine.IO) had a few breaking changes and Socket.IO 2 going to remain on servers for a long time. The plugin has to support both versions seamlessly and it has a few [roadblocks](https://github.com/socketio/engine.io-protocol/issues/35).
Still, i already have a version that should work with both Socket.IO 2 and 3 without any modification to the client (other than updating the plugin). I can send you a copy if you drop me a mail with your invoice number.
