### ISSUE TITLE
HTTPRequest.Abort() doesn't shutdown the connection immediately!

### ISSUE THREAD

**Issue by feraligatr** [Benedicht/BestHTTP-Issues#48]
I called req.Abort() followed by req.Dispose() but the connection isn't closed at all. Instead it closed when next time connecting the same address or nearly 30s later, which is SOOOOOO long. I don't know why and how can I close connecting immediately?

**Comment by Benedicht** [comment]
Request and connection is two different things. A request is sent on a connection, and the connection checks whether cancellation is requested for that request. 
It's possible that the cancellation is requested after the connection last checks the request's cancellation state. In this case, the request still going to be cancelled, but the connection not going to know about this and sits there waiting for a new request to process as it would normally do.

If you have a repro project or logs produced by [setting the plugin's log level to All](https://besthttp-documentation.readthedocs.io/en/latest/#7.GlobalTopics/Logging/) I can further inspect this issue.

**Comment by Benedicht** [comment]
To answer your last question, you can take a look on the [Connection Pooling](https://besthttp-documentation.readthedocs.io/en/latest/#7.GlobalTopics/ConnectionPool/) topic of the documentation.
