### ISSUE TITLE
Suggestion for Improvements to Socket.IO code and documentation

### ISSUE THREAD

**Issue by jrabek** [Benedicht/BestHTTP-Issues#52]
First of all, great library and well worth the purchase!  This saved me a ton of time on implementation.

I wanted to pass a few ideas back that I found made it easier to work with BestHTTP when using Socket.IO all related to message passing using [Serializable] classes rather than basic types.

Maybe they can make their way into the documentation and future updates of the library?

**1) Decoding to a [Serializable] type**

I didn't see this in the documentation but this is much nicer than extracting fields by hand.

I am using socket.io message handlers like this.
```
void OnConnected(Socket socket, Packet packet, params object[] args)
{
  ...
  this.socket.On(Messages.ERROR, OnError);
  ...
}

[Serializable]
public class ServerError
{
    public string message;
    public int code;
}

private void OnError(Socket socket, Packet packet, params object[] args)
{
    var json = packet.RemoveEventName(true);        
    var error = JsonUtility.FromJson<ServerError>(json);
    GameManager.instance.ErrorHandler(error);
}
```

This way the ServerError already has the fields populated and the values enforced.  As a bonus, any nested, custom [Serializable] classes are also decoded.

**2) Sending [Serializable] types**

`bool SerializeValue(object value, StringBuilder builder)` only supports basic types and so when sending a message objects have to be manually converted to dictionaries.

Given that `JsonUtility.ToJson` already supports converting nested [Serializable] classes, it would be nice to include the ability to pass preserialized json like the following:

```
    SerializedJson WrapJson(object obj)
    {
        return new SerializedJson(JsonUtility.ToJson(obj));
    }

    public void UpdatePlayer(Player player)
    {
        var cmdUpdatePlayer = new CmdUpdatePlayer
        {
            player = player
        };

        socket.Emit(Commands.UPDATE_PLAYER, WrapJson(cmdUpdatePlayer));
    }

```

Where `SerializedJson` looks something like:
```
namespace BestHTTP.JSON
{
	public class SerializedJson {
	   public SerializedJson(string json)
           {
	      this.json = json;
           }

	   public string json;
	}
}
```

And in JSON.cs this would be added
```
bool SerializeValue(object value, StringBuilder builder) {
...
   } else if (value is SerializedJson json) {
      builder.Append(json.json);
   }
...
}
```

**3) Don't catch errors passed to handlers**

This is more of annoyance when debugging.

When socket.io message handlers are called, the calls are wrapped in a try which means it is a pain to debug errors in my code since Unity won't stop at the point the error is called.  The call stack is also a mess when printed this way.

I ended up doing this to escape the `try` block:
```
    private IEnumerator Dispatch(Action func)
    {
        func();
        yield return null;
    }

    private void OnPlayerJoined(Socket socket, Packet packet, params object[] args)
    {
        var json = packet.RemoveEventName(true);
        var playerChange = JsonUtility.FromJson<PlayerChange>(json);        
        StartCoroutine(Dispatch(() => {            
            GameManager.instance.PlayerAdded(playerChange);
        }));
    }
```

Would be nice to optionally disable the try/catch to make debugging easier (and not require the VS debugger to be attached at the time).

**Comment by Felix-N** [comment]
Thanks for 
_2) Sending [Serializable] types_
I stumbled across this issue too, having the expectation to simply be able to pass an object in.

Would love to see the library updated and an example included in the documentation.

**Comment by Benedicht** [comment]
Thanks for the feedback @Felix-N !
I'm doing the final touches and testing of the next release that going to contain a much user friendly Socket.IO implementation. With this new one you are going to be able to send complex objects and define strongly typed callbacks:

A few snippets from the new chat example:
```cs
class LoginData
{
    public int numUsers;
}

sealed class NewMessageData
{
    public string username;
    public string message;
}

sealed class UserJoinedData : LoginData
{
    public string username;
}

sealed class TypingData
{
    public string username;
}

Manager = new SocketManager(new Uri(this.address));

Manager.Socket.On<ConnectResponse>(SocketIOEventTypes.Connect, OnConnected);
Manager.Socket.On(SocketIOEventTypes.Disconnect, OnDisconnected);

Manager.Socket.On<LoginData>("login", OnLogin);
Manager.Socket.On<NewMessageData>("new message", OnNewMessage);
Manager.Socket.On<UserJoinedData>("user joined", OnUserJoined);
Manager.Socket.On<UserJoinedData>("user left", OnUserLeft);
Manager.Socket.On<TypingData>("typing", OnTyping);
Manager.Socket.On<TypingData>("stop typing", OnStopTyping);

private void OnNewMessage(NewMessageData data)
{
    AddText(string.Format("{0}: {1}", data.username, data.message));
}
```

**Comment by Benedicht** [comment]
Also, new parsers can be used now and the MsgPackParser going to be included in the package.

**Comment by Felix-N** [comment]
@Benedicht  thanks, much appreciated. im comming from the node side and c# / unity are still pretty new to me.
given that i've struggled quite a bit today getting a 'simple' nested message object back into unity.

**Comment by Benedicht** [comment]
[v2.4.0](https://assetstore.unity.com/packages/tools/network/best-http-2-155981?aid=1101lfX8E) is released now with a strongly typed Socket.IO implementation.
