### ISSUE TITLE
Redirect failed on HTTP request

### ISSUE THREAD

**Issue by maruhax** [Benedicht/BestHTTP-Issues#53]
Redirect seems to fail when the redirect URL has a query parameter.
The reason seems to be that the redirect PATH is encoded.

**Comment by Benedicht** [comment]
Could you send me an example?

**Comment by maruhax** [comment]
Exsample code.

`    private void sample()
    {
        var uri  = new Uri("https://d.navicon.com/q?i=1J533MA7ZQES&tab=1");
        var http = new HTTPRequest(uri,
                                   HTTPMethods.Get,
                                   true,
                                   true,
                                   (request, response) => {
                                      Debug.Log(response.StatusCode);    // 404
                                   });
  
        http.AddHeader("Accept", "*/*");
        http.AddHeader("Accept-Language", "en");

        http.OnBeforeRedirection += (request, response, redirect) => {
                                        Debug.Log(redirect.AbsoluteUri);
                                        return true;
                                    };
  
        CookieJar.Clear(uri.DnsSafeHost);
        http.Send();
    }
`

**Comment by Benedicht** [comment]
Thanks! Please drop me a mail to besthttp@gmail.com so i can send you an updated package.

**Comment by maruhax** [comment]
I am not in a hurry, so I will wait until the next update for an update.
Thanks.
