### ISSUE TITLE
Inquiry about the Websocket Interaction between Unity and Java via BestHTTP

### ISSUE THREAD

**Issue by RichardLoveMP** [Benedicht/BestHTTP-Issues#54]
Dear BestHTTP's developers,  
I am working on a project which is actually a sensor-controlled game. Temporarily, my project's backend is implemented in Java using **Websocket** protocol. We have successfully connected the Java part to the JavaScript (frontend), but now I want to connect the Java part to C# (i.e. Unity) at present.   

I have checked the [documentation](https://besthttp-documentation.readthedocs.io/en/latest/#2.WebSocket/) and the [sample code](https://github.com/Benedicht/BestHTTP_Examples/blob/master/Websocket/WebSocketSample.cs). However, I am still confusing how to use BestHTTP library to **receive** the WebSocket message from Java.

Therefore, can you help me with this question. For example, could you please provide some lines of sample code which uses BestHTTP to **receive** the message from a WebSocket connection (e.g. ws://.....)?

I will appreciate it if you can provide me with any assistance, and I am looking forward to your reply.

**Comment by Benedicht** [comment]
A minimal example could be something like this:

```cs
using System;
using BestHTTP.WebSocket;
using UnityEngine;

public sealed class WebSocketCloseTest : MonoBehaviour
{
    WebSocket webSocket;

    private void Start()
    {
        webSocket = new WebSocket(new Uri("ws://websocketserver"));

        webSocket.OnMessage += OnMessage;
        webSocket.OnOpen += OnOpened;
        webSocket.OnClosed += OnClosed;
        webSocket.OnError += OnError;

        webSocket.Open();
    }

    private void OnMessage(WebSocket webSocket, string message)
    {
        Debug.Log(message);
    }

    void OnOpened(WebSocket webSocket)
    {
        Debug.Log("Opened");
    }

    private void OnClosed(WebSocket webSocket, ushort code, string message)
    {
        Debug.Log("OnClosed: " + code + " " + message);
    }

    private void OnError(WebSocket webSocket, string reason)
    {
        Debug.Log("OnError: " + reason);
    }

    private void OnApplicationQuit()
    {
        if (webSocket != null)
            webSocket.Close();
    }
}
```
