### ISSUE TITLE
Any experience with the connection to a Flask-Server?

### ISSUE THREAD

**Issue by AndiHal** [Benedicht/BestHTTP-Issues#55]
Hello. I am currently working on an application where I will need an quite extensive exchange of data between Unity and a python application. On the python side I will probably work with a Flask server. For the Unity side I consider using the BestHTTP package. 
My question is if anyone has experience with this combination, especially the [Flask-SocketIO](https://flask-socketio.readthedocs.io/en/latest/) solution and the connection and exchange of data with the BestHTTP SocketIO solution for Unity/C#?
Should this work or can you anticipate problems?

**Comment by Benedicht** [comment]
Closing it now, but let me know if you still experience any issues.
