### ISSUE TITLE
[Socket.io] Transport close!

### ISSUE THREAD

**Issue by ghanbari** [Benedicht/BestHTTP-Issues#58]
I use Socket.io v4 and after connect to server, transport close because client(BestHttp Socket.io) dose not send ping request to server.

`
var options = new SocketOptions();

options.AutoConnect = false;
options.ServerVersion = SupportedSocketIOVersions.v2;
options.ConnectWith = TransportTypes.WebSocket;
Manager = new SocketManager(new Uri("http://localhost:3000/socket.io/"), options);
`

I set `pingInterval =10000ms` on server and after 10 second connection closed and reason on server is "transport close".

How can fix this?

Thank you and I am sorry, my English is very bad

**Comment by Benedicht** [comment]
It's because you inform the client to expect a Socket.io v2 server, however the server has v4.
For v4 i would highly recommend to use classes from the [SocketIO3 namespace](https://besthttp-documentation.readthedocs.io/en/latest/#3.1Socket.IO3/)!

**Comment by ghanbari** [comment]
Thank you
