### ISSUE TITLE
[Socket.IO.v3] Is this bug of BestHTTP?

### ISSUE THREAD

**Issue by johnnyapu15** [Benedicht/BestHTTP-Issues#59]
I connected with namespace using Socket.IO.v3. The namespace is "/TestRoom".

`Manager = new SocketManager(new System.Uri(uri), socketOptions);
socket = Manager.GetSocket(markerId);`

Socket Server is implemented Node.JS with express.

But when I emit custom event "ATTACH", is on error.

So I printed the raw message that sent into the Node server.

I expected the message like to be

`2/TestRoom,["ATTACH",{"socketEvent":"ATTACH","markerId":"","members":null, ... `

But I got this

`2/TestRoom["ATTACH",{"socketEvent":"ATTACH","markerId":"","members":null, ... `

Is this bug of BestHTTP? Or I missed something?

**Comment by Benedicht** [comment]
It's got fixed in [v2.5.0](https://besthttp-documentation.readthedocs.io/en/latest/#changelog/#_top).

**Comment by johnnyapu15** [comment]
Thanks for quick reply.
