### ISSUE TITLE
HTTP2 - HTTPRequest.ProcessingStarted

### ISSUE THREAD

**Issue by vasyaPP** [Benedicht/BestHTTP-Issues#60]
After upgrading from v2.2.0 to v2.4.0 I discovered issue that first request to the HTTP2 server has wrong value in ProcessingStarted property, seems it's DateTime.MinValue. All subsequent requests have the correct values according to the current date. I tested latest v2.5.0 package - problem repeats.
Also I have tested requests to the HTTP1 server with v2.5.0 and they always have the correct property values.
I can confirm that there is no such problem in v2.2.0 package.

Unity 2019.4.26f1 LTS
BestHTTP packages v2.4.0 and v2.5.0
Scripting Define Symbols: `BESTHTTP_DISABLE_CACHING;BESTHTTP_DISABLE_COOKIES;BESTHTTP_DISABLE_SERVERSENT_EVENTS;BESTHTTP_DISABLE_WEBSOCKET;BESTHTTP_DISABLE_SIGNALR;BESTHTTP_DISABLE_SIGNALR_CORE;BESTHTTP_DISABLE_SOCKETIO`

I created test script to reproduce issue. You can switch between HTTP1 and HTTP2 servers.
Below I attached logs (LogLevel.All) from test with HTTP2 server.

```
using System;
using System.Collections;
using BestHTTP;
using UnityEngine;

public class Test : MonoBehaviour
{
    private int _requestsCounter;

    private IEnumerator Start()
    {
        SendRequest();

        yield return new WaitForSeconds(5);
        
        Debug.Log("------------");

        SendRequest();
    }

    private void SendRequest()
    {
        _requestsCounter++;
        // Uri uri = new Uri("http://info.cern.ch"); // HTTP1
        Uri uri = new Uri("https://www.google.com"); // HTTP2
        
        var req = new HTTPRequest(uri, HTTPMethods.Get);
        req.Callback += (request, response) =>
        {
            Debug.Log($"request_{_requestsCounter} : DateTime.UtcNow = {DateTime.UtcNow} request.ProcessingStarted = {request.ProcessingStarted}");
        };
        req.Send();
    }
}
```

[request_1_log.txt](https://github.com/Benedicht/BestHTTP-Issues/files/6516244/request_1_log.txt)
[request_2_log.txt](https://github.com/Benedicht/BestHTTP-Issues/files/6516245/request_2_log.txt)

**Comment by Benedicht** [comment]
Fixed in the next release.
