### ISSUE TITLE
EnableDebugStackTraceCollection 

### ISSUE THREAD

**Issue by cubed-it** [Benedicht/BestHTTP-Issues#61]
Hey, unfortunately I found another issue. After updating from 2.3.2 to 2.5.0, we noticed a drop in performance. After rolling back the changes step by step we were able to trace it back to the `EnableDebugStackTraceCollection`.
Maybe it is not so good to activate this function in the unity editor by default. I have created two example videos. These represent the extreme case indeed, but even with the normal use-case there are short and slight drops in the frame rate.

https://drive.google.com/file/d/1cUtP_8Uelw6fXvvzWSPvnYjlXbjApwT1/view?usp=sharing
https://drive.google.com/file/d/1cHeZWHWUKBTS2TDDtMemKK-_Dinjufg8/view?usp=sharing

**Comment by Benedicht** [comment]
Fixed in the next release.

You can disable it by adding this line somewhere in your startup code:
```cs
BestHTTP.PlatformSupport.Memory.BufferPool.EnableDebugStackTraceCollection = false;
```
