### ISSUE TITLE
Add Multiple Binary Data To The Field

### ISSUE THREAD

**Issue by nintendaii** [Benedicht/BestHTTP-Issues#63]
Greeting! 
I am using your plugin in my project and I was wondering how can I add multiple files to the request field? I tried to find some info in the official docs but couldn't find anything. I have a field "file" in my API and I want to add more than one array of bites (more than 1 file)
<img width="865" alt="Screenshot 2021-05-31 at 18 33 35" src="https://user-images.githubusercontent.com/44233090/120215708-b7a90380-c23e-11eb-9b74-e4f10ba0482d.png">
It is pretty easy to add one file. Here is my code:
```c#

request.AddBinaryData("file",media, "media_"+id+Random.Range(1,100)+".mp4","video/mp4");
```
The second argument "media" is a simple array of bytes. How can I add more than one file?

**Comment by Benedicht** [comment]
You can by using the same field and adding the array square brackets:
```cs
request.AddBinaryData("file[]",media, "media_"+id+Random.Range(1,100)+".mp4","video/mp4");
```

**Comment by nintendaii** [comment]
I've tried this but the second parameter has incorrect type. I have a list of byte arrays (every item of the list is a file => byte[]).
How can I correctly pass different byte[]? Should I combine them to one byte[] array?
<img width="924" alt="Screenshot 2021-06-01 at 11 56 25" src="https://user-images.githubusercontent.com/44233090/120296035-65b0be00-c2d0-11eb-9d35-716519dc2c50.png">

**Comment by Benedicht** [comment]
No, you can call AdBinaryData more than once, each time with different file(byte[]) and on the server it's going to be one array.

**Comment by nintendaii** [comment]
I tried but the API returns this error. Maybe you could show me an example where more than 1 files are added to the request field? Thanks for your help.
<img width="366" alt="Screenshot 2021-06-01 at 15 15 09" src="https://user-images.githubusercontent.com/44233090/120321588-28f2c000-c2ec-11eb-8581-105eeaaa8e49.png">

**Comment by Benedicht** [comment]
This is a working example:
```cs
var request = new HTTPRequest(new Uri("http://httpbin.org/post"), HTTPMethods.Post, (req, resp) =>
{
    switch (req.State)
    {
        // The request finished without any problem.
        case HTTPRequestStates.Finished:
            if (resp.IsSuccess)
            {
                Debug.Log("Request Finished Successfully! " + resp.DataAsText);
            }
            else
                Debug.LogWarning(string.Format("Request Finished Successfully, but the server sent an error. Status Code: {0}-{1} Message: {2}",
                                                resp.StatusCode,
                                                resp.Message,
                                                resp.DataAsText));
            break;

        // The request finished with an unexpected error. The request's Exception property may contain more info about the error.
        case HTTPRequestStates.Error:
            Debug.LogWarning("Request Finished with Error! " + (req.Exception != null ? (req.Exception.Message + "\n" + req.Exception.StackTrace) : "No Exception"));
            break;

        // The request aborted, initiated by the user.
        case HTTPRequestStates.Aborted:
            Debug.LogWarning("Request Aborted!");
            break;

        // Connecting to the server is timed out.
        case HTTPRequestStates.ConnectionTimedOut:
            Debug.LogError("Connection Timed Out!");
            break;

        // The request didn't finished in the given time.
        case HTTPRequestStates.TimedOut:
            Debug.LogError("Processing the request Timed Out!");
            break;
    }
});

List<string> values = new List<string>() { "value_1", "value_2", "value_3" };
for (int i = 0; i < values.Count; i++)
    request.AddField("array_field[]", values[i]);

request.AddBinaryData("zips[]", new byte[10], "filename_1.zip");
request.AddBinaryData("zips[]", new byte[20], "filename_2.zip");

request.Send();
```

What would be really helpful is to know what's your server side and what/how it expects the data.

**Comment by Benedicht** [comment]
@nintendaii Could you got it working?

**Comment by nintendaii** [comment]
Hey! Not yet. I tried the option with brackets ("filed_name[]") but it didn't work. I think this is more API issue than plugin issue. Waiting for the explanation of the request from the backend guy.

**Comment by Benedicht** [comment]
Any update on this issue @nintendaii ?

**Comment by nintendaii** [comment]
Greetings! Unfortunately the project I have been working on was stopped. This means I cant communicate with the backend developer to potentially fix this issue. Sorry about that.

**Comment by Benedicht** [comment]
Closing this issue then until further details. Feel free to reopen it when new details are available.
