### ISSUE TITLE
Can't be as like as two peas in Microsoft's signalR code?

### ISSUE THREAD

**Issue by bbhxwl** [Benedicht/BestHTTP-Issues#64]
Can't be as like as two peas in Microsoft's signalR code?

**Comment by Benedicht** [comment]
I'm sorry, but i don't understand your question. 
Do you have any issues with it, or just asking whether it supports it? The plugin has full support for the SignalR Core protocol.

**Comment by Benedicht** [comment]
It should work without any issues.
