### ISSUE TITLE
parsing error

### ISSUE THREAD

**Issue by canaksoy** [Benedicht/BestHTTP-Issues#65]
{"tid":1,"div":"WebSocketTransport","msg":"OnMessage Packet parsing","ex": [{"msg": "Can't add a value here", "stack": "  at BestHTTP.JSON.LitJson.JsonWriter.DoValidation (BestHTTP.JSON.LitJson.Condition cond) ......

server: socket:io 4
unity 2020.3.x

defaultjsonparser

**Comment by Benedicht** [comment]
Could you share:

1. Version of the plugin ([HTTPManager.UserAgent](https://besthttp-documentation.readthedocs.io/en/latest/#7.GlobalTopics/GlobalSettings/#useragent))
2. Full log entry
3. If possible the server code that causes this error

**Comment by canaksoy** [comment]
2.5.1

`
 public class Competition
 {
    public string roomCode { get; set; }
    public List<Users> users { get; set; }
 }

        var options = new SocketOptions {AutoConnect = false};
        options.ConnectWith = TransportTypes.WebSocket;
        options.AdditionalQueryParams =
        new PlatformSupport.Collections.ObjectModel.ObservableDictionary<string, string>();
        options.AdditionalQueryParams.Add("token", token);


        manager = new SocketManager(new Uri(URL), options);

        manager.Socket.On<Competition>("competition", OnCompetition);
        manager.Socket.On("ready", OnReady);
        manager.Socket.On<int, string, string>("words", OnWords);
        manager.Socket.On("start", OnStart);

        manager.Open();

void OnCompetition(Competition competition)
    {
        Debug.Log("OnCompetition");
    }
`

Unity logs:

`{"tid":1,"div":"WebSocketTransport","msg":"OnMessage Packet parsing","ex": [{"msg": "Index was out of range. Must be non-negative and less than the size of the collection.\r\nParameter name: index", "stack": "  at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <695d1cc93cca45069c528c15c9fdd749>:0 \r\n  at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <695d1cc93cca45069c528c15c9fdd749>:0 \r\n  at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <695d1cc93cca45069c528c15c9fdd749>:0 \r\n  at BestHTTP.SocketIO3.Parsers.DefaultJsonParser.ReadParameters (BestHTTP.SocketIO3.Socket socket, BestHTTP.SocketIO3.Events.Subscription subscription, System.Collections.Generic.List`1[T] array, System.Int32 startIdx) [0x00168] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\SocketIO.3\\Parsers\\DefaultJsonParser.cs:277 \r\n  at BestHTTP.SocketIO3.Parsers.DefaultJsonParser.ReadData (BestHTTP.SocketIO3.SocketManager manager, BestHTTP.SocketIO3.IncomingPacket packet, System.String payload) [0x00130] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\SocketIO.3\\Parsers\\DefaultJsonParser.cs:240 \r\n  at BestHTTP.SocketIO3.Parsers.DefaultJsonParser.Parse (BestHTTP.SocketIO3.SocketManager manager, System.String from) [0x00237] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\SocketIO.3\\Parsers\\DefaultJsonParser.cs:123 \r\n  at BestHTTP.SocketIO3.Transports.WebSocketTransport.OnMessage (BestHTTP.WebSocket.WebSocket ws, System.String message) [0x00059] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\SocketIO.3\\Transports\\WebSocketTransport.cs:133 "}],"stack":"  at SocketIO3.Transports.WebSocketTransport.OnMessage (WebSocket.WebSocket ws, System.String message) [0x000a0] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\SocketIO.3\\Transports\\WebSocketTransport.cs:142 \r  at WebSocket.OverHTTP1.<OnInternalRequestUpgraded>b__15_0 (WebSocket.WebSocketResponse ws, System.String msg) [0x00013] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\WebSocket\\Implementations\\OverHTTP1.cs:283 \r  at WebSocket.WebSocketResponse.Core.IProtocol.HandleEvents () [0x000a4] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\WebSocket\\WebSocketResponse.cs:537 \r  at Core.ProtocolEventHelper.ProcessQueue () [0x00087] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\Core\\ProtocolEvents.cs:69 \r  at HTTPManager.OnUpdate () [0x0000d] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\HTTPManager.cs:416 \r  at HTTPUpdateDelegator.Update () [0x00020] in C:\\Users\\Wiggle\\Desktop\\Unity\\Freelance\\Can\\LetsDraw2\\Assets\\Best HTTP\\Source\\HTTPUpdateDelegator.cs:171 ","ctxs":[{"TypeName": "SocketManager", "Hash": -793657216}],"t":637586662811783002,"ll":"Exception","bh":1}
UnityEngine.Debug:LogError (object)
BestHTTP.Logger.UnityOutput:Write (BestHTTP.Logger.Loglevels,string) (at Assets/Best HTTP/Source/Logger/UnityOutput.cs:22)
BestHTTP.Logger.ThreadedLogger:ThreadFunc () (at Assets/Best HTTP/Source/Logger/ThreadedLogger.cs:130)
BestHTTP.PlatformSupport.Threading.ThreadedRunner/<>c_DisplayClass5_0:<RunLongLiving>b_0 (object) (at Assets/Best HTTP/Source/PlatformSupport/Threading/ThreadedRunner.cs:98)
System.Threading.ThreadHelper:ThreadStart (object)`

Also iOS debug logs for server-side data:

`2021-06-06 14:27:25.643598+0300 SocketTest[31306:16941170] LOG SocketEngine: Got message: 42["competition","{\"roomCode\":\"UKIROF\",\"users\":[{\"id\":83,\"fullName\":\"Emre33333\",\"isPremium\":0,\"countryCode\":\"tr\",\"packetIds\":[1,2,3],\"isBot\":false,\"isOnline\":true}]}"]
2021-06-06 14:27:25.643771+0300 SocketTest[31306:16940941] LOG SocketParser: Parsing 2["competition","{\"roomCode\":\"UKIROF\",\"users\":[{\"id\":83,\"fullName\":\"Emre33333\",\"isPremium\":0,\"countryCode\":\"tr\",\"packetIds\":[1,2,3],\"isBot\":false,\"isOnline\":true}]}"]
2021-06-06 14:27:25.643781+0300 SocketTest[31306:16941170] LOG SocketEngine: Switching to WebSockets
2021-06-06 14:27:25.643917+0300 SocketTest[31306:16941170] LOG SocketEngineWebSocket: Sending ws:  as type: 5
2021-06-06 14:27:25.644021+0300 SocketTest[31306:16940941] LOG SocketParser: Decoded packet as: SocketPacket {type: 2; data: [competition, {"roomCode":"UKIROF","users":[{"id":83,"fullName":"Emre33333","isPremium":0,"countryCode":"tr","packetIds":[1,2,3],"isBot":false,"isOnline":true}]}]; id: -1; placeholders: -1; nsp: /}`

**Comment by Benedicht** [comment]
I think the `competition` event is ok, one of your other event handlers might have more arguments than what the server sends.

**Comment by canaksoy** [comment]
OnCompetition is not working

**Comment by Benedicht** [comment]
I used the following code and it works completely fine.

Client:
```cs
public sealed class Users
{
    public int id;
    public string fullName;
    public int isPremium;
    public string countryCode;
    public int[] packetIds;
    public bool isBot;
    public bool isOnline;
}

public sealed class Competition
{
    public string roomCode { get; set; }
    public List<Users> users { get; set; }
}

manager.Socket.On<Competition>("competition", OnCompetition);

private void OnCompetition(Competition comp)
{
    Debug.Log($"OnCompetition: {comp.roomCode}, {comp.users.Count}");
}
```

Server:
```js
socket.emit('competition', {
    roomCode: "UKIROF",
    users: [
        {
            id: 83,
            fullName: "Emre33333",
            isPremium: 0,
            countryCode: "tr",
            packetIds: [1, 2, 3],
            isBot: false,
            isOnline: true
        }
    ]
});
```

**Comment by canaksoy** [comment]
![image](https://user-images.githubusercontent.com/3260696/121180544-a462ed00-c869-11eb-8473-2dc22dfe751a.png)

**Comment by canaksoy** [comment]
OK we found the problem. Server was sending with JSON.stringify. We fixed by sending as objects.
