### ISSUE TITLE
socket io v2 on pong event not received latency ms 

### ISSUE THREAD

**Issue by EthanYa** [Benedicht/BestHTTP-Issues#67]
According to socket io v2 client api  [document](https://socket.io/docs/v2/client-api/#Event-%E2%80%98ping%E2%80%99)  

```
Event: ‘pong’
ms (Number) number of ms elapsed since ping packet (i.e.: latency).
Fired when a pong is received from the server.
```

When I on `pong` event expect to receive latency ms in  Packet Payload, but received an empty string.

Has another approach can receive latency ms?

![image](https://user-images.githubusercontent.com/26006250/123749739-554c2d00-d8e8-11eb-8d48-dfef184f27dc.png)

**Comment by Benedicht** [comment]
Sorry, but this feature isn't implemented in the plugin.
