### ISSUE TITLE
Support for HTTP/3?

### ISSUE THREAD

**Issue by joaocc** [Benedicht/BestHTTP-Issues#68]
Hi,
Now that QUIC is RFC, are there any plans to support HTTP/3 (currently draft 34) when it becomes final?
Thanks

**Comment by Benedicht** [comment]
To get started with HTTP/3, one of the prerequisites i'm waiting for is the TLS 1.3 support in the BouncyCastle library. When TLS 1.3 support arrives, i can start to work on it.
