### ISSUE TITLE
[Suggestion] Ability to manually store entries in HTTPCacheService

### ISSUE THREAD

**Issue by RobinB-Gbanga** [Benedicht/BestHTTP-Issues#69]
Would it be possible to allow us to inject (handcrafted) responses into the cache, e.g. through making `HTTPCacheService.Store` public?

I keep encountering cases where I have both:
* a request to get a single item through a rest API, e.g.: `api.net/items/1`, returning a json of a single item
* a request to get a list of items, e.g.: `api.net/items`, returning a json array of 50 items

One useful pattern is to fire the "get all items" request once (e.g. on app start), putting them all into cache, and then firing the "get single item" on demand whenever needed. Requests for items that were already downloaded with the initial request could then return the file from cache immediately, while others could still hit the server to get the missing items (e.g. if new ones have been added, if the initial request only gets a subset like 'all items of chapter 1' etc).

We can roll our own cache layer of course, but since you only need very little domain-specific knowledge ("how to treat the response of the multi-item request" and "how to generate cache keys for the individual fragments"), I feel like building our own caching layer for this (and probably disabling BestHTTP's cache for these requests) seems avoidable.

Instead, we could simply fire the "get all items" request on start, split the json in the response apart, and cache each individual array element under `"${base_uri}/item.uid"`, ensuring that future single-item requests (e.g. to `api.net/items/3`) would hit the cache.

I'm happy for any thoughts on this!

**Comment by Benedicht** [comment]
v3 got a new local cache implementation with support for manually populating the cache too. The package will come with a complete example on how to do it.

Main functions are `HTTPManager.LocalCache.BeginCache`, `HTTPManager.LocalCache.EndCache` and the `HTTPCacheContentWriter` class.
