### ISSUE TITLE
SSE(Server-Sent Events) does not work at BestHTTP 2.0.5

### ISSUE THREAD

**Issue by martin-magang** [Benedicht/BestHTTP-Issues#7]
Testing with the SSE example provided, It received nothing after a while, and  the **OnError/OnClosed**  of EventSource does not be called.
There is a log **[HTTP2Stream]: [1] State changed from HalfClosedLocal to Closed** in console of Unity .

**Comment by Benedicht** [comment]
Hi Martin,

If i'm right, i already sent a link to a fixed package yesterday. Please check your emails and let me know if you didn't find it.
