### ISSUE TITLE
Is it possible to upload dictionaries?

### ISSUE THREAD

**Issue by drinikol** [Benedicht/BestHTTP-Issues#70]
Can this package handle dictionaries? or I need to simplify things into lists. Thank you!

**Comment by Benedicht** [comment]
It depends on what and how the server expects the upload. Is it expects a form with url or multipart encoded? Or it must be a json one?
Even if you use a framework where you can define strongly typed callbacks, under the hood usually one from the above mentioned encodings are used.
The plugin supports all of the above, but you can upload any arbitrary data by sending the raw bytes.

**Comment by drinikol** [comment]
Thank you for answering my question!
