### ISSUE TITLE
Texture2D markNonReadable configuration

### ISSUE THREAD

**Issue by GavanWilhite** [Benedicht/BestHTTP-Issues#72]
On Line 157 in HTTPResponse there is a hardcoded constant for "markNonReadable". Can you please provide a way to modify this dynamically?

**Comment by Benedicht** [comment]
`DataAsTexture2D` aims to handle a generic case where the texture loaded from a remote server and no script is expected to read/modify the texture. Marking it readable would consume (much) [more memory](https://docs.unity3d.com/ScriptReference/TextureImporter-isReadable.html) as it would have to keep it in both GPU and system memory.
So, while it's not going to change, you can write an extension method to create a new function and use it with ease:
```cs
using BestHTTP;

using UnityEngine;

public static class HTTPResponseExtensions
{
    public static Texture2D GetDataAsReadableTexture2D(this HTTPResponse response)
    {
        if (response == null || response.Data == null || response.Data.Length == 0)
            return null;

        var texture = new Texture2D(0, 0, TextureFormat.RGBA32, false);
        texture.LoadImage(response.Data, true);

        return texture;
    }
}
```

And you can call it on the HTTPResponse object:
```cs
void OnRequestFinished(HTTPRequest req, HTTPResponse resp)
{
    var texture = resp.GetDataAsReadableTexture2D();

    // ...
}
```

**Comment by GavanWilhite** [comment]
Thank you, this is perfect
