### ISSUE TITLE
[Error] Dublicate of class ConcurrentStack<T>

### ISSUE THREAD

**Issue by vandelpal** [Benedicht/BestHTTP-Issues#73]
Step for reproducing: Update Unity to version 2020.3.19f1 and see to console:
Library\PackageCache\com.unity.scriptablebuildpipeline@1.19.0\Editor\Utilities\BuildCache.cs(347,21): error CS0433: The type 'ConcurrentStack<T>' exists in both 'BestHTTP.
scriptablebuildpipeline v1.19.0  is the default dependency of this unity version.

**Comment by Benedicht** [comment]
It seems i no longer use `ConcurrentStack` included in the plugin. You can delete from the \Best HTTP\Source\PlatformSupport\Collections\Concurrent\ directory.
