### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by edgar-rodrigo-santos** [Benedicht/BestHTTP-Issues#76]
We are building and sending an HTTPRequest like this:

HTTPRequest request = new HTTPRequest(<url>, HTTPMethods.Post);
request.AddField(...)
request.AddBinaryData(...)
request.AddHeader(...)
HTTPResponse httpResponse = await request.GetHTTPResponseAsync();

We are also making sure we do the dispose methods:
request.Dispose()
httpResponse.Dispose()

If we do a memory snapshot at the start of the app, and then a memory snapshot at the end, we see alot of referenced binary data, header fields, etc in Unity3d's memory profiler (checking the "diff" between the snapshots). 

We could be ok if these were just from the "last" request, but they're not:
![image](https://user-images.githubusercontent.com/60887430/137897240-4eca2ed3-f822-4025-971d-715b2ea2bb02.png)

And here an example of what contains the managed reference to the binary data visible in the screenshot:
![image](https://user-images.githubusercontent.com/60887430/137897384-a033e20c-143b-4924-83ff-503b1c886205.png)

Are we missing something or is this maybe a memory leak in the code itself? 

Thank you

**Comment by Benedicht** [comment]
Do you saw anything interesting while investigating?

**Comment by edgar-rodrigo-santos** [comment]
I did investigate a bit further but couldn't really prove that there's no memory leaks (memory profiling is not so easy to do in a unity application). I assumed that if a memory leak existed, then I would see a lot more memory getting accumulated which didn't seem to be the case.

**Comment by Benedicht** [comment]
There are allocations that are staying until the program terminates, but these are there for a reason. Other, dynamic allocations are not kept or removed after some time.
