### ISSUE TITLE
Potential managed memory leak with HTTP2Stream disposal

### ISSUE THREAD

**Issue by krone128** [Benedicht/BestHTTP-Issues#77]
It seems that HTTP2Stream is subscribed to HTTP2SettingsRegistry, but is not unsubscribed, thus leaving streams, requests, responses etc hanging without garbage collection

Plugin version: 2.5.2
Event subscription line: HTTP2Stream.cs:134

**Comment by Benedicht** [comment]
Thanks for the report! Fixed and going to be available in the next release.
