### ISSUE TITLE
[Bug] Hooking into Application.wantsToQuit causes BestHTTP/2 to break

### ISSUE THREAD

**Issue by SoftwareGuy** [Benedicht/BestHTTP-Issues#78]
This took a little while to investigate, but it seems that there is some weird issue with Best HTTP/2 when utilizing Application.wantsToQuit to intercept and display a confirmation message.

In my Unity project, I use [Application.wantsToQuit](https://docs.unity3d.com/ScriptReference/Application-wantsToQuit.html) to intercept a quit request and present the player with a "Really quit?" screen. All BestHTTP related calls before implementing the quit prompt works, but when I start using Application.wantsToQuit to intercept the quit request and select No, Best HTTP requests get stuck, as they'll never progress. For example, I have server browser that uses an HTTP API and it "locks up" because Best HTTP isn't fetching the required data. Heck, even using the code provided by Unity's scripting reference causes this issue.

Is this a known issue or is Unity being janky?

**Comment by Benedicht** [comment]
Instad of `Application.wantsToQuit` you have to use `BestHTTP.HTTPUpdateDelegator.OnBeforeApplicationQuit`. It has the same mechanism, but this way the plugin will know wheter the app stays alive to going to quit. When `Application.wantsToQuit` is used the plugin can only assume that the application is quitting and shuts down itself.

**Comment by SoftwareGuy** [comment]
I'm sorry, but I don't quite follow. I tried a quick and dirty way of changing my hooks from `Application.wantsToQuit` and changed it to the `BestHTTP.HTTPUpdateDelegator.OnBeforeApplicationQuit` hook, but when I went to Alt+F4, but it didn't trigger my code to interrupt the quitting process, causing Unity to just exit the game. 

Could you elaborate and/or provide a snippet that demonstrates the said behaviour?

**Comment by Benedicht** [comment]
What version of Unity are you using?

**Comment by SoftwareGuy** [comment]
I'm using Unity 2020 LTS. More specifically, Unity LTS 2020.3.22f1.

I can confirm that this behavior happens on IL2CPP targets, such as Windows, Android. I assume Linux as well but I haven't tested a Linux non-Server (non-headless) build.

**Comment by Benedicht** [comment]
Forgot that you have to call Application.CancelQuit() as the function's return value only informs the plugin to whether to shut down or not. So it could be something like this:
```csharp
HTTPUpdateDelegator.OnBeforeApplicationQuit += () =>
{       
    // Cancel the current quitting
    Application.CancelQuit();
        
    // Return false, so BestHTTP will not shut down itself
    return false;
};
```

You can also start to show your "really quit?" popup to the user, and when a really quit choosed, you can remove the event handler:
```csharp
// Unsubscribe, so next time we will truly quit
HTTPUpdateDelegator.OnBeforeApplicationQuit = null;

// Really quit now
Application.Quit();
```

I wasn't aware that `Application.CancelQuit()` is got deprecated, however it still works.

**Comment by SoftwareGuy** [comment]
Thanks for the snippet - I'll be right back and let you know the results. 😃

**Comment by SoftwareGuy** [comment]
Alright, got it working. The code snippets you provided were the golden ticket. I now have the server list no longer broken when someone tries to quit the game via Alt+F4 on the main menu.
