### ISSUE TITLE
SignalrCore - OnMessage return false discards all queued messages

### ISSUE THREAD

**Issue by discodonut** [Benedicht/BestHTTP-Issues#8]
The docs for HubConnection say:
> OnMessage: This event is called for every server-sent message. When returns false, no further processing of the message is done by the plugin.

However, the code (consolidated for clarity) looks like this:
```
for (int messageIdx = 0; messageIdx < messages.Count; ++messageIdx) {
    var message = messages[messageIdx];
    if (this.OnMessage != null && !this.OnMessage(this, message))
        return;  <--
```
I think that `return` should really be a `continue`?  Otherwise any other messages in the list will be ignored as the array is cleared before calling this function.

**Comment by Benedicht** [comment]
Yes, it should be a continue.
