### ISSUE TITLE
HubConnection is not thread safe

### ISSUE THREAD

**Issue by FlipSs** [Benedicht/BestHTTP-Issues#80]
Hello.
`HubConnection` is not completely thread safe, you use regular `Dictionary` instead of `ConcurrentDictionary` for invocations and subscriptions and calling methods like `SendAsync` from multiple threads can result in exception.
Example exception:
```System.IndexOutOfRangeException: Index was outside the bounds of the array.\n  at System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x00000] in <00000000000000000000000000000000>:0 \n  at BestHTTP.SignalRCore.HubConnection.InvokeImp (System.String target, System.Object[] args, System.Action`1[T] callback, System.Type itemType, System.Boolean isStreamingInvocation) [0x00000] in <00000000000000000000000000000000>:0 \n  at BestHTTP.SignalRCore.HubConnection.SendAsync (System.String target, System.Threading.CancellationToken cancellationToken, System.Object[] args)```

**Comment by Benedicht** [comment]
That's no surprise because it wasn't built with thread safety in mind. Just switching `invocations` to a `ConcurrentDictionary` isn't going to be enough.

**Comment by Benedicht** [comment]
If you drop me a mail at besthttp@gmail.com i can send you a new version.
