### ISSUE TITLE
Request: Support for neuecc/MessagePack-CSharp

### ISSUE THREAD

**Issue by wgoddard** [Benedicht/BestHTTP-Issues#82]
The MessagePack implementation currently used is not maintained and less feature rich. It would be great to support https://github.com/neuecc/MessagePack-CSharp. As well this would bring greater parity with the back end.

**Comment by Benedicht** [comment]
[Implementation](https://github.com/Benedicht/BestHTTP_Examples/blob/master/SignalRCore/Encoders/MessagePackCSharpProtocol.cs), [documentation](https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/protocols/signalr_core/Encoders.html#messagepack-csharp)

Until the next release, you have to download and add the MessagePackCSharpProtocol.cs to the /Best HTTP/Examples/SignalRCore/Encoders/ folder.
