### ISSUE TITLE
Reconnection issue with SignalR-Core in Long-Polling mode (webgl app)

### ISSUE THREAD

**Issue by desalema70** [Benedicht/BestHTTP-Issues#84]
Hello,

We have an issue with our application (Unity/webgl in a browser connecting to a SignalRCore server) where the connection to the server breaks and cannot be reestablished. This happens systematically when the browser window is hidden or otherwise out-of-focus: in that state, the period between heartbeats gets longer and longer, and it happens that the server times out during the protocol negotiation phase while using the long-polling transport. It should be noted that our app specifies websocket as the preferred transport, but oftentimes this does not work (an issue for another day!) and the library client, as expected, falls back on long-polling.

The problem is that if a connectivity issue arises while negotiating a connection, the library client places the transport in a black list ("triedoutTransports") and that this list is never reset. It should be noted that the preferred transport is not affected as the library client will always try the preferred transport, regardless of previous attempts. As a result, the library client enters a loop where it tries to connect using the preferred transport, then fails, then runs out of available transports, closes with an error, then retries. This sequence repeats until this runs out the clock on the reconnect policy.

We implemented a simple work-around to reset the "triedOutTransports" list in OnHeartbeatUpdate, in the Reconnecting case, just before the StartConnect() call. With this change, the library client always reconnects when the window comes in focus.

                case ConnectionStates.Reconnecting:
                    if (this.reconnectAt != DateTime.MinValue && DateTime.Now >= this.reconnectAt)
                    {
                        this.connectionStartedAt = DateTime.Now;
                        this.reconnectAt = DateTime.MinValue;
                        this.triedoutTransports.Clear(); // <---- the line we added
                        this.StartConnect();
                    }
                    break;

So: is this a desirable fix, or is there a better way to deal with the situation?

Thanks, and sorry for the long-windedness!

**Comment by Benedicht** [comment]
Yes, that's a perfect place to add. What's about the other issue (websocket doesn't connect)?

**Comment by desalema70** [comment]
Thanks for the quick response!

I don’t have a lot of insight into the websocket transport issue: as far as I can see, whenever the library client tries to open a websocket to talk to the signalrcore server it gets a 1006 error. I don’t see any mistake in the uri; and I don’t have anything more to go on. I would sure appreciate a hint there!

**Comment by Benedicht** [comment]
1006 means an abnormal termination of the connection. If i'm remember it right, it also can be if the server's response isn't a websocket upgrade response.

Opening the browser's Developer Tools and checking the Console and Network tabs might give some hints what's going on.  If there's a webgl build that i can try out or if you can send relevant screenshots about those tabs to my email address (besthttp@gmail.com) i might see something that can help.

**Comment by desalema70** [comment]
Hi! I was wondering if you were planning on incorporating a fix for this issue in a forthcoming release? Our patched code seems really solid and we are happy with the functionality; however we would prefer using official releases if possible.

**Comment by Benedicht** [comment]
Yes, i plan to add it to the next release.

**Comment by Benedicht** [comment]
Merged the fix into the branch of the next release.
