### ISSUE TITLE
Compressed HTTP2 Replies Do Not Decompress Before The Callback

### ISSUE THREAD

**Issue by GabeBigBoxVR** [Benedicht/BestHTTP-Issues#85]
We're posting a JSON payload to a graphql endpoint and the reply is coming back only as bytes.  The `response.DataAsText` field is returning garbage.  Upon looking at `response.Data` I can see it's compressed, so manually decompressing the stream appears to work.  I am seeing in the logs that BestHTTP2 is using a regular HTTP2 call and is not chunked or streaming, but `response.IsCompressed` is not returning true.  BestHTTP2 needs to detect the reply is compressed and automatically decompress it when getting data back from an HTTP2 server.

```
HTTPRequest r = new HTTPRequest(
    new Uri("https://testendpoint.that.doesnotexistpublicly.com/graphql"), 
    HTTPMethods.Post,
    (HTTPRequest request, HTTPResponse response) =>
    {
        if (request.State != HTTPRequestStates.Finished)
        {
            Debug.LogError($"Failed to Load title data from. State = {request.State}");
        }

        if (response.IsSuccess)
        {
            MemoryStream dataStream = new MemoryStream(response.Data);
            MemoryStream destStream = new MemoryStream();
            using var decompressor = new GZipStream(dataStream, CompressionMode.Decompress);
            decompressor.CopyTo(destStream);
            destStream.Position = 0;
            StreamReader reader = new StreamReader(destStream);
            string text = reader.ReadToEnd();
            Debug.Log($"Title Data Response {text}");
        }
        else
        {
            Debug.LogError($"Failed to Load title data. State = {response.Message}");
        }
    });
    
    Debug.Log($"Payload for Title Data Load\n {payload}");
    r.RawData = Encoding.UTF8.GetBytes(payload);
    r.SetHeader("Content-Type", "application/json; charset=UTF-8");
    r.SetHeader("Accept-Encoding", "gzip");
    r.Send();
```

**Comment by Benedicht** [comment]
Please try out the following code to dump all the headers received from the server and share what output you received:

```cs
void DumpHeaders(HTTPResponse resp)
{
    if (resp == null)
    {
        Debug.LogWarning("resp == null");
        return;
    }

    foreach(var kvp in resp.Headers)
    {
        for (int i = 0; i < kvp.Value.Count; i++)
        {
            Debug.Log($"'{kvp.Key}' => '{kvp.Value[i]}'");
        }
    }
}

HTTPRequest r = new HTTPRequest(
    new Uri("https://testendpoint.that.doesnotexistpublicly.com/graphql"), 
    HTTPMethods.Post,
    (HTTPRequest request, HTTPResponse response) =>
    {
        if (request.State != HTTPRequestStates.Finished)
        {
            Debug.LogError($"Failed to Load title data from. State = {request.State}");
        }

        if (response.IsSuccess)
        {
            DumpHeaders(response);
        }
        else
        {
            Debug.LogError($"Failed to Load title data. State = {response.Message}");
        }
    });
    
    Debug.Log($"Payload for Title Data Load\n {payload}");
    r.RawData = Encoding.UTF8.GetBytes(payload);
    r.SetHeader("Content-Type", "application/json; charset=UTF-8");
    r.SetHeader("Accept-Encoding", "gzip");
    r.Send();
```

**Comment by GabeBigBoxVR** [comment]
The code sample to dump the headers failed because it's compressed.
When I manually decompress the entire blob it works.

![image](https://user-images.githubusercontent.com/22383358/152183863-b4a2456e-7ea2-42cb-9523-a74c09bce19f.png)

**Comment by Benedicht** [comment]
Headers in a HTTP/2 connections are HPACK encoded and not compressed. 

The data might be compressed by the application server and not the webserver (so the response has no content-encoding header and because there's no content-encoding header, the plugin can't know that the content is compressed).

The `DumpHeaders` is failing not because compression but because the response's Headers is null. And that's quite interesting.

To get a better view what's going on, you can set the plugin's logging level to verbose, replicate your issue and send over the produced logs to me (you can attach it here, or send over to besthttp@gmail.com):
```cs
BestHTTP.HTTPManager.Logger.Level = BestHTTP.Logger.Loglevels.All;
```

You can read more about logging in the plugin here: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/Logging.html

**Comment by GabeBigBoxVR** [comment]
Right, what’s weird is that the same request from postman works correctly. I’ll get full logs for you.

Gabe

On Feb 2, 2022, at 7:39 AM, Tivadar György Nagy ***@***.***> wrote:

﻿

Headers in a HTTP/2 connections are HPACK encoded and not compressed.

The data might be compressed by the application server and not the webserver (so the response has no content-encoding header and because there's no content-encoding header, the plugin can't know that the content is compressed).

The DumpHeaders is failing not because compression but because the response's Headers is null. And that's quite interesting.

To get a better view what's going on, you can set the plugin's logging level to verbose, replicate your issue and send over the produced logs to me (you can attach it here, or send over to ***@***.******@***.***>):

BestHTTP.HTTPManager.Logger.Level = BestHTTP.Logger.Loglevels.All;

You can read more about logging in the plugin here: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/Logging.html<https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/Logging.html>

**Comment by GabeBigBoxVR** [comment]
Email sent

**Comment by GabeBigBoxVR** [comment]
One thing to note is that this endpoint works correctly in Postman.
