### ISSUE TITLE
Create an example for connecting to a standard Azure SignalR implementation

### ISSUE THREAD

**Issue by peterhuisman** [Benedicht/BestHTTP-Issues#86]
When following the standard Azure tutorials for using the new SignalR service (like https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-javascript), we get a working Azure Function, a Negotiation endpoint and a client app that works with the deployed infrastructure. 
It would be nice to have a Unity Client connecting to this SignalR service via the Azure Function negotiation endpoint, but I can't get it work with the default examples, as they seem to connect in a different maner...

**Comment by Benedicht** [comment]
Added more documentation: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/protocols/signalr_core/AzureSignalRService.html#azure-signalr-service-with-azure-functions
