### ISSUE TITLE
signalr core null exception problem

### ISSUE THREAD

**Issue by kopan** [Benedicht/BestHTTP-Issues#87]
hubconnection.cs

this.rwLock.Dispose(); 

need null check

**Comment by Benedicht** [comment]
With regular usage it shouldn't be a problem. How did you triggeren the exception there?

**Comment by kopan** [comment]
> With regular usage it shouldn't be a problem. How did you triggeren the exception there?

It occurs when you repeatedly connect to a server with slow response, such as accessing a US server from Asia.

**Comment by Benedicht** [comment]
You mean by reusing the HubConnection instance?

**Comment by kopan** [comment]
No, I always use a new hub connection instance.

**Comment by Benedicht** [comment]
Hmm, that's interesting. Could you set the plugin's log level to verbose by adding the following line somewhere in your startup code:
```cs
BestHTTP.HTTPManager.Logger.Level = BestHTTP.Logger.Loglevels.All;
```

Replicate the exception and send over the (Editor)log to me (you can send it to my email address too: besthttp@gmail.com).  You can read more about logging in the plugin here: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/Logging.html
