### ISSUE TITLE
Using Sockets under WebGL violates the STOMP protocol

### ISSUE THREAD

**Issue by Phil-Bo** [Benedicht/BestHTTP-Issues#88]
Hello 

We use BestHttp to establish a connection to a server leveraging the STOMP protocol. 
This works for mobile native builds out of the box but using the WebGL library leads to a violation of the STOMP protocol 
>The body is then followed by the null byte (0x00)

([Stomp documentation](http://stomp.github.io/stomp-specification-1.1.html#STOMP_Frames))

The mentioned null byte is cut out as a delimiter the send function of the BestHTTP_WebSocket.jslib due to using UTF8ToString().

```
WS_Send_String: function (id, str)
{
		var socket = ws.Get(id);
		var str = UTF8ToString(str);
...
```
This makes the Websocket unable to communicate via STOMP protocol.

**Comment by Benedicht** [comment]
[Emscripten's UTF8ToString](https://emscripten.org/docs/api_reference/preamble.js.html#UTF8ToString) expects a null-terminated string and doesn't include it in the final string.

**Comment by Phil-Bo** [comment]
Yes, which is the problem when you want to adapt the STOMP protocol that needs a null byte in the string as a delimiter marking a complete message.

**Comment by Benedicht** [comment]
That was more of a note to myself what and why causes the issue.

**Comment by Benedicht** [comment]
Could you send over an email to my mail address (besthttp@gmail.com) so i can send back a new package that you could try out?

**Comment by Benedicht** [comment]
Fix confirmed to work, going into the next release.
