### ISSUE TITLE
Update Allocation in the editor

### ISSUE THREAD

**Issue by TheSmallPixel** [Benedicht/BestHTTP-Issues#9]
Increasing the mouse clicking cause this in the editor
![image](https://user-images.githubusercontent.com/25280244/79334229-2b475e80-7f20-11ea-8930-b035b3385d52.png)

**Comment by Benedicht** [comment]
@TheSmallPixel Could you elaborate on the reproduction steps?

**Comment by TheSmallPixel** [comment]
I have a system that simulates the mouse for bug test purposes, launching multiple mouse events in low time.
To replicate this, just try to have an auto clicker or a macro that clicks on objects that receive a raycast and launches an event.

I don't know how this can take effect, I'm currently using SignalRCore for webgl.

**Comment by Benedicht** [comment]
@TheSmallPixel 

Couldn't reproduce it. Could you send a repro project to me? Slightly differences can make it work.
Also, do you send anything to the server in that event?

**Comment by TheSmallPixel** [comment]
Sorry, i  can't share the repo.., do you have time for a conf call?

**Comment by Benedicht** [comment]
Sorry, that's not an option currently. Maybe new, smaller project? Also, do you send anything to the server in that event that called on the triggerd mouse click?

**Comment by TheSmallPixel** [comment]
Nothing is sent to the server at the time, the connection is active but nothing is asked

**Comment by Benedicht** [comment]
I'm out of ideas.

**Comment by TheSmallPixel** [comment]
I understand that it is difficult to try in this way, I try to make a test project and pass it to you.
Maybe tomorrow I can.
Thanks a lot anyway.
In the meantime I wanted to tell you that the work you have done is wonderful.

**Comment by TheSmallPixel** [comment]
ok , im back.
Most of the problems were mine.
An unsuspected object was loading its content, 
Is it convenient to use MessagePack to reduce json allocation?
Every time I upload one of my objects I receive 60mb of GC in the json Converter.

**Comment by Benedicht** [comment]
@TheSmallPixel I definately recommend to try out the messagepack transport!
