### ISSUE TITLE
Support SignalR Core with MessagePack-CSharp Encoders on iphone?

### ISSUE THREAD

**Issue by frank12001** [Benedicht/BestHTTP-Issues#91]
this is the error message from xcode "overload is not supported in MessagePackSerializer.NonGenerics"
 
but it's work find when i use MessagePack-CSharp directly.

**Comment by Benedicht** [comment]
You can find a new version here: https://github.com/Benedicht/BestHTTP_Examples/blob/master/SignalRCore/Encoders/MessagePackCSharpProtocol.cs
You havet o overwrite the old one in the `\Best HTTP\Examples\SignalRCore\Encoders\` folder.

But note that you still have to read through [MessagePack-CSharp's Unity Support](https://github.com/neuecc/MessagePack-CSharp#unity-support) section and do the required steps.

**Comment by frank12001** [comment]
It's work.
Thank you for your help.
