### ISSUE TITLE
SignalR and Messagepacks causing editor to freeze

### ISSUE THREAD

**Issue by windowslucker1121** [Benedicht/BestHTTP-Issues#92]
Hey,

im using this BestHTTP for the connection between a server and Unity. 
SignalR is handling all stuff for me and the message is sent with MessagePacks.
With my pure Websocket Implementation everything is running fine and smooth, so i clearly suspect the BestHTTP package.
Im using this in a realtime machine simulation - transform matrices and new meshes are calculated in the backend and my simulation received the new data every frame. 
At the beginning everything is smooth - within 2 seconds of moving parts the editor will freeze and my fps drop to 0.
When i kill the backend server - the editor will smooth out and gets useable again.
The profiler tells me, that its the garbagecollector in the HTTPUpdateDelegator's update function that causes this issue. 
(see the attached screenshot)
![Unbenannt](https://user-images.githubusercontent.com/59010961/160598892-a9df4ead-8786-448a-8c89-210844b437e5.PNG)

How can i fix this? Are there any Hub options im not aware of?

**Comment by Benedicht** [comment]
I see there's a `HTTP_Manager_Call` is that a marker you added?

**Comment by Benedicht** [comment]
While it has more overhead, Deep Profile might show where's the time is spent. Also note that HTTPManager calls all your callbacks too, so anything you do or allocates contributes to the time you see for the HTTPUpdateDelegator/HTTPManager.OnUpdate()  calls.

**Comment by windowslucker1121** [comment]
I will do a Deep Profile tomorrow. Thanks for that tip.
Will keep you updated.

**Comment by Benedicht** [comment]
Any update?
