### ISSUE TITLE
Best HTTP adds increases Android build by about ~ 3.6 mb 

### ISSUE THREAD

**Issue by tallior** [Benedicht/BestHTTP-Issues#94]
Adding Best HTTP increases our build size by about ~ 3.6 mb.

I already read the docs that describe how to remove certain components: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/HowToDisableFeatures.html

Removing almost everything that we don't require makes things a bit better, but still the size addition is around ~ 3 mb.

Is this the expected size of Best HTTP? is there anything else to do about it?

**Comment by Benedicht** [comment]
The one that you can add to gain the most is **BESTHTTP_DISABLE_ALTERNATE_SSL**, it disables HTTP/2 support however.

**Comment by egaponenko-ma** [comment]
@Benedicht are there any other drawbacks for disabling alternate SSL except of no HTTP/2 support?

**Comment by Benedicht** [comment]
@egaponenko-ma The [TLS Security Addon](https://assetstore.unity.com/packages/tools/network/best-http-2-tls-security-addon-184441) also works only with Bouncy Castle (the laternate TLS handler).
