### ISSUE TITLE
Webgl browser screen freezes on quitting application with socket.io 

### ISSUE THREAD

**Issue by sivabalan-m** [Benedicht/BestHTTP-Issues#95]
Our WebGL application freezes when we try to quit. This is happening only when we connect to socket.io, otherwise there is no issue in quitting the app. The unity app is integrated with another reatcjs app.

We are using this code to quit our app:
`unityInstance.Quit(function() {
    console.log("done!");
});
unityInstance = null;`

We are connecting to the socket.io server using this code:
`Socketmanager = new SocketManager(new Uri(SocketUri));`
We also close the socket manager just before quitting:
`socketmanager.Close();`

We got no error or warning message in the browser console. In the browser task manager, the cpu usage value reaches 100 during the issue

BestHTTP/2 asset version: 2.6.2
socket.io 3+
Unity Editor 2020.3.18 (LTS)

**Comment by Benedicht** [comment]
Thanks for the report!
Unfortunately, i couldn't replicate your issue. Could you create and send a minimal repro project?

**Comment by sivabalan-m** [comment]
We found that the issue is due to the socket manager is not closed properly. When we gave a 0.5-second delay for the socket manager to close and then quit, the issue does not occur. Now we got another problem to solve - delaying the browser navigation button click - is that possible?

The reason you could not replicate, might be you are reloading your entire page. The issue actually occurs when we redirect to a route within the page.

**Comment by Benedicht** [comment]
I see. I think in this case you just shouldn't try to close the socket manager. You can't delay the browser's navigation, and the browser already going to clean up everything (including closing any open connections to the server).
