### ISSUE TITLE
crash of best http on android

### ISSUE THREAD

**Issue by Jaymz1688** [Benedicht/BestHTTP-Issues#97]
besthttp version : 1.3.2
android firebase console stack:
crashed：Thread #1
SIGSEGV 0x0000006baee91020
0
libil2cpp.so
Salsa20Engine.cs
ProcessBytes
1
libil2cpp.so
Salsa20Engine.cs
ProcessBytes
2
libil2cpp.so
Chacha20Poly1305.cs
EncodePlaintext
3
libil2cpp.so
RecordStream.cs
WriteRecord
4
libil2cpp.so
TlsProtocol.cs
SafeWriteRecord
5
libil2cpp.so
TlsProtocol.cs
WriteData
6
libil2cpp.so
WriteOnlyBufferedStream.cs
Flush
7
libil2cpp.so
HTTPRequest.cs
SendOutTo
8
libil2cpp.so
HTTP1Handler.cs
RunHandler
9
libil2cpp.so
HTTPConnection.cs
ThreadFunc
10
libil2cpp.so
Action.cs
Invoke
11
libil2cpp.so
ParameterizedThreadStart.cs
Invoke
12
libil2cpp.so
ContextCallback.cs
Invoke
13
libil2cpp.so
ExecutionContext.cs
RunInternal
14
libil2cpp.so
ParameterizedThreadStart.cs
Invoke
15
libil2cpp.so
Il2CppInvokerTable.cpp - Line 70655
RuntimeInvoker_TrueVoid_t700C6383A2A510C2CF4DD86DABD5CA9FF70ADAC5_RuntimeObject(void (*)(), MethodInfo const*, void*, void**) + 70655
16
libil2cpp.so
Runtime.cpp - Line 568
il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) + 568
17
libil2cpp.so
Thread.cpp - Line 156
il2cpp::icalls::mscorlib::System::Threading::ThreadStart(void*) + 156
18
libil2cpp.so
Thread.cpp - Line 183
il2cpp::os::Thread::RunWrapper(void*) + 183
19
libil2cpp.so
ThreadImpl.cpp - Line 125
il2cpp::os::ThreadImpl::ThreadStartWrapper(void*) + 125
20
libc.so
(缺少 UUID 0f39fc790debeef5bc191987ab30a3f5)
21
libc.so
(缺少 UUID 0f39fc790debeef5bc191987ab30a3f5)

We have been using best http at high frequency in our games
I want to know what happened
Hope you can understand
thank you

**Comment by Benedicht** [comment]
Unfortunately, Best HTTP v1.3.2 isn't supported any more, but even so, even the v1.x line has a newer version (v1.12.5) that you should be able to upgrade to.

As far as i can remember, i had to disable the ChaCha implementation in one of the versions because of this crash and got enabled again only in v2.6.0.

**Comment by Benedicht** [comment]
I see. If you had crashes in v2.6.0 then i think they will be there in v2.6.2 too. I'm not aware of any crashes with the plugin and didn't fixed any in the last two versions. But, if there's any, it would be good to get stack traces so i would have a chanse to fix them. Please reopen or create a new issue if you have new stack traces.
(The implementation that you have creashes in v2.3.0 are modified in v2.6.0 with a newer implementation.)

The only crash i'm aware of is a bug in Unity 2020.03.19 or older that can be triggered by using many threads.

**Comment by Jaymz1688** [comment]
We checked the release notes of Unity, the problem should be on the multi-threaded invoke, our current Unity version is 2020.3.16f, we will try to upgrade to a newer version of Unity, if the problem persists, I will give feedback to you, thank you so much
