### ISSUE TITLE
AddField doesn't work well

### ISSUE THREAD

**Issue by emanonhero** [Benedicht/BestHTTP-Issues#98]
`var request = new HTTPRequest(new Uri($"http:/**/api/Card/"), HTTPMethods.Get);
        request.AddField("CardNo", CardNo);`

it works in windows. but it doesn't work in webGL.

**Comment by Benedicht** [comment]
Under WebGL the plugin has to use the underlying browser's `XmlHTTPRequest` implementation. `XmlHTTPRequest` when used with GET will encode and append the form to the url.
I would suggest to use POST requests when a payload is sent with the request.
