### ISSUE TITLE
Game crashes after updating to version Best HTTP/2 to version 2.6.2 (Apr 18, 2022) and Best HTTP/2 - TLS Security package to version 1.1.0

### ISSUE THREAD

**Issue by BlueTeaNLAccount** [Benedicht/BestHTTP-Issues#99]
Game crashes after updating to version Best HTTP/2 to version 2.6.2 (Apr 18, 2022) and Best HTTP/2 - TLS Security package to version 1.1.0. After reversing to previous version it works again. I don't have a lot of information.

Unity version: 2020.3.35f1 
Best HTTP/2 version: 2.6.2 
Best HTTP/2 - TLS Security version: 1.1.0
Log:
========== OUTPUTTING STACK TRACE ==================

0x00007FFFCACC1A46 (mono-2.0-bdwgc) GC_malloc_kind
0x00007FFFCAAC774D (mono-2.0-bdwgc) mono_object_hash
0x00007FFFCAA6D3E1 (mono-2.0-bdwgc) mono_string_new_size
0x00007FFFCAA678AB (mono-2.0-bdwgc) mono_ldstr
0x00007FFFCAA67847 (mono-2.0-bdwgc) mono_ldstr
0x00007FFFCAB71A0A (mono-2.0-bdwgc) mono_set_defaults
0x000002CE91077ABA (Mono JIT Code) (wrapper managed-to-native) object:__icall_wrapper_mono_helper_ldstr (intptr,intptr)
0x000002CE6F7E11B3 (Mono JIT Code) BestHTTP.Connections.TLS.Crypto.Impl.FastGcmBlockCipher:CheckStatus ()
0x000002CE6F7E102B (Mono JIT Code) BestHTTP.Connections.TLS.Crypto.Impl.FastGcmBlockCipher:ProcessAadBytes (byte[],int,int)
0x000002CE6F7DBB8B (Mono JIT Code) BestHTTP.Connections.TLS.Crypto.Impl.FastGcmBlockCipher:Init (bool,BestHTTP.SecureProtocol.Org.BouncyCastle.Crypto.ICipherParameters)
0x000002CE6F7DB3CA (Mono JIT Code) BestHTTP.Connections.TLS.Crypto.Impl.FastTlsAeadCipherImpl:Init (byte[],int,byte[])
0x000002CE6E718FDF (Mono JIT Code) BestHTTP.Connections.TLS.Crypto.Impl.FastTlsAeadCipher:EncodePlaintext (long,int16,BestHTTP.SecureProtocol.Org.BouncyCastle.Tls.ProtocolVersion,int,byte[],int,int)
0x000002CE6D548410 (Mono JIT Code) BestHTTP.SecureProtocol.Org.BouncyCastle.Tls.RecordStream:WriteRecord (int16,byte[],int,int)
0x000002CE91077C8B (Mono JIT Code) BestHTTP.SecureProtocol.Org.BouncyCastle.Tls.TlsProtocol:RaiseAlertFatal (int16,string,System.Exception)
0x000002CE91077BA0 (Mono JIT Code) BestHTTP.SecureProtocol.Org.BouncyCastle.Tls.TlsProtocol:HandleException (int16,string,System.Exception)
0x000002CE6D549BA6 (Mono JIT Code) BestHTTP.SecureProtocol.Org.BouncyCastle.Tls.TlsProtocol:SafeReadRecord ()
0x000002CE91076EBC (Mono JIT Code) BestHTTP.SecureProtocol.Org.BouncyCastle.Tls.TlsProtocol:TestApplicationData ()
0x000002CE6F795F1B (Mono JIT Code) BestHTTP.Connections.HTTPConnection:TestConnection ()
0x000002CE6D2C3D05 (Mono JIT Code) BestHTTP.Core.HostConnection:GetNextAvailable (BestHTTP.HTTPRequest)
0x000002CE6D2C3B6B (Mono JIT Code) BestHTTP.Core.HostConnection:Send (BestHTTP.HTTPRequest)
0x000002CE6D2C31EB (Mono JIT Code) BestHTTP.Core.HostDefinition:Send (BestHTTP.HTTPRequest)
0x000002CE6D2C0E73 (Mono JIT Code) BestHTTP.Core.RequestEventHelper:ProcessQueue ()
0x000002CE6D2C01CB (Mono JIT Code) BestHTTP.HTTPManager:OnUpdate ()
0x000002CE6D2BFEB3 (Mono JIT Code) BestHTTP.HTTPUpdateDelegator:Update ()
0x000002CE6D2001E0 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007FFFCAADF1E0 (mono-2.0-bdwgc) mono_get_runtime_build_info
0x00007FFFCAA62AC2 (mono-2.0-bdwgc) mono_perfcounters_init
0x00007FFFCAA6BB1F (mono-2.0-bdwgc) mono_runtime_invoke
0x00007FFFCBA0CFAD (UnityPlayer) UnityMain
0x00007FFFCBA0A0A2 (UnityPlayer) UnityMain
0x00007FFFCB9F1973 (UnityPlayer) UnityMain
0x00007FFFCB9F1A4F (UnityPlayer) UnityMain
0x00007FFFCB761BD0 (UnityPlayer) UnityMain
0x00007FFFCB8980CA (UnityPlayer) UnityMain
0x00007FFFCB898170 (UnityPlayer) UnityMain
0x00007FFFCB89C408 (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFCB65C6BA)
0x00007FFFCB65C6BA (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFCB65AB8B)
0x00007FFFCB65AB8B (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFFCB65FD02)
0x00007FFFCB65FD02 (UnityPlayer) (function-name not available)
0x00007FFFCB660C8B (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FF6CD8411F2)
0x00007FF6CD8411F2 (Vista_College_VR) (function-name not available)
0x00007FF88C5C244D (KERNEL32) BaseThreadInitThunk
0x00007FF88D4CDF88 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

**Comment by Benedicht** [comment]
Could you drop me a mail to besthttp@gmail.com, so i can send you a test version?
